// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_ST_fsm_state1 = "1";
const sc_lv<2> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_ST_fsm_pp0_stage0 = "10";
const bool dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_boolean_1 = true;
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv1_1 = "1";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_1 = "1";
const bool dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_boolean_0 = false;
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_0 = "0000";
const sc_lv<1> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv1_0 = "0";
const sc_lv<15> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv15_7C00 = "111110000000000";
const sc_lv<15> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv15_7CC8 = "111110011001000";
const sc_lv<15> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv15_3F8 = "1111111000";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_1 = "1";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_8 = "1000";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_2 = "10";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_3 = "11";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_4 = "100";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_5 = "101";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_6 = "110";
const sc_lv<4> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv4_7 = "111";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_8 = "1000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_F = "1111";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_10 = "10000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_17 = "10111";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_18 = "11000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_1F = "11111";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_20 = "100000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_27 = "100111";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_28 = "101000";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_2F = "101111";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_5 = "101";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_4 = "100";
const sc_lv<32> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv32_B = "1011";
const sc_lv<8> dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::ap_const_lv8_0 = "00000000";

dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w2_V_U = new dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_w2_V("w2_V_U");
    w2_V_U->clk(ap_clk);
    w2_V_U->reset(ap_rst);
    w2_V_U->address0(w2_V_address0);
    w2_V_U->ce0(w2_V_ce0);
    w2_V_U->q0(w2_V_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_acc_0_V_fu_526_p2);
    sensitive << ( p_Val2_6_reg_225 );
    sensitive << ( sext_ln703_fu_522_p1 );

    SC_METHOD(thread_acc_1_V_fu_555_p2);
    sensitive << ( p_Val2_88_reg_211 );
    sensitive << ( sext_ln703_1_fu_551_p1 );

    SC_METHOD(thread_acc_2_V_fu_584_p2);
    sensitive << ( p_Val2_910_reg_197 );
    sensitive << ( sext_ln703_2_fu_580_p1 );

    SC_METHOD(thread_acc_3_V_fu_613_p2);
    sensitive << ( p_Val2_1012_reg_183 );
    sensitive << ( sext_ln703_3_fu_609_p1 );

    SC_METHOD(thread_acc_4_V_fu_642_p2);
    sensitive << ( p_Val2_1114_reg_169 );
    sensitive << ( sext_ln703_4_fu_638_p1 );

    SC_METHOD(thread_acc_5_V_fu_671_p2);
    sensitive << ( p_Val2_1216_reg_155 );
    sensitive << ( sext_ln703_5_fu_667_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_condition_136);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln46_reg_787_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_enable_reg_pp0_iter0);
    sensitive << ( ap_start );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_idle_pp0_0to1);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_w_index17_phi_fu_129_p6);
    sensitive << ( w_index17_reg_125 );
    sensitive << ( w_index_reg_782 );
    sensitive << ( icmp_ln46_reg_787 );
    sensitive << ( ap_condition_136 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( icmp_ln46_fu_250_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_ap_reset_idle_pp0);
    sensitive << ( ap_start );
    sensitive << ( ap_idle_pp0_0to1 );

    SC_METHOD(thread_ap_return_0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln46_reg_787_pp0_iter1_reg );
    sensitive << ( acc_0_V_fu_526_p2 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_return_0_preg );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln46_reg_787_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( acc_1_V_fu_555_p2 );
    sensitive << ( ap_return_1_preg );

    SC_METHOD(thread_ap_return_2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln46_reg_787_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( acc_2_V_fu_584_p2 );
    sensitive << ( ap_return_2_preg );

    SC_METHOD(thread_ap_return_3);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln46_reg_787_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( acc_3_V_fu_613_p2 );
    sensitive << ( ap_return_3_preg );

    SC_METHOD(thread_ap_return_4);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln46_reg_787_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( acc_4_V_fu_642_p2 );
    sensitive << ( ap_return_4_preg );

    SC_METHOD(thread_ap_return_5);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln46_reg_787_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( acc_5_V_fu_671_p2 );
    sensitive << ( ap_return_5_preg );

    SC_METHOD(thread_icmp_ln19_1_fu_298_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( w_index17_reg_125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln19_2_fu_304_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( w_index17_reg_125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln19_3_fu_310_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( w_index17_reg_125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln19_4_fu_316_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( w_index17_reg_125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln19_5_fu_322_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( w_index17_reg_125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln19_6_fu_328_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( w_index17_reg_125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln19_7_fu_334_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( w_index17_reg_125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln19_fu_292_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( w_index17_reg_125 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_icmp_ln46_fu_250_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_phi_mux_w_index17_phi_fu_129_p6 );

    SC_METHOD(thread_mul_ln1118_75_fu_535_p0);
    sensitive << ( tmp_382_i_reg_801 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_75_fu_535_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1116_fu_500_p1 );

    SC_METHOD(thread_mul_ln1118_75_fu_535_p2);
    sensitive << ( mul_ln1118_75_fu_535_p0 );
    sensitive << ( mul_ln1118_75_fu_535_p1 );

    SC_METHOD(thread_mul_ln1118_76_fu_564_p0);
    sensitive << ( tmp_384_i_reg_806 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_76_fu_564_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1116_fu_500_p1 );

    SC_METHOD(thread_mul_ln1118_76_fu_564_p2);
    sensitive << ( mul_ln1118_76_fu_564_p0 );
    sensitive << ( mul_ln1118_76_fu_564_p1 );

    SC_METHOD(thread_mul_ln1118_77_fu_593_p0);
    sensitive << ( tmp_386_i_reg_811 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_77_fu_593_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1116_fu_500_p1 );

    SC_METHOD(thread_mul_ln1118_77_fu_593_p2);
    sensitive << ( mul_ln1118_77_fu_593_p0 );
    sensitive << ( mul_ln1118_77_fu_593_p1 );

    SC_METHOD(thread_mul_ln1118_78_fu_622_p0);
    sensitive << ( tmp_388_i_reg_816 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_78_fu_622_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1116_fu_500_p1 );

    SC_METHOD(thread_mul_ln1118_78_fu_622_p2);
    sensitive << ( mul_ln1118_78_fu_622_p0 );
    sensitive << ( mul_ln1118_78_fu_622_p1 );

    SC_METHOD(thread_mul_ln1118_79_fu_651_p0);
    sensitive << ( tmp_390_i_reg_821 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_79_fu_651_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1116_fu_500_p1 );

    SC_METHOD(thread_mul_ln1118_79_fu_651_p2);
    sensitive << ( mul_ln1118_79_fu_651_p0 );
    sensitive << ( mul_ln1118_79_fu_651_p1 );

    SC_METHOD(thread_mul_ln1118_fu_506_p0);
    sensitive << ( trunc_ln59_reg_796 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_mul_ln1118_fu_506_p1);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln1116_fu_500_p1 );

    SC_METHOD(thread_mul_ln1118_fu_506_p2);
    sensitive << ( mul_ln1118_fu_506_p0 );
    sensitive << ( mul_ln1118_fu_506_p1 );

    SC_METHOD(thread_or_ln19_1_fu_362_p2);
    sensitive << ( icmp_ln19_5_fu_322_p2 );
    sensitive << ( icmp_ln19_4_fu_316_p2 );

    SC_METHOD(thread_or_ln19_2_fu_376_p2);
    sensitive << ( icmp_ln19_3_fu_310_p2 );
    sensitive << ( icmp_ln19_2_fu_304_p2 );

    SC_METHOD(thread_or_ln19_3_fu_390_p2);
    sensitive << ( icmp_ln19_1_fu_298_p2 );
    sensitive << ( icmp_ln19_fu_292_p2 );

    SC_METHOD(thread_or_ln19_4_fu_404_p2);
    sensitive << ( or_ln19_fu_348_p2 );
    sensitive << ( or_ln19_1_fu_362_p2 );

    SC_METHOD(thread_or_ln19_5_fu_418_p2);
    sensitive << ( or_ln19_2_fu_376_p2 );
    sensitive << ( or_ln19_3_fu_390_p2 );

    SC_METHOD(thread_or_ln19_6_fu_432_p2);
    sensitive << ( or_ln19_4_fu_404_p2 );
    sensitive << ( or_ln19_5_fu_418_p2 );

    SC_METHOD(thread_or_ln19_fu_348_p2);
    sensitive << ( icmp_ln19_7_fu_334_p2 );
    sensitive << ( icmp_ln19_6_fu_328_p2 );

    SC_METHOD(thread_select_ln19_1_fu_354_p3);
    sensitive << ( kernel_data_V_4414 );
    sensitive << ( kernel_data_V_5415 );
    sensitive << ( icmp_ln19_5_fu_322_p2 );

    SC_METHOD(thread_select_ln19_2_fu_368_p3);
    sensitive << ( kernel_data_V_2412 );
    sensitive << ( kernel_data_V_3413 );
    sensitive << ( icmp_ln19_3_fu_310_p2 );

    SC_METHOD(thread_select_ln19_3_fu_382_p3);
    sensitive << ( kernel_data_V_0 );
    sensitive << ( kernel_data_V_1411 );
    sensitive << ( icmp_ln19_1_fu_298_p2 );

    SC_METHOD(thread_select_ln19_4_fu_396_p3);
    sensitive << ( or_ln19_fu_348_p2 );
    sensitive << ( select_ln19_fu_340_p3 );
    sensitive << ( select_ln19_1_fu_354_p3 );

    SC_METHOD(thread_select_ln19_5_fu_410_p3);
    sensitive << ( or_ln19_2_fu_376_p2 );
    sensitive << ( select_ln19_2_fu_368_p3 );
    sensitive << ( select_ln19_3_fu_382_p3 );

    SC_METHOD(thread_select_ln19_6_fu_424_p3);
    sensitive << ( or_ln19_4_fu_404_p2 );
    sensitive << ( select_ln19_4_fu_396_p3 );
    sensitive << ( select_ln19_5_fu_410_p3 );

    SC_METHOD(thread_select_ln19_7_fu_438_p3);
    sensitive << ( kernel_data_V_8 );
    sensitive << ( or_ln19_6_fu_432_p2 );
    sensitive << ( select_ln19_6_fu_424_p3 );

    SC_METHOD(thread_select_ln19_fu_340_p3);
    sensitive << ( kernel_data_V_6 );
    sensitive << ( kernel_data_V_7 );
    sensitive << ( icmp_ln19_7_fu_334_p2 );

    SC_METHOD(thread_sext_ln703_1_fu_551_p1);
    sensitive << ( trunc_ln708_s_fu_541_p4 );

    SC_METHOD(thread_sext_ln703_2_fu_580_p1);
    sensitive << ( trunc_ln708_84_fu_570_p4 );

    SC_METHOD(thread_sext_ln703_3_fu_609_p1);
    sensitive << ( trunc_ln708_85_fu_599_p4 );

    SC_METHOD(thread_sext_ln703_4_fu_638_p1);
    sensitive << ( trunc_ln708_86_fu_628_p4 );

    SC_METHOD(thread_sext_ln703_5_fu_667_p1);
    sensitive << ( trunc_ln708_87_fu_657_p4 );

    SC_METHOD(thread_sext_ln703_fu_522_p1);
    sensitive << ( trunc_ln_fu_512_p4 );

    SC_METHOD(thread_trunc_ln59_fu_446_p1);
    sensitive << ( w2_V_q0 );

    SC_METHOD(thread_trunc_ln708_84_fu_570_p4);
    sensitive << ( mul_ln1118_76_fu_564_p2 );

    SC_METHOD(thread_trunc_ln708_85_fu_599_p4);
    sensitive << ( mul_ln1118_77_fu_593_p2 );

    SC_METHOD(thread_trunc_ln708_86_fu_628_p4);
    sensitive << ( mul_ln1118_78_fu_622_p2 );

    SC_METHOD(thread_trunc_ln708_87_fu_657_p4);
    sensitive << ( mul_ln1118_79_fu_651_p2 );

    SC_METHOD(thread_trunc_ln708_s_fu_541_p4);
    sensitive << ( mul_ln1118_75_fu_535_p2 );

    SC_METHOD(thread_trunc_ln_fu_512_p4);
    sensitive << ( mul_ln1118_fu_506_p2 );

    SC_METHOD(thread_w2_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( zext_ln59_fu_239_p1 );

    SC_METHOD(thread_w2_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_w_index_fu_244_p2);
    sensitive << ( ap_phi_mux_w_index17_phi_fu_129_p6 );

    SC_METHOD(thread_zext_ln1116_fu_500_p1);
    sensitive << ( select_ln19_7_reg_791 );

    SC_METHOD(thread_zext_ln59_fu_239_p1);
    sensitive << ( ap_phi_mux_w_index17_phi_fu_129_p6 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_reset_idle_pp0 );

    ap_CS_fsm = "01";
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_return_0_preg = "00000000";
    ap_return_1_preg = "00000000";
    ap_return_2_preg = "00000000";
    ap_return_3_preg = "00000000";
    ap_return_4_preg = "00000000";
    ap_return_5_preg = "00000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, kernel_data_V_8, "(port)kernel_data_V_8");
    sc_trace(mVcdFile, kernel_data_V_0, "(port)kernel_data_V_0");
    sc_trace(mVcdFile, kernel_data_V_1411, "(port)kernel_data_V_1411");
    sc_trace(mVcdFile, kernel_data_V_2412, "(port)kernel_data_V_2412");
    sc_trace(mVcdFile, kernel_data_V_3413, "(port)kernel_data_V_3413");
    sc_trace(mVcdFile, kernel_data_V_4414, "(port)kernel_data_V_4414");
    sc_trace(mVcdFile, kernel_data_V_5415, "(port)kernel_data_V_5415");
    sc_trace(mVcdFile, kernel_data_V_6, "(port)kernel_data_V_6");
    sc_trace(mVcdFile, kernel_data_V_7, "(port)kernel_data_V_7");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_return_2, "(port)ap_return_2");
    sc_trace(mVcdFile, ap_return_3, "(port)ap_return_3");
    sc_trace(mVcdFile, ap_return_4, "(port)ap_return_4");
    sc_trace(mVcdFile, ap_return_5, "(port)ap_return_5");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, icmp_ln46_fu_250_p2, "icmp_ln46_fu_250_p2");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, w2_V_address0, "w2_V_address0");
    sc_trace(mVcdFile, w2_V_ce0, "w2_V_ce0");
    sc_trace(mVcdFile, w2_V_q0, "w2_V_q0");
    sc_trace(mVcdFile, w_index17_reg_125, "w_index17_reg_125");
    sc_trace(mVcdFile, p_Val2_1216_reg_155, "p_Val2_1216_reg_155");
    sc_trace(mVcdFile, p_Val2_1114_reg_169, "p_Val2_1114_reg_169");
    sc_trace(mVcdFile, p_Val2_1012_reg_183, "p_Val2_1012_reg_183");
    sc_trace(mVcdFile, p_Val2_910_reg_197, "p_Val2_910_reg_197");
    sc_trace(mVcdFile, p_Val2_88_reg_211, "p_Val2_88_reg_211");
    sc_trace(mVcdFile, p_Val2_6_reg_225, "p_Val2_6_reg_225");
    sc_trace(mVcdFile, w_index_fu_244_p2, "w_index_fu_244_p2");
    sc_trace(mVcdFile, w_index_reg_782, "w_index_reg_782");
    sc_trace(mVcdFile, icmp_ln46_reg_787, "icmp_ln46_reg_787");
    sc_trace(mVcdFile, icmp_ln46_reg_787_pp0_iter1_reg, "icmp_ln46_reg_787_pp0_iter1_reg");
    sc_trace(mVcdFile, select_ln19_7_fu_438_p3, "select_ln19_7_fu_438_p3");
    sc_trace(mVcdFile, select_ln19_7_reg_791, "select_ln19_7_reg_791");
    sc_trace(mVcdFile, trunc_ln59_fu_446_p1, "trunc_ln59_fu_446_p1");
    sc_trace(mVcdFile, trunc_ln59_reg_796, "trunc_ln59_reg_796");
    sc_trace(mVcdFile, tmp_382_i_reg_801, "tmp_382_i_reg_801");
    sc_trace(mVcdFile, tmp_384_i_reg_806, "tmp_384_i_reg_806");
    sc_trace(mVcdFile, tmp_386_i_reg_811, "tmp_386_i_reg_811");
    sc_trace(mVcdFile, tmp_388_i_reg_816, "tmp_388_i_reg_816");
    sc_trace(mVcdFile, tmp_390_i_reg_821, "tmp_390_i_reg_821");
    sc_trace(mVcdFile, acc_0_V_fu_526_p2, "acc_0_V_fu_526_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, acc_1_V_fu_555_p2, "acc_1_V_fu_555_p2");
    sc_trace(mVcdFile, acc_2_V_fu_584_p2, "acc_2_V_fu_584_p2");
    sc_trace(mVcdFile, acc_3_V_fu_613_p2, "acc_3_V_fu_613_p2");
    sc_trace(mVcdFile, acc_4_V_fu_642_p2, "acc_4_V_fu_642_p2");
    sc_trace(mVcdFile, acc_5_V_fu_671_p2, "acc_5_V_fu_671_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_phi_mux_w_index17_phi_fu_129_p6, "ap_phi_mux_w_index17_phi_fu_129_p6");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, zext_ln59_fu_239_p1, "zext_ln59_fu_239_p1");
    sc_trace(mVcdFile, icmp_ln19_7_fu_334_p2, "icmp_ln19_7_fu_334_p2");
    sc_trace(mVcdFile, icmp_ln19_6_fu_328_p2, "icmp_ln19_6_fu_328_p2");
    sc_trace(mVcdFile, icmp_ln19_5_fu_322_p2, "icmp_ln19_5_fu_322_p2");
    sc_trace(mVcdFile, icmp_ln19_4_fu_316_p2, "icmp_ln19_4_fu_316_p2");
    sc_trace(mVcdFile, icmp_ln19_3_fu_310_p2, "icmp_ln19_3_fu_310_p2");
    sc_trace(mVcdFile, icmp_ln19_2_fu_304_p2, "icmp_ln19_2_fu_304_p2");
    sc_trace(mVcdFile, icmp_ln19_1_fu_298_p2, "icmp_ln19_1_fu_298_p2");
    sc_trace(mVcdFile, icmp_ln19_fu_292_p2, "icmp_ln19_fu_292_p2");
    sc_trace(mVcdFile, or_ln19_fu_348_p2, "or_ln19_fu_348_p2");
    sc_trace(mVcdFile, select_ln19_fu_340_p3, "select_ln19_fu_340_p3");
    sc_trace(mVcdFile, select_ln19_1_fu_354_p3, "select_ln19_1_fu_354_p3");
    sc_trace(mVcdFile, or_ln19_1_fu_362_p2, "or_ln19_1_fu_362_p2");
    sc_trace(mVcdFile, or_ln19_2_fu_376_p2, "or_ln19_2_fu_376_p2");
    sc_trace(mVcdFile, select_ln19_2_fu_368_p3, "select_ln19_2_fu_368_p3");
    sc_trace(mVcdFile, select_ln19_3_fu_382_p3, "select_ln19_3_fu_382_p3");
    sc_trace(mVcdFile, or_ln19_3_fu_390_p2, "or_ln19_3_fu_390_p2");
    sc_trace(mVcdFile, or_ln19_4_fu_404_p2, "or_ln19_4_fu_404_p2");
    sc_trace(mVcdFile, select_ln19_4_fu_396_p3, "select_ln19_4_fu_396_p3");
    sc_trace(mVcdFile, select_ln19_5_fu_410_p3, "select_ln19_5_fu_410_p3");
    sc_trace(mVcdFile, or_ln19_5_fu_418_p2, "or_ln19_5_fu_418_p2");
    sc_trace(mVcdFile, or_ln19_6_fu_432_p2, "or_ln19_6_fu_432_p2");
    sc_trace(mVcdFile, select_ln19_6_fu_424_p3, "select_ln19_6_fu_424_p3");
    sc_trace(mVcdFile, mul_ln1118_fu_506_p0, "mul_ln1118_fu_506_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_506_p1, "mul_ln1118_fu_506_p1");
    sc_trace(mVcdFile, zext_ln1116_fu_500_p1, "zext_ln1116_fu_500_p1");
    sc_trace(mVcdFile, mul_ln1118_fu_506_p2, "mul_ln1118_fu_506_p2");
    sc_trace(mVcdFile, trunc_ln_fu_512_p4, "trunc_ln_fu_512_p4");
    sc_trace(mVcdFile, sext_ln703_fu_522_p1, "sext_ln703_fu_522_p1");
    sc_trace(mVcdFile, mul_ln1118_75_fu_535_p0, "mul_ln1118_75_fu_535_p0");
    sc_trace(mVcdFile, mul_ln1118_75_fu_535_p1, "mul_ln1118_75_fu_535_p1");
    sc_trace(mVcdFile, mul_ln1118_75_fu_535_p2, "mul_ln1118_75_fu_535_p2");
    sc_trace(mVcdFile, trunc_ln708_s_fu_541_p4, "trunc_ln708_s_fu_541_p4");
    sc_trace(mVcdFile, sext_ln703_1_fu_551_p1, "sext_ln703_1_fu_551_p1");
    sc_trace(mVcdFile, mul_ln1118_76_fu_564_p0, "mul_ln1118_76_fu_564_p0");
    sc_trace(mVcdFile, mul_ln1118_76_fu_564_p1, "mul_ln1118_76_fu_564_p1");
    sc_trace(mVcdFile, mul_ln1118_76_fu_564_p2, "mul_ln1118_76_fu_564_p2");
    sc_trace(mVcdFile, trunc_ln708_84_fu_570_p4, "trunc_ln708_84_fu_570_p4");
    sc_trace(mVcdFile, sext_ln703_2_fu_580_p1, "sext_ln703_2_fu_580_p1");
    sc_trace(mVcdFile, mul_ln1118_77_fu_593_p0, "mul_ln1118_77_fu_593_p0");
    sc_trace(mVcdFile, mul_ln1118_77_fu_593_p1, "mul_ln1118_77_fu_593_p1");
    sc_trace(mVcdFile, mul_ln1118_77_fu_593_p2, "mul_ln1118_77_fu_593_p2");
    sc_trace(mVcdFile, trunc_ln708_85_fu_599_p4, "trunc_ln708_85_fu_599_p4");
    sc_trace(mVcdFile, sext_ln703_3_fu_609_p1, "sext_ln703_3_fu_609_p1");
    sc_trace(mVcdFile, mul_ln1118_78_fu_622_p0, "mul_ln1118_78_fu_622_p0");
    sc_trace(mVcdFile, mul_ln1118_78_fu_622_p1, "mul_ln1118_78_fu_622_p1");
    sc_trace(mVcdFile, mul_ln1118_78_fu_622_p2, "mul_ln1118_78_fu_622_p2");
    sc_trace(mVcdFile, trunc_ln708_86_fu_628_p4, "trunc_ln708_86_fu_628_p4");
    sc_trace(mVcdFile, sext_ln703_4_fu_638_p1, "sext_ln703_4_fu_638_p1");
    sc_trace(mVcdFile, mul_ln1118_79_fu_651_p0, "mul_ln1118_79_fu_651_p0");
    sc_trace(mVcdFile, mul_ln1118_79_fu_651_p1, "mul_ln1118_79_fu_651_p1");
    sc_trace(mVcdFile, mul_ln1118_79_fu_651_p2, "mul_ln1118_79_fu_651_p2");
    sc_trace(mVcdFile, trunc_ln708_87_fu_657_p4, "trunc_ln708_87_fu_657_p4");
    sc_trace(mVcdFile, sext_ln703_5_fu_667_p1, "sext_ln703_5_fu_667_p1");
    sc_trace(mVcdFile, ap_return_0_preg, "ap_return_0_preg");
    sc_trace(mVcdFile, ap_return_1_preg, "ap_return_1_preg");
    sc_trace(mVcdFile, ap_return_2_preg, "ap_return_2_preg");
    sc_trace(mVcdFile, ap_return_3_preg, "ap_return_3_preg");
    sc_trace(mVcdFile, ap_return_4_preg, "ap_return_4_preg");
    sc_trace(mVcdFile, ap_return_5_preg, "ap_return_5_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0_0to1, "ap_idle_pp0_0to1");
    sc_trace(mVcdFile, ap_reset_idle_pp0, "ap_reset_idle_pp0");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_136, "ap_condition_136");
#endif

    }
}

dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::~dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete w2_V_U;
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_start.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_0_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
            ap_return_0_preg = acc_0_V_fu_526_p2.read().range(11, 4);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_1_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
            ap_return_1_preg = acc_1_V_fu_555_p2.read().range(11, 4);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_2_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
            ap_return_2_preg = acc_2_V_fu_584_p2.read().range(11, 4);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_3_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
            ap_return_3_preg = acc_3_V_fu_613_p2.read().range(11, 4);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_4_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
            ap_return_4_preg = acc_4_V_fu_642_p2.read().range(11, 4);
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_5_preg = ap_const_lv8_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
            ap_return_5_preg = acc_5_V_fu_671_p2.read().range(11, 4);
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_reg_787_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        p_Val2_1012_reg_183 = acc_3_V_fu_613_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read())))) {
        p_Val2_1012_reg_183 = ap_const_lv15_7CC8;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_reg_787_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        p_Val2_1114_reg_169 = acc_4_V_fu_642_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read())))) {
        p_Val2_1114_reg_169 = ap_const_lv15_7C00;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_reg_787_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        p_Val2_1216_reg_155 = acc_5_V_fu_671_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read())))) {
        p_Val2_1216_reg_155 = ap_const_lv15_7C00;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_reg_787_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        p_Val2_6_reg_225 = acc_0_V_fu_526_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read())))) {
        p_Val2_6_reg_225 = ap_const_lv15_7C00;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_reg_787_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        p_Val2_88_reg_211 = acc_1_V_fu_555_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read())))) {
        p_Val2_88_reg_211 = ap_const_lv15_3F8;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_reg_787_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        p_Val2_910_reg_197 = acc_2_V_fu_584_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read())))) {
        p_Val2_910_reg_197 = ap_const_lv15_3F8;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln46_reg_787.read(), ap_const_lv1_0))) {
        w_index17_reg_125 = w_index_reg_782.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787.read())))) {
        w_index17_reg_125 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln46_reg_787 = icmp_ln46_fu_250_p2.read();
        icmp_ln46_reg_787_pp0_iter1_reg = icmp_ln46_reg_787.read();
        select_ln19_7_reg_791 = select_ln19_7_fu_438_p3.read();
        tmp_382_i_reg_801 = w2_V_q0.read().range(15, 8);
        tmp_384_i_reg_806 = w2_V_q0.read().range(23, 16);
        tmp_386_i_reg_811 = w2_V_q0.read().range(31, 24);
        tmp_388_i_reg_816 = w2_V_q0.read().range(39, 32);
        tmp_390_i_reg_821 = w2_V_q0.read().range(47, 40);
        trunc_ln59_reg_796 = trunc_ln59_fu_446_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        w_index_reg_782 = w_index_fu_244_p2.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_acc_0_V_fu_526_p2() {
    acc_0_V_fu_526_p2 = (!p_Val2_6_reg_225.read().is_01() || !sext_ln703_fu_522_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_6_reg_225.read()) + sc_bigint<15>(sext_ln703_fu_522_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_acc_1_V_fu_555_p2() {
    acc_1_V_fu_555_p2 = (!p_Val2_88_reg_211.read().is_01() || !sext_ln703_1_fu_551_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_88_reg_211.read()) + sc_bigint<15>(sext_ln703_1_fu_551_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_acc_2_V_fu_584_p2() {
    acc_2_V_fu_584_p2 = (!p_Val2_910_reg_197.read().is_01() || !sext_ln703_2_fu_580_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_910_reg_197.read()) + sc_bigint<15>(sext_ln703_2_fu_580_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_acc_3_V_fu_613_p2() {
    acc_3_V_fu_613_p2 = (!p_Val2_1012_reg_183.read().is_01() || !sext_ln703_3_fu_609_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_1012_reg_183.read()) + sc_bigint<15>(sext_ln703_3_fu_609_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_acc_4_V_fu_642_p2() {
    acc_4_V_fu_642_p2 = (!p_Val2_1114_reg_169.read().is_01() || !sext_ln703_4_fu_638_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_1114_reg_169.read()) + sc_bigint<15>(sext_ln703_4_fu_638_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_acc_5_V_fu_671_p2() {
    acc_5_V_fu_671_p2 = (!p_Val2_1216_reg_155.read().is_01() || !sext_ln703_5_fu_667_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(p_Val2_1216_reg_155.read()) + sc_bigint<15>(sext_ln703_5_fu_667_p1.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_condition_136() {
    ap_condition_136 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_enable_reg_pp0_iter0() {
    ap_enable_reg_pp0_iter0 = ap_start.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_idle_pp0_0to1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0_0to1 = ap_const_logic_1;
    } else {
        ap_idle_pp0_0to1 = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_phi_mux_w_index17_phi_fu_129_p6() {
    if (esl_seteq<1,1,1>(ap_condition_136.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787.read())) {
            ap_phi_mux_w_index17_phi_fu_129_p6 = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(icmp_ln46_reg_787.read(), ap_const_lv1_0)) {
            ap_phi_mux_w_index17_phi_fu_129_p6 = w_index_reg_782.read();
        } else {
            ap_phi_mux_w_index17_phi_fu_129_p6 = w_index17_reg_125.read();
        }
    } else {
        ap_phi_mux_w_index17_phi_fu_129_p6 = w_index17_reg_125.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(icmp_ln46_fu_250_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_reset_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_idle_pp0_0to1.read()))) {
        ap_reset_idle_pp0 = ap_const_logic_1;
    } else {
        ap_reset_idle_pp0 = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_return_0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
        ap_return_0 = acc_0_V_fu_526_p2.read().range(11, 4);
    } else {
        ap_return_0 = ap_return_0_preg.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_return_1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
        ap_return_1 = acc_1_V_fu_555_p2.read().range(11, 4);
    } else {
        ap_return_1 = ap_return_1_preg.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_return_2() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
        ap_return_2 = acc_2_V_fu_584_p2.read().range(11, 4);
    } else {
        ap_return_2 = ap_return_2_preg.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_return_3() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
        ap_return_3 = acc_3_V_fu_613_p2.read().range(11, 4);
    } else {
        ap_return_3 = ap_return_3_preg.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_return_4() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
        ap_return_4 = acc_4_V_fu_642_p2.read().range(11, 4);
    } else {
        ap_return_4 = ap_return_4_preg.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_return_5() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln46_reg_787_pp0_iter1_reg.read()))) {
        ap_return_5 = acc_5_V_fu_671_p2.read().range(11, 4);
    } else {
        ap_return_5 = ap_return_5_preg.read();
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln19_1_fu_298_p2() {
    icmp_ln19_1_fu_298_p2 = (!w_index17_reg_125.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<1>(): sc_lv<1>(w_index17_reg_125.read() == ap_const_lv4_1);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln19_2_fu_304_p2() {
    icmp_ln19_2_fu_304_p2 = (!w_index17_reg_125.read().is_01() || !ap_const_lv4_2.is_01())? sc_lv<1>(): sc_lv<1>(w_index17_reg_125.read() == ap_const_lv4_2);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln19_3_fu_310_p2() {
    icmp_ln19_3_fu_310_p2 = (!w_index17_reg_125.read().is_01() || !ap_const_lv4_3.is_01())? sc_lv<1>(): sc_lv<1>(w_index17_reg_125.read() == ap_const_lv4_3);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln19_4_fu_316_p2() {
    icmp_ln19_4_fu_316_p2 = (!w_index17_reg_125.read().is_01() || !ap_const_lv4_4.is_01())? sc_lv<1>(): sc_lv<1>(w_index17_reg_125.read() == ap_const_lv4_4);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln19_5_fu_322_p2() {
    icmp_ln19_5_fu_322_p2 = (!w_index17_reg_125.read().is_01() || !ap_const_lv4_5.is_01())? sc_lv<1>(): sc_lv<1>(w_index17_reg_125.read() == ap_const_lv4_5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln19_6_fu_328_p2() {
    icmp_ln19_6_fu_328_p2 = (!w_index17_reg_125.read().is_01() || !ap_const_lv4_6.is_01())? sc_lv<1>(): sc_lv<1>(w_index17_reg_125.read() == ap_const_lv4_6);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln19_7_fu_334_p2() {
    icmp_ln19_7_fu_334_p2 = (!w_index17_reg_125.read().is_01() || !ap_const_lv4_7.is_01())? sc_lv<1>(): sc_lv<1>(w_index17_reg_125.read() == ap_const_lv4_7);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln19_fu_292_p2() {
    icmp_ln19_fu_292_p2 = (!w_index17_reg_125.read().is_01() || !ap_const_lv4_0.is_01())? sc_lv<1>(): sc_lv<1>(w_index17_reg_125.read() == ap_const_lv4_0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_icmp_ln46_fu_250_p2() {
    icmp_ln46_fu_250_p2 = (!ap_phi_mux_w_index17_phi_fu_129_p6.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_w_index17_phi_fu_129_p6.read() == ap_const_lv4_8);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_75_fu_535_p0() {
    mul_ln1118_75_fu_535_p0 = tmp_382_i_reg_801.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_75_fu_535_p1() {
    mul_ln1118_75_fu_535_p1 =  (sc_lv<8>) (zext_ln1116_fu_500_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_75_fu_535_p2() {
    mul_ln1118_75_fu_535_p2 = (!mul_ln1118_75_fu_535_p0.read().is_01() || !mul_ln1118_75_fu_535_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln1118_75_fu_535_p0.read()) * sc_biguint<8>(mul_ln1118_75_fu_535_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_76_fu_564_p0() {
    mul_ln1118_76_fu_564_p0 = tmp_384_i_reg_806.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_76_fu_564_p1() {
    mul_ln1118_76_fu_564_p1 =  (sc_lv<8>) (zext_ln1116_fu_500_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_76_fu_564_p2() {
    mul_ln1118_76_fu_564_p2 = (!mul_ln1118_76_fu_564_p0.read().is_01() || !mul_ln1118_76_fu_564_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln1118_76_fu_564_p0.read()) * sc_biguint<8>(mul_ln1118_76_fu_564_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_77_fu_593_p0() {
    mul_ln1118_77_fu_593_p0 = tmp_386_i_reg_811.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_77_fu_593_p1() {
    mul_ln1118_77_fu_593_p1 =  (sc_lv<8>) (zext_ln1116_fu_500_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_77_fu_593_p2() {
    mul_ln1118_77_fu_593_p2 = (!mul_ln1118_77_fu_593_p0.read().is_01() || !mul_ln1118_77_fu_593_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln1118_77_fu_593_p0.read()) * sc_biguint<8>(mul_ln1118_77_fu_593_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_78_fu_622_p0() {
    mul_ln1118_78_fu_622_p0 = tmp_388_i_reg_816.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_78_fu_622_p1() {
    mul_ln1118_78_fu_622_p1 =  (sc_lv<8>) (zext_ln1116_fu_500_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_78_fu_622_p2() {
    mul_ln1118_78_fu_622_p2 = (!mul_ln1118_78_fu_622_p0.read().is_01() || !mul_ln1118_78_fu_622_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln1118_78_fu_622_p0.read()) * sc_biguint<8>(mul_ln1118_78_fu_622_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_79_fu_651_p0() {
    mul_ln1118_79_fu_651_p0 = tmp_390_i_reg_821.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_79_fu_651_p1() {
    mul_ln1118_79_fu_651_p1 =  (sc_lv<8>) (zext_ln1116_fu_500_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_79_fu_651_p2() {
    mul_ln1118_79_fu_651_p2 = (!mul_ln1118_79_fu_651_p0.read().is_01() || !mul_ln1118_79_fu_651_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln1118_79_fu_651_p0.read()) * sc_biguint<8>(mul_ln1118_79_fu_651_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_fu_506_p0() {
    mul_ln1118_fu_506_p0 = trunc_ln59_reg_796.read();
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_fu_506_p1() {
    mul_ln1118_fu_506_p1 =  (sc_lv<8>) (zext_ln1116_fu_500_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_mul_ln1118_fu_506_p2() {
    mul_ln1118_fu_506_p2 = (!mul_ln1118_fu_506_p0.read().is_01() || !mul_ln1118_fu_506_p1.read().is_01())? sc_lv<16>(): sc_bigint<8>(mul_ln1118_fu_506_p0.read()) * sc_biguint<8>(mul_ln1118_fu_506_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_or_ln19_1_fu_362_p2() {
    or_ln19_1_fu_362_p2 = (icmp_ln19_5_fu_322_p2.read() | icmp_ln19_4_fu_316_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_or_ln19_2_fu_376_p2() {
    or_ln19_2_fu_376_p2 = (icmp_ln19_3_fu_310_p2.read() | icmp_ln19_2_fu_304_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_or_ln19_3_fu_390_p2() {
    or_ln19_3_fu_390_p2 = (icmp_ln19_1_fu_298_p2.read() | icmp_ln19_fu_292_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_or_ln19_4_fu_404_p2() {
    or_ln19_4_fu_404_p2 = (or_ln19_fu_348_p2.read() | or_ln19_1_fu_362_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_or_ln19_5_fu_418_p2() {
    or_ln19_5_fu_418_p2 = (or_ln19_2_fu_376_p2.read() | or_ln19_3_fu_390_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_or_ln19_6_fu_432_p2() {
    or_ln19_6_fu_432_p2 = (or_ln19_4_fu_404_p2.read() | or_ln19_5_fu_418_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_or_ln19_fu_348_p2() {
    or_ln19_fu_348_p2 = (icmp_ln19_7_fu_334_p2.read() | icmp_ln19_6_fu_328_p2.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_select_ln19_1_fu_354_p3() {
    select_ln19_1_fu_354_p3 = (!icmp_ln19_5_fu_322_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln19_5_fu_322_p2.read()[0].to_bool())? kernel_data_V_5415.read(): kernel_data_V_4414.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_select_ln19_2_fu_368_p3() {
    select_ln19_2_fu_368_p3 = (!icmp_ln19_3_fu_310_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln19_3_fu_310_p2.read()[0].to_bool())? kernel_data_V_3413.read(): kernel_data_V_2412.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_select_ln19_3_fu_382_p3() {
    select_ln19_3_fu_382_p3 = (!icmp_ln19_1_fu_298_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln19_1_fu_298_p2.read()[0].to_bool())? kernel_data_V_1411.read(): kernel_data_V_0.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_select_ln19_4_fu_396_p3() {
    select_ln19_4_fu_396_p3 = (!or_ln19_fu_348_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln19_fu_348_p2.read()[0].to_bool())? select_ln19_fu_340_p3.read(): select_ln19_1_fu_354_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_select_ln19_5_fu_410_p3() {
    select_ln19_5_fu_410_p3 = (!or_ln19_2_fu_376_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln19_2_fu_376_p2.read()[0].to_bool())? select_ln19_2_fu_368_p3.read(): select_ln19_3_fu_382_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_select_ln19_6_fu_424_p3() {
    select_ln19_6_fu_424_p3 = (!or_ln19_4_fu_404_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln19_4_fu_404_p2.read()[0].to_bool())? select_ln19_4_fu_396_p3.read(): select_ln19_5_fu_410_p3.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_select_ln19_7_fu_438_p3() {
    select_ln19_7_fu_438_p3 = (!or_ln19_6_fu_432_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln19_6_fu_432_p2.read()[0].to_bool())? select_ln19_6_fu_424_p3.read(): kernel_data_V_8.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_select_ln19_fu_340_p3() {
    select_ln19_fu_340_p3 = (!icmp_ln19_7_fu_334_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln19_7_fu_334_p2.read()[0].to_bool())? kernel_data_V_7.read(): kernel_data_V_6.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_sext_ln703_1_fu_551_p1() {
    sext_ln703_1_fu_551_p1 = esl_sext<15,11>(trunc_ln708_s_fu_541_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_sext_ln703_2_fu_580_p1() {
    sext_ln703_2_fu_580_p1 = esl_sext<15,11>(trunc_ln708_84_fu_570_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_sext_ln703_3_fu_609_p1() {
    sext_ln703_3_fu_609_p1 = esl_sext<15,11>(trunc_ln708_85_fu_599_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_sext_ln703_4_fu_638_p1() {
    sext_ln703_4_fu_638_p1 = esl_sext<15,11>(trunc_ln708_86_fu_628_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_sext_ln703_5_fu_667_p1() {
    sext_ln703_5_fu_667_p1 = esl_sext<15,11>(trunc_ln708_87_fu_657_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_sext_ln703_fu_522_p1() {
    sext_ln703_fu_522_p1 = esl_sext<15,11>(trunc_ln_fu_512_p4.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_trunc_ln59_fu_446_p1() {
    trunc_ln59_fu_446_p1 = w2_V_q0.read().range(8-1, 0);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_trunc_ln708_84_fu_570_p4() {
    trunc_ln708_84_fu_570_p4 = mul_ln1118_76_fu_564_p2.read().range(15, 5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_trunc_ln708_85_fu_599_p4() {
    trunc_ln708_85_fu_599_p4 = mul_ln1118_77_fu_593_p2.read().range(15, 5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_trunc_ln708_86_fu_628_p4() {
    trunc_ln708_86_fu_628_p4 = mul_ln1118_78_fu_622_p2.read().range(15, 5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_trunc_ln708_87_fu_657_p4() {
    trunc_ln708_87_fu_657_p4 = mul_ln1118_79_fu_651_p2.read().range(15, 5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_trunc_ln708_s_fu_541_p4() {
    trunc_ln708_s_fu_541_p4 = mul_ln1118_75_fu_535_p2.read().range(15, 5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_trunc_ln_fu_512_p4() {
    trunc_ln_fu_512_p4 = mul_ln1118_fu_506_p2.read().range(15, 5);
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_w2_V_address0() {
    w2_V_address0 =  (sc_lv<4>) (zext_ln59_fu_239_p1.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_w2_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        w2_V_ce0 = ap_const_logic_1;
    } else {
        w2_V_ce0 = ap_const_logic_0;
    }
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_w_index_fu_244_p2() {
    w_index_fu_244_p2 = (!ap_const_lv4_1.is_01() || !ap_phi_mux_w_index17_phi_fu_129_p6.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_1) + sc_biguint<4>(ap_phi_mux_w_index17_phi_fu_129_p6.read()));
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_zext_ln1116_fu_500_p1() {
    zext_ln1116_fu_500_p1 = esl_zext<16,8>(select_ln19_7_reg_791.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_zext_ln59_fu_239_p1() {
    zext_ln59_fu_239_p1 = esl_zext<64,4>(ap_phi_mux_w_index17_phi_fu_129_p6.read());
}

void dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_reset_idle_pp0.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reset_idle_pp0.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

