Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    dense:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_1:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    dense_1_linear:
      Precision:
        result: auto
      Trace: false
    dense_linear:
      Precision:
        result: auto
      Trace: false
    flatten:
      Precision:
        result: auto
      Trace: false
    gru:
      Precision:
        bias: auto
        recurrent_bias: auto
        recurrent_weight: auto
        result: auto
        weight: auto
      Trace: false
    input_1:
      Precision:
        result: auto
      Trace: false
    relu_0:
      Precision:
        result: auto
      Trace: false
    relu_1:
      Precision:
        result: auto
      Trace: false
    rnn_densef:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: false
    rnn_densef_linear:
      Precision:
        result: auto
      Trace: false
    softmax:
      Precision:
        result: auto
      Trace: false
      implementation: argmax
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: ap_fixed<20,10>
    ReuseFactor: 64
    Strategy: Resource
    TraceOutput: false
IOType: io_stream
InputData: null
InputShapes:
  input_1:
  - 100
  - 3
KerasModel: !keras_model 'model_1/hls4ml_gru/name/keras_model.keras'
OutputDir: model_2/hls4ml_gru
OutputPredictions: null
OutputShapes:
  layer12_out:
  - 5
Part: xcu280-fsvh2892-2L-e
ProjectName: myproject
Stamp: 276ec0dc
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteTar: false
  WriteWeightsTxt: true
