Backend: Vivado
ClockPeriod: 5
ClockUncertainty: 12.5%
HLSConfig:
  LayerName:
    conv1d:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: true
    conv1d_1:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: true
    conv1d_1_linear:
      Precision:
        result: auto
      Trace: true
    conv1d_2:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: true
    conv1d_2_linear:
      Precision:
        result: auto
      Trace: true
    conv1d_linear:
      Precision:
        result: auto
      Trace: true
    input_1:
      Precision:
        result: auto
      Trace: true
    lstm_10:
      Precision:
        bias: auto
        recurrent_bias: auto
        recurrent_weight: auto
        result: auto
        weight: auto
      Trace: true
    lstm_11:
      Precision:
        bias: auto
        recurrent_bias: auto
        recurrent_weight: auto
        result: auto
        weight: auto
      Trace: true
    output_softmax:
      Precision:
        result: auto
      Trace: true
      implementation: argmax
    relu_0:
      Precision:
        result: auto
      Trace: true
    relu_1:
      Precision:
        result: auto
      Trace: true
    relu_2:
      Precision:
        result: auto
      Trace: true
    rnn_densef:
      Precision:
        bias: auto
        result: auto
        weight: auto
      Trace: true
    rnn_densef_linear:
      Precision:
        result: auto
      Trace: true
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: ap_fixed<20,10>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
InputShapes:
  input_1:
  - 100
  - 3
KerasModel: !keras_model 'model_1/hls4ml_lstm/name/keras_model.keras'
OutputDir: model_1/hls4ml_lstm/name
OutputPredictions: null
OutputShapes:
  layer15_out:
  - 5
Part: xc7vx690tffg1761-2
ProjectName: myproject
Stamp: 6a8c5b39
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteTar: false
  WriteWeightsTxt: true
