// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module relu_array_ap_fixed_32u_array_ap_fixed_20_10_5_3_0_32u_relu_config6_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        data_V_data_4_V_dout,
        data_V_data_4_V_empty_n,
        data_V_data_4_V_read,
        data_V_data_5_V_dout,
        data_V_data_5_V_empty_n,
        data_V_data_5_V_read,
        data_V_data_6_V_dout,
        data_V_data_6_V_empty_n,
        data_V_data_6_V_read,
        data_V_data_7_V_dout,
        data_V_data_7_V_empty_n,
        data_V_data_7_V_read,
        data_V_data_8_V_dout,
        data_V_data_8_V_empty_n,
        data_V_data_8_V_read,
        data_V_data_9_V_dout,
        data_V_data_9_V_empty_n,
        data_V_data_9_V_read,
        data_V_data_10_V_dout,
        data_V_data_10_V_empty_n,
        data_V_data_10_V_read,
        data_V_data_11_V_dout,
        data_V_data_11_V_empty_n,
        data_V_data_11_V_read,
        data_V_data_12_V_dout,
        data_V_data_12_V_empty_n,
        data_V_data_12_V_read,
        data_V_data_13_V_dout,
        data_V_data_13_V_empty_n,
        data_V_data_13_V_read,
        data_V_data_14_V_dout,
        data_V_data_14_V_empty_n,
        data_V_data_14_V_read,
        data_V_data_15_V_dout,
        data_V_data_15_V_empty_n,
        data_V_data_15_V_read,
        data_V_data_16_V_dout,
        data_V_data_16_V_empty_n,
        data_V_data_16_V_read,
        data_V_data_17_V_dout,
        data_V_data_17_V_empty_n,
        data_V_data_17_V_read,
        data_V_data_18_V_dout,
        data_V_data_18_V_empty_n,
        data_V_data_18_V_read,
        data_V_data_19_V_dout,
        data_V_data_19_V_empty_n,
        data_V_data_19_V_read,
        data_V_data_20_V_dout,
        data_V_data_20_V_empty_n,
        data_V_data_20_V_read,
        data_V_data_21_V_dout,
        data_V_data_21_V_empty_n,
        data_V_data_21_V_read,
        data_V_data_22_V_dout,
        data_V_data_22_V_empty_n,
        data_V_data_22_V_read,
        data_V_data_23_V_dout,
        data_V_data_23_V_empty_n,
        data_V_data_23_V_read,
        data_V_data_24_V_dout,
        data_V_data_24_V_empty_n,
        data_V_data_24_V_read,
        data_V_data_25_V_dout,
        data_V_data_25_V_empty_n,
        data_V_data_25_V_read,
        data_V_data_26_V_dout,
        data_V_data_26_V_empty_n,
        data_V_data_26_V_read,
        data_V_data_27_V_dout,
        data_V_data_27_V_empty_n,
        data_V_data_27_V_read,
        data_V_data_28_V_dout,
        data_V_data_28_V_empty_n,
        data_V_data_28_V_read,
        data_V_data_29_V_dout,
        data_V_data_29_V_empty_n,
        data_V_data_29_V_read,
        data_V_data_30_V_dout,
        data_V_data_30_V_empty_n,
        data_V_data_30_V_read,
        data_V_data_31_V_dout,
        data_V_data_31_V_empty_n,
        data_V_data_31_V_read,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write,
        res_V_data_4_V_din,
        res_V_data_4_V_full_n,
        res_V_data_4_V_write,
        res_V_data_5_V_din,
        res_V_data_5_V_full_n,
        res_V_data_5_V_write,
        res_V_data_6_V_din,
        res_V_data_6_V_full_n,
        res_V_data_6_V_write,
        res_V_data_7_V_din,
        res_V_data_7_V_full_n,
        res_V_data_7_V_write,
        res_V_data_8_V_din,
        res_V_data_8_V_full_n,
        res_V_data_8_V_write,
        res_V_data_9_V_din,
        res_V_data_9_V_full_n,
        res_V_data_9_V_write,
        res_V_data_10_V_din,
        res_V_data_10_V_full_n,
        res_V_data_10_V_write,
        res_V_data_11_V_din,
        res_V_data_11_V_full_n,
        res_V_data_11_V_write,
        res_V_data_12_V_din,
        res_V_data_12_V_full_n,
        res_V_data_12_V_write,
        res_V_data_13_V_din,
        res_V_data_13_V_full_n,
        res_V_data_13_V_write,
        res_V_data_14_V_din,
        res_V_data_14_V_full_n,
        res_V_data_14_V_write,
        res_V_data_15_V_din,
        res_V_data_15_V_full_n,
        res_V_data_15_V_write,
        res_V_data_16_V_din,
        res_V_data_16_V_full_n,
        res_V_data_16_V_write,
        res_V_data_17_V_din,
        res_V_data_17_V_full_n,
        res_V_data_17_V_write,
        res_V_data_18_V_din,
        res_V_data_18_V_full_n,
        res_V_data_18_V_write,
        res_V_data_19_V_din,
        res_V_data_19_V_full_n,
        res_V_data_19_V_write,
        res_V_data_20_V_din,
        res_V_data_20_V_full_n,
        res_V_data_20_V_write,
        res_V_data_21_V_din,
        res_V_data_21_V_full_n,
        res_V_data_21_V_write,
        res_V_data_22_V_din,
        res_V_data_22_V_full_n,
        res_V_data_22_V_write,
        res_V_data_23_V_din,
        res_V_data_23_V_full_n,
        res_V_data_23_V_write,
        res_V_data_24_V_din,
        res_V_data_24_V_full_n,
        res_V_data_24_V_write,
        res_V_data_25_V_din,
        res_V_data_25_V_full_n,
        res_V_data_25_V_write,
        res_V_data_26_V_din,
        res_V_data_26_V_full_n,
        res_V_data_26_V_write,
        res_V_data_27_V_din,
        res_V_data_27_V_full_n,
        res_V_data_27_V_write,
        res_V_data_28_V_din,
        res_V_data_28_V_full_n,
        res_V_data_28_V_write,
        res_V_data_29_V_din,
        res_V_data_29_V_full_n,
        res_V_data_29_V_write,
        res_V_data_30_V_din,
        res_V_data_30_V_full_n,
        res_V_data_30_V_write,
        res_V_data_31_V_din,
        res_V_data_31_V_full_n,
        res_V_data_31_V_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [52:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [52:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [52:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [52:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
input  [52:0] data_V_data_4_V_dout;
input   data_V_data_4_V_empty_n;
output   data_V_data_4_V_read;
input  [52:0] data_V_data_5_V_dout;
input   data_V_data_5_V_empty_n;
output   data_V_data_5_V_read;
input  [52:0] data_V_data_6_V_dout;
input   data_V_data_6_V_empty_n;
output   data_V_data_6_V_read;
input  [52:0] data_V_data_7_V_dout;
input   data_V_data_7_V_empty_n;
output   data_V_data_7_V_read;
input  [52:0] data_V_data_8_V_dout;
input   data_V_data_8_V_empty_n;
output   data_V_data_8_V_read;
input  [52:0] data_V_data_9_V_dout;
input   data_V_data_9_V_empty_n;
output   data_V_data_9_V_read;
input  [52:0] data_V_data_10_V_dout;
input   data_V_data_10_V_empty_n;
output   data_V_data_10_V_read;
input  [52:0] data_V_data_11_V_dout;
input   data_V_data_11_V_empty_n;
output   data_V_data_11_V_read;
input  [52:0] data_V_data_12_V_dout;
input   data_V_data_12_V_empty_n;
output   data_V_data_12_V_read;
input  [52:0] data_V_data_13_V_dout;
input   data_V_data_13_V_empty_n;
output   data_V_data_13_V_read;
input  [52:0] data_V_data_14_V_dout;
input   data_V_data_14_V_empty_n;
output   data_V_data_14_V_read;
input  [52:0] data_V_data_15_V_dout;
input   data_V_data_15_V_empty_n;
output   data_V_data_15_V_read;
input  [52:0] data_V_data_16_V_dout;
input   data_V_data_16_V_empty_n;
output   data_V_data_16_V_read;
input  [52:0] data_V_data_17_V_dout;
input   data_V_data_17_V_empty_n;
output   data_V_data_17_V_read;
input  [52:0] data_V_data_18_V_dout;
input   data_V_data_18_V_empty_n;
output   data_V_data_18_V_read;
input  [52:0] data_V_data_19_V_dout;
input   data_V_data_19_V_empty_n;
output   data_V_data_19_V_read;
input  [52:0] data_V_data_20_V_dout;
input   data_V_data_20_V_empty_n;
output   data_V_data_20_V_read;
input  [52:0] data_V_data_21_V_dout;
input   data_V_data_21_V_empty_n;
output   data_V_data_21_V_read;
input  [52:0] data_V_data_22_V_dout;
input   data_V_data_22_V_empty_n;
output   data_V_data_22_V_read;
input  [52:0] data_V_data_23_V_dout;
input   data_V_data_23_V_empty_n;
output   data_V_data_23_V_read;
input  [52:0] data_V_data_24_V_dout;
input   data_V_data_24_V_empty_n;
output   data_V_data_24_V_read;
input  [52:0] data_V_data_25_V_dout;
input   data_V_data_25_V_empty_n;
output   data_V_data_25_V_read;
input  [52:0] data_V_data_26_V_dout;
input   data_V_data_26_V_empty_n;
output   data_V_data_26_V_read;
input  [52:0] data_V_data_27_V_dout;
input   data_V_data_27_V_empty_n;
output   data_V_data_27_V_read;
input  [52:0] data_V_data_28_V_dout;
input   data_V_data_28_V_empty_n;
output   data_V_data_28_V_read;
input  [52:0] data_V_data_29_V_dout;
input   data_V_data_29_V_empty_n;
output   data_V_data_29_V_read;
input  [52:0] data_V_data_30_V_dout;
input   data_V_data_30_V_empty_n;
output   data_V_data_30_V_read;
input  [52:0] data_V_data_31_V_dout;
input   data_V_data_31_V_empty_n;
output   data_V_data_31_V_read;
output  [19:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [19:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [19:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [19:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;
output  [19:0] res_V_data_4_V_din;
input   res_V_data_4_V_full_n;
output   res_V_data_4_V_write;
output  [19:0] res_V_data_5_V_din;
input   res_V_data_5_V_full_n;
output   res_V_data_5_V_write;
output  [19:0] res_V_data_6_V_din;
input   res_V_data_6_V_full_n;
output   res_V_data_6_V_write;
output  [19:0] res_V_data_7_V_din;
input   res_V_data_7_V_full_n;
output   res_V_data_7_V_write;
output  [19:0] res_V_data_8_V_din;
input   res_V_data_8_V_full_n;
output   res_V_data_8_V_write;
output  [19:0] res_V_data_9_V_din;
input   res_V_data_9_V_full_n;
output   res_V_data_9_V_write;
output  [19:0] res_V_data_10_V_din;
input   res_V_data_10_V_full_n;
output   res_V_data_10_V_write;
output  [19:0] res_V_data_11_V_din;
input   res_V_data_11_V_full_n;
output   res_V_data_11_V_write;
output  [19:0] res_V_data_12_V_din;
input   res_V_data_12_V_full_n;
output   res_V_data_12_V_write;
output  [19:0] res_V_data_13_V_din;
input   res_V_data_13_V_full_n;
output   res_V_data_13_V_write;
output  [19:0] res_V_data_14_V_din;
input   res_V_data_14_V_full_n;
output   res_V_data_14_V_write;
output  [19:0] res_V_data_15_V_din;
input   res_V_data_15_V_full_n;
output   res_V_data_15_V_write;
output  [19:0] res_V_data_16_V_din;
input   res_V_data_16_V_full_n;
output   res_V_data_16_V_write;
output  [19:0] res_V_data_17_V_din;
input   res_V_data_17_V_full_n;
output   res_V_data_17_V_write;
output  [19:0] res_V_data_18_V_din;
input   res_V_data_18_V_full_n;
output   res_V_data_18_V_write;
output  [19:0] res_V_data_19_V_din;
input   res_V_data_19_V_full_n;
output   res_V_data_19_V_write;
output  [19:0] res_V_data_20_V_din;
input   res_V_data_20_V_full_n;
output   res_V_data_20_V_write;
output  [19:0] res_V_data_21_V_din;
input   res_V_data_21_V_full_n;
output   res_V_data_21_V_write;
output  [19:0] res_V_data_22_V_din;
input   res_V_data_22_V_full_n;
output   res_V_data_22_V_write;
output  [19:0] res_V_data_23_V_din;
input   res_V_data_23_V_full_n;
output   res_V_data_23_V_write;
output  [19:0] res_V_data_24_V_din;
input   res_V_data_24_V_full_n;
output   res_V_data_24_V_write;
output  [19:0] res_V_data_25_V_din;
input   res_V_data_25_V_full_n;
output   res_V_data_25_V_write;
output  [19:0] res_V_data_26_V_din;
input   res_V_data_26_V_full_n;
output   res_V_data_26_V_write;
output  [19:0] res_V_data_27_V_din;
input   res_V_data_27_V_full_n;
output   res_V_data_27_V_write;
output  [19:0] res_V_data_28_V_din;
input   res_V_data_28_V_full_n;
output   res_V_data_28_V_write;
output  [19:0] res_V_data_29_V_din;
input   res_V_data_29_V_full_n;
output   res_V_data_29_V_write;
output  [19:0] res_V_data_30_V_din;
input   res_V_data_30_V_full_n;
output   res_V_data_30_V_write;
output  [19:0] res_V_data_31_V_din;
input   res_V_data_31_V_full_n;
output   res_V_data_31_V_write;
output   start_out;
output   start_write;

reg ap_done;
reg ap_idle;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;
reg data_V_data_4_V_read;
reg data_V_data_5_V_read;
reg data_V_data_6_V_read;
reg data_V_data_7_V_read;
reg data_V_data_8_V_read;
reg data_V_data_9_V_read;
reg data_V_data_10_V_read;
reg data_V_data_11_V_read;
reg data_V_data_12_V_read;
reg data_V_data_13_V_read;
reg data_V_data_14_V_read;
reg data_V_data_15_V_read;
reg data_V_data_16_V_read;
reg data_V_data_17_V_read;
reg data_V_data_18_V_read;
reg data_V_data_19_V_read;
reg data_V_data_20_V_read;
reg data_V_data_21_V_read;
reg data_V_data_22_V_read;
reg data_V_data_23_V_read;
reg data_V_data_24_V_read;
reg data_V_data_25_V_read;
reg data_V_data_26_V_read;
reg data_V_data_27_V_read;
reg data_V_data_28_V_read;
reg data_V_data_29_V_read;
reg data_V_data_30_V_read;
reg data_V_data_31_V_read;
reg res_V_data_0_V_write;
reg res_V_data_1_V_write;
reg res_V_data_2_V_write;
reg res_V_data_3_V_write;
reg res_V_data_4_V_write;
reg res_V_data_5_V_write;
reg res_V_data_6_V_write;
reg res_V_data_7_V_write;
reg res_V_data_8_V_write;
reg res_V_data_9_V_write;
reg res_V_data_10_V_write;
reg res_V_data_11_V_write;
reg res_V_data_12_V_write;
reg res_V_data_13_V_write;
reg res_V_data_14_V_write;
reg res_V_data_15_V_write;
reg res_V_data_16_V_write;
reg res_V_data_17_V_write;
reg res_V_data_18_V_write;
reg res_V_data_19_V_write;
reg res_V_data_20_V_write;
reg res_V_data_21_V_write;
reg res_V_data_22_V_write;
reg res_V_data_23_V_write;
reg res_V_data_24_V_write;
reg res_V_data_25_V_write;
reg res_V_data_26_V_write;
reg res_V_data_27_V_write;
reg res_V_data_28_V_write;
reg res_V_data_29_V_write;
reg res_V_data_30_V_write;
reg res_V_data_31_V_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    internal_ap_ready;
wire    io_acc_block_signal_op3;
reg    ap_block_state1_pp0_stage0_iter0;
wire    io_acc_block_signal_op199;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg    data_V_data_0_V_blk_n;
wire    ap_block_pp0_stage0;
reg    data_V_data_1_V_blk_n;
reg    data_V_data_2_V_blk_n;
reg    data_V_data_3_V_blk_n;
reg    data_V_data_4_V_blk_n;
reg    data_V_data_5_V_blk_n;
reg    data_V_data_6_V_blk_n;
reg    data_V_data_7_V_blk_n;
reg    data_V_data_8_V_blk_n;
reg    data_V_data_9_V_blk_n;
reg    data_V_data_10_V_blk_n;
reg    data_V_data_11_V_blk_n;
reg    data_V_data_12_V_blk_n;
reg    data_V_data_13_V_blk_n;
reg    data_V_data_14_V_blk_n;
reg    data_V_data_15_V_blk_n;
reg    data_V_data_16_V_blk_n;
reg    data_V_data_17_V_blk_n;
reg    data_V_data_18_V_blk_n;
reg    data_V_data_19_V_blk_n;
reg    data_V_data_20_V_blk_n;
reg    data_V_data_21_V_blk_n;
reg    data_V_data_22_V_blk_n;
reg    data_V_data_23_V_blk_n;
reg    data_V_data_24_V_blk_n;
reg    data_V_data_25_V_blk_n;
reg    data_V_data_26_V_blk_n;
reg    data_V_data_27_V_blk_n;
reg    data_V_data_28_V_blk_n;
reg    data_V_data_29_V_blk_n;
reg    data_V_data_30_V_blk_n;
reg    data_V_data_31_V_blk_n;
reg    res_V_data_0_V_blk_n;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
reg    res_V_data_4_V_blk_n;
reg    res_V_data_5_V_blk_n;
reg    res_V_data_6_V_blk_n;
reg    res_V_data_7_V_blk_n;
reg    res_V_data_8_V_blk_n;
reg    res_V_data_9_V_blk_n;
reg    res_V_data_10_V_blk_n;
reg    res_V_data_11_V_blk_n;
reg    res_V_data_12_V_blk_n;
reg    res_V_data_13_V_blk_n;
reg    res_V_data_14_V_blk_n;
reg    res_V_data_15_V_blk_n;
reg    res_V_data_16_V_blk_n;
reg    res_V_data_17_V_blk_n;
reg    res_V_data_18_V_blk_n;
reg    res_V_data_19_V_blk_n;
reg    res_V_data_20_V_blk_n;
reg    res_V_data_21_V_blk_n;
reg    res_V_data_22_V_blk_n;
reg    res_V_data_23_V_blk_n;
reg    res_V_data_24_V_blk_n;
reg    res_V_data_25_V_blk_n;
reg    res_V_data_26_V_blk_n;
reg    res_V_data_27_V_blk_n;
reg    res_V_data_28_V_blk_n;
reg    res_V_data_29_V_blk_n;
reg    res_V_data_30_V_blk_n;
reg    res_V_data_31_V_blk_n;
wire   [19:0] tmp_data_0_V_fu_1744_p3;
reg   [19:0] tmp_data_0_V_reg_2000;
wire   [19:0] tmp_data_1_V_fu_1752_p3;
reg   [19:0] tmp_data_1_V_reg_2005;
wire   [19:0] tmp_data_2_V_fu_1760_p3;
reg   [19:0] tmp_data_2_V_reg_2010;
wire   [19:0] tmp_data_3_V_fu_1768_p3;
reg   [19:0] tmp_data_3_V_reg_2015;
wire   [19:0] tmp_data_4_V_fu_1776_p3;
reg   [19:0] tmp_data_4_V_reg_2020;
wire   [19:0] tmp_data_5_V_fu_1784_p3;
reg   [19:0] tmp_data_5_V_reg_2025;
wire   [19:0] tmp_data_6_V_fu_1792_p3;
reg   [19:0] tmp_data_6_V_reg_2030;
wire   [19:0] tmp_data_7_V_fu_1800_p3;
reg   [19:0] tmp_data_7_V_reg_2035;
wire   [19:0] tmp_data_8_V_fu_1808_p3;
reg   [19:0] tmp_data_8_V_reg_2040;
wire   [19:0] tmp_data_9_V_fu_1816_p3;
reg   [19:0] tmp_data_9_V_reg_2045;
wire   [19:0] tmp_data_10_V_fu_1824_p3;
reg   [19:0] tmp_data_10_V_reg_2050;
wire   [19:0] tmp_data_11_V_fu_1832_p3;
reg   [19:0] tmp_data_11_V_reg_2055;
wire   [19:0] tmp_data_12_V_fu_1840_p3;
reg   [19:0] tmp_data_12_V_reg_2060;
wire   [19:0] tmp_data_13_V_fu_1848_p3;
reg   [19:0] tmp_data_13_V_reg_2065;
wire   [19:0] tmp_data_14_V_fu_1856_p3;
reg   [19:0] tmp_data_14_V_reg_2070;
wire   [19:0] tmp_data_15_V_fu_1864_p3;
reg   [19:0] tmp_data_15_V_reg_2075;
wire   [19:0] tmp_data_16_V_fu_1872_p3;
reg   [19:0] tmp_data_16_V_reg_2080;
wire   [19:0] tmp_data_17_V_fu_1880_p3;
reg   [19:0] tmp_data_17_V_reg_2085;
wire   [19:0] tmp_data_18_V_fu_1888_p3;
reg   [19:0] tmp_data_18_V_reg_2090;
wire   [19:0] tmp_data_19_V_fu_1896_p3;
reg   [19:0] tmp_data_19_V_reg_2095;
wire   [19:0] tmp_data_20_V_fu_1904_p3;
reg   [19:0] tmp_data_20_V_reg_2100;
wire   [19:0] tmp_data_21_V_fu_1912_p3;
reg   [19:0] tmp_data_21_V_reg_2105;
wire   [19:0] tmp_data_22_V_fu_1920_p3;
reg   [19:0] tmp_data_22_V_reg_2110;
wire   [19:0] tmp_data_23_V_fu_1928_p3;
reg   [19:0] tmp_data_23_V_reg_2115;
wire   [19:0] tmp_data_24_V_fu_1936_p3;
reg   [19:0] tmp_data_24_V_reg_2120;
wire   [19:0] tmp_data_25_V_fu_1944_p3;
reg   [19:0] tmp_data_25_V_reg_2125;
wire   [19:0] tmp_data_26_V_fu_1952_p3;
reg   [19:0] tmp_data_26_V_reg_2130;
wire   [19:0] tmp_data_27_V_fu_1960_p3;
reg   [19:0] tmp_data_27_V_reg_2135;
wire   [19:0] tmp_data_28_V_fu_1968_p3;
reg   [19:0] tmp_data_28_V_reg_2140;
wire   [19:0] tmp_data_29_V_fu_1976_p3;
reg   [19:0] tmp_data_29_V_reg_2145;
wire   [19:0] tmp_data_30_V_fu_1984_p3;
reg   [19:0] tmp_data_30_V_reg_2150;
wire   [19:0] tmp_data_31_V_fu_1992_p3;
reg   [19:0] tmp_data_31_V_reg_2155;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln1494_fu_1232_p2;
wire   [19:0] trunc_ln_fu_1238_p4;
wire   [0:0] icmp_ln1494_1_fu_1248_p2;
wire   [19:0] trunc_ln708_1_fu_1254_p4;
wire   [0:0] icmp_ln1494_2_fu_1264_p2;
wire   [19:0] trunc_ln708_2_fu_1270_p4;
wire   [0:0] icmp_ln1494_3_fu_1280_p2;
wire   [19:0] trunc_ln708_3_fu_1286_p4;
wire   [0:0] icmp_ln1494_4_fu_1296_p2;
wire   [19:0] trunc_ln708_4_fu_1302_p4;
wire   [0:0] icmp_ln1494_5_fu_1312_p2;
wire   [19:0] trunc_ln708_5_fu_1318_p4;
wire   [0:0] icmp_ln1494_6_fu_1328_p2;
wire   [19:0] trunc_ln708_6_fu_1334_p4;
wire   [0:0] icmp_ln1494_7_fu_1344_p2;
wire   [19:0] trunc_ln708_7_fu_1350_p4;
wire   [0:0] icmp_ln1494_8_fu_1360_p2;
wire   [19:0] trunc_ln708_8_fu_1366_p4;
wire   [0:0] icmp_ln1494_9_fu_1376_p2;
wire   [19:0] trunc_ln708_9_fu_1382_p4;
wire   [0:0] icmp_ln1494_10_fu_1392_p2;
wire   [19:0] trunc_ln708_s_fu_1398_p4;
wire   [0:0] icmp_ln1494_11_fu_1408_p2;
wire   [19:0] trunc_ln708_10_fu_1414_p4;
wire   [0:0] icmp_ln1494_12_fu_1424_p2;
wire   [19:0] trunc_ln708_11_fu_1430_p4;
wire   [0:0] icmp_ln1494_13_fu_1440_p2;
wire   [19:0] trunc_ln708_12_fu_1446_p4;
wire   [0:0] icmp_ln1494_14_fu_1456_p2;
wire   [19:0] trunc_ln708_13_fu_1462_p4;
wire   [0:0] icmp_ln1494_15_fu_1472_p2;
wire   [19:0] trunc_ln708_14_fu_1478_p4;
wire   [0:0] icmp_ln1494_16_fu_1488_p2;
wire   [19:0] trunc_ln708_15_fu_1494_p4;
wire   [0:0] icmp_ln1494_17_fu_1504_p2;
wire   [19:0] trunc_ln708_16_fu_1510_p4;
wire   [0:0] icmp_ln1494_18_fu_1520_p2;
wire   [19:0] trunc_ln708_17_fu_1526_p4;
wire   [0:0] icmp_ln1494_19_fu_1536_p2;
wire   [19:0] trunc_ln708_18_fu_1542_p4;
wire   [0:0] icmp_ln1494_20_fu_1552_p2;
wire   [19:0] trunc_ln708_19_fu_1558_p4;
wire   [0:0] icmp_ln1494_21_fu_1568_p2;
wire   [19:0] trunc_ln708_20_fu_1574_p4;
wire   [0:0] icmp_ln1494_22_fu_1584_p2;
wire   [19:0] trunc_ln708_21_fu_1590_p4;
wire   [0:0] icmp_ln1494_23_fu_1600_p2;
wire   [19:0] trunc_ln708_22_fu_1606_p4;
wire   [0:0] icmp_ln1494_24_fu_1616_p2;
wire   [19:0] trunc_ln708_23_fu_1622_p4;
wire   [0:0] icmp_ln1494_25_fu_1632_p2;
wire   [19:0] trunc_ln708_24_fu_1638_p4;
wire   [0:0] icmp_ln1494_26_fu_1648_p2;
wire   [19:0] trunc_ln708_25_fu_1654_p4;
wire   [0:0] icmp_ln1494_27_fu_1664_p2;
wire   [19:0] trunc_ln708_26_fu_1670_p4;
wire   [0:0] icmp_ln1494_28_fu_1680_p2;
wire   [19:0] trunc_ln708_27_fu_1686_p4;
wire   [0:0] icmp_ln1494_29_fu_1696_p2;
wire   [19:0] trunc_ln708_28_fu_1702_p4;
wire   [0:0] icmp_ln1494_30_fu_1712_p2;
wire   [19:0] trunc_ln708_29_fu_1718_p4;
wire   [0:0] icmp_ln1494_31_fu_1728_p2;
wire   [19:0] trunc_ln708_30_fu_1734_p4;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= real_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_data_0_V_reg_2000 <= tmp_data_0_V_fu_1744_p3;
        tmp_data_10_V_reg_2050 <= tmp_data_10_V_fu_1824_p3;
        tmp_data_11_V_reg_2055 <= tmp_data_11_V_fu_1832_p3;
        tmp_data_12_V_reg_2060 <= tmp_data_12_V_fu_1840_p3;
        tmp_data_13_V_reg_2065 <= tmp_data_13_V_fu_1848_p3;
        tmp_data_14_V_reg_2070 <= tmp_data_14_V_fu_1856_p3;
        tmp_data_15_V_reg_2075 <= tmp_data_15_V_fu_1864_p3;
        tmp_data_16_V_reg_2080 <= tmp_data_16_V_fu_1872_p3;
        tmp_data_17_V_reg_2085 <= tmp_data_17_V_fu_1880_p3;
        tmp_data_18_V_reg_2090 <= tmp_data_18_V_fu_1888_p3;
        tmp_data_19_V_reg_2095 <= tmp_data_19_V_fu_1896_p3;
        tmp_data_1_V_reg_2005 <= tmp_data_1_V_fu_1752_p3;
        tmp_data_20_V_reg_2100 <= tmp_data_20_V_fu_1904_p3;
        tmp_data_21_V_reg_2105 <= tmp_data_21_V_fu_1912_p3;
        tmp_data_22_V_reg_2110 <= tmp_data_22_V_fu_1920_p3;
        tmp_data_23_V_reg_2115 <= tmp_data_23_V_fu_1928_p3;
        tmp_data_24_V_reg_2120 <= tmp_data_24_V_fu_1936_p3;
        tmp_data_25_V_reg_2125 <= tmp_data_25_V_fu_1944_p3;
        tmp_data_26_V_reg_2130 <= tmp_data_26_V_fu_1952_p3;
        tmp_data_27_V_reg_2135 <= tmp_data_27_V_fu_1960_p3;
        tmp_data_28_V_reg_2140 <= tmp_data_28_V_fu_1968_p3;
        tmp_data_29_V_reg_2145 <= tmp_data_29_V_fu_1976_p3;
        tmp_data_2_V_reg_2010 <= tmp_data_2_V_fu_1760_p3;
        tmp_data_30_V_reg_2150 <= tmp_data_30_V_fu_1984_p3;
        tmp_data_31_V_reg_2155 <= tmp_data_31_V_fu_1992_p3;
        tmp_data_3_V_reg_2015 <= tmp_data_3_V_fu_1768_p3;
        tmp_data_4_V_reg_2020 <= tmp_data_4_V_fu_1776_p3;
        tmp_data_5_V_reg_2025 <= tmp_data_5_V_fu_1784_p3;
        tmp_data_6_V_reg_2030 <= tmp_data_6_V_fu_1792_p3;
        tmp_data_7_V_reg_2035 <= tmp_data_7_V_fu_1800_p3;
        tmp_data_8_V_reg_2040 <= tmp_data_8_V_fu_1808_p3;
        tmp_data_9_V_reg_2045 <= tmp_data_9_V_fu_1816_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_0_V_read = 1'b1;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_10_V_blk_n = data_V_data_10_V_empty_n;
    end else begin
        data_V_data_10_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_10_V_read = 1'b1;
    end else begin
        data_V_data_10_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_11_V_blk_n = data_V_data_11_V_empty_n;
    end else begin
        data_V_data_11_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_11_V_read = 1'b1;
    end else begin
        data_V_data_11_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_12_V_blk_n = data_V_data_12_V_empty_n;
    end else begin
        data_V_data_12_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_12_V_read = 1'b1;
    end else begin
        data_V_data_12_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_13_V_blk_n = data_V_data_13_V_empty_n;
    end else begin
        data_V_data_13_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_13_V_read = 1'b1;
    end else begin
        data_V_data_13_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_14_V_blk_n = data_V_data_14_V_empty_n;
    end else begin
        data_V_data_14_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_14_V_read = 1'b1;
    end else begin
        data_V_data_14_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_15_V_blk_n = data_V_data_15_V_empty_n;
    end else begin
        data_V_data_15_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_15_V_read = 1'b1;
    end else begin
        data_V_data_15_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_16_V_blk_n = data_V_data_16_V_empty_n;
    end else begin
        data_V_data_16_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_16_V_read = 1'b1;
    end else begin
        data_V_data_16_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_17_V_blk_n = data_V_data_17_V_empty_n;
    end else begin
        data_V_data_17_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_17_V_read = 1'b1;
    end else begin
        data_V_data_17_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_18_V_blk_n = data_V_data_18_V_empty_n;
    end else begin
        data_V_data_18_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_18_V_read = 1'b1;
    end else begin
        data_V_data_18_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_19_V_blk_n = data_V_data_19_V_empty_n;
    end else begin
        data_V_data_19_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_19_V_read = 1'b1;
    end else begin
        data_V_data_19_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_1_V_read = 1'b1;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_20_V_blk_n = data_V_data_20_V_empty_n;
    end else begin
        data_V_data_20_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_20_V_read = 1'b1;
    end else begin
        data_V_data_20_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_21_V_blk_n = data_V_data_21_V_empty_n;
    end else begin
        data_V_data_21_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_21_V_read = 1'b1;
    end else begin
        data_V_data_21_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_22_V_blk_n = data_V_data_22_V_empty_n;
    end else begin
        data_V_data_22_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_22_V_read = 1'b1;
    end else begin
        data_V_data_22_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_23_V_blk_n = data_V_data_23_V_empty_n;
    end else begin
        data_V_data_23_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_23_V_read = 1'b1;
    end else begin
        data_V_data_23_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_24_V_blk_n = data_V_data_24_V_empty_n;
    end else begin
        data_V_data_24_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_24_V_read = 1'b1;
    end else begin
        data_V_data_24_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_25_V_blk_n = data_V_data_25_V_empty_n;
    end else begin
        data_V_data_25_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_25_V_read = 1'b1;
    end else begin
        data_V_data_25_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_26_V_blk_n = data_V_data_26_V_empty_n;
    end else begin
        data_V_data_26_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_26_V_read = 1'b1;
    end else begin
        data_V_data_26_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_27_V_blk_n = data_V_data_27_V_empty_n;
    end else begin
        data_V_data_27_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_27_V_read = 1'b1;
    end else begin
        data_V_data_27_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_28_V_blk_n = data_V_data_28_V_empty_n;
    end else begin
        data_V_data_28_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_28_V_read = 1'b1;
    end else begin
        data_V_data_28_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_29_V_blk_n = data_V_data_29_V_empty_n;
    end else begin
        data_V_data_29_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_29_V_read = 1'b1;
    end else begin
        data_V_data_29_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_2_V_read = 1'b1;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_30_V_blk_n = data_V_data_30_V_empty_n;
    end else begin
        data_V_data_30_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_30_V_read = 1'b1;
    end else begin
        data_V_data_30_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_31_V_blk_n = data_V_data_31_V_empty_n;
    end else begin
        data_V_data_31_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_31_V_read = 1'b1;
    end else begin
        data_V_data_31_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_3_V_read = 1'b1;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_4_V_blk_n = data_V_data_4_V_empty_n;
    end else begin
        data_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_4_V_read = 1'b1;
    end else begin
        data_V_data_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_5_V_blk_n = data_V_data_5_V_empty_n;
    end else begin
        data_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_5_V_read = 1'b1;
    end else begin
        data_V_data_5_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_6_V_blk_n = data_V_data_6_V_empty_n;
    end else begin
        data_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_6_V_read = 1'b1;
    end else begin
        data_V_data_6_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_7_V_blk_n = data_V_data_7_V_empty_n;
    end else begin
        data_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_7_V_read = 1'b1;
    end else begin
        data_V_data_7_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_8_V_blk_n = data_V_data_8_V_empty_n;
    end else begin
        data_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_8_V_read = 1'b1;
    end else begin
        data_V_data_8_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_9_V_blk_n = data_V_data_9_V_empty_n;
    end else begin
        data_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_9_V_read = 1'b1;
    end else begin
        data_V_data_9_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (real_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_10_V_blk_n = res_V_data_10_V_full_n;
    end else begin
        res_V_data_10_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_10_V_write = 1'b1;
    end else begin
        res_V_data_10_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_11_V_blk_n = res_V_data_11_V_full_n;
    end else begin
        res_V_data_11_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_11_V_write = 1'b1;
    end else begin
        res_V_data_11_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_12_V_blk_n = res_V_data_12_V_full_n;
    end else begin
        res_V_data_12_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_12_V_write = 1'b1;
    end else begin
        res_V_data_12_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_13_V_blk_n = res_V_data_13_V_full_n;
    end else begin
        res_V_data_13_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_13_V_write = 1'b1;
    end else begin
        res_V_data_13_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_14_V_blk_n = res_V_data_14_V_full_n;
    end else begin
        res_V_data_14_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_14_V_write = 1'b1;
    end else begin
        res_V_data_14_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_15_V_blk_n = res_V_data_15_V_full_n;
    end else begin
        res_V_data_15_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_15_V_write = 1'b1;
    end else begin
        res_V_data_15_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_16_V_blk_n = res_V_data_16_V_full_n;
    end else begin
        res_V_data_16_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_16_V_write = 1'b1;
    end else begin
        res_V_data_16_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_17_V_blk_n = res_V_data_17_V_full_n;
    end else begin
        res_V_data_17_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_17_V_write = 1'b1;
    end else begin
        res_V_data_17_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_18_V_blk_n = res_V_data_18_V_full_n;
    end else begin
        res_V_data_18_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_18_V_write = 1'b1;
    end else begin
        res_V_data_18_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_19_V_blk_n = res_V_data_19_V_full_n;
    end else begin
        res_V_data_19_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_19_V_write = 1'b1;
    end else begin
        res_V_data_19_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_20_V_blk_n = res_V_data_20_V_full_n;
    end else begin
        res_V_data_20_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_20_V_write = 1'b1;
    end else begin
        res_V_data_20_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_21_V_blk_n = res_V_data_21_V_full_n;
    end else begin
        res_V_data_21_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_21_V_write = 1'b1;
    end else begin
        res_V_data_21_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_22_V_blk_n = res_V_data_22_V_full_n;
    end else begin
        res_V_data_22_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_22_V_write = 1'b1;
    end else begin
        res_V_data_22_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_23_V_blk_n = res_V_data_23_V_full_n;
    end else begin
        res_V_data_23_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_23_V_write = 1'b1;
    end else begin
        res_V_data_23_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_24_V_blk_n = res_V_data_24_V_full_n;
    end else begin
        res_V_data_24_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_24_V_write = 1'b1;
    end else begin
        res_V_data_24_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_25_V_blk_n = res_V_data_25_V_full_n;
    end else begin
        res_V_data_25_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_25_V_write = 1'b1;
    end else begin
        res_V_data_25_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_26_V_blk_n = res_V_data_26_V_full_n;
    end else begin
        res_V_data_26_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_26_V_write = 1'b1;
    end else begin
        res_V_data_26_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_27_V_blk_n = res_V_data_27_V_full_n;
    end else begin
        res_V_data_27_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_27_V_write = 1'b1;
    end else begin
        res_V_data_27_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_28_V_blk_n = res_V_data_28_V_full_n;
    end else begin
        res_V_data_28_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_28_V_write = 1'b1;
    end else begin
        res_V_data_28_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_29_V_blk_n = res_V_data_29_V_full_n;
    end else begin
        res_V_data_29_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_29_V_write = 1'b1;
    end else begin
        res_V_data_29_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_30_V_blk_n = res_V_data_30_V_full_n;
    end else begin
        res_V_data_30_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_30_V_write = 1'b1;
    end else begin
        res_V_data_30_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_31_V_blk_n = res_V_data_31_V_full_n;
    end else begin
        res_V_data_31_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_31_V_write = 1'b1;
    end else begin
        res_V_data_31_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n;
    end else begin
        res_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_4_V_write = 1'b1;
    end else begin
        res_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n;
    end else begin
        res_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_5_V_write = 1'b1;
    end else begin
        res_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n;
    end else begin
        res_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_6_V_write = 1'b1;
    end else begin
        res_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n;
    end else begin
        res_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_7_V_write = 1'b1;
    end else begin
        res_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_8_V_blk_n = res_V_data_8_V_full_n;
    end else begin
        res_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_8_V_write = 1'b1;
    end else begin
        res_V_data_8_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_9_V_blk_n = res_V_data_9_V_full_n;
    end else begin
        res_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        res_V_data_9_V_write = 1'b1;
    end else begin
        res_V_data_9_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((real_start == 1'b1) & ((real_start == 1'b0) | (io_acc_block_signal_op3 == 1'b0) | (ap_done_reg == 1'b1))) | ((io_acc_block_signal_op199 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((real_start == 1'b1) & ((real_start == 1'b0) | (io_acc_block_signal_op3 == 1'b0) | (ap_done_reg == 1'b1))) | ((io_acc_block_signal_op199 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((real_start == 1'b1) & ((real_start == 1'b0) | (io_acc_block_signal_op3 == 1'b0) | (ap_done_reg == 1'b1))) | ((io_acc_block_signal_op199 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((real_start == 1'b0) | (io_acc_block_signal_op3 == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (io_acc_block_signal_op199 == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = real_start;

assign ap_ready = internal_ap_ready;

assign icmp_ln1494_10_fu_1392_p2 = (($signed(data_V_data_10_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_1408_p2 = (($signed(data_V_data_11_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_1424_p2 = (($signed(data_V_data_12_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_1440_p2 = (($signed(data_V_data_13_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_1456_p2 = (($signed(data_V_data_14_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_1472_p2 = (($signed(data_V_data_15_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_1488_p2 = (($signed(data_V_data_16_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_1504_p2 = (($signed(data_V_data_17_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_1520_p2 = (($signed(data_V_data_18_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_19_fu_1536_p2 = (($signed(data_V_data_19_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_1248_p2 = (($signed(data_V_data_1_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_20_fu_1552_p2 = (($signed(data_V_data_20_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_21_fu_1568_p2 = (($signed(data_V_data_21_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_22_fu_1584_p2 = (($signed(data_V_data_22_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_23_fu_1600_p2 = (($signed(data_V_data_23_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_24_fu_1616_p2 = (($signed(data_V_data_24_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_25_fu_1632_p2 = (($signed(data_V_data_25_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_26_fu_1648_p2 = (($signed(data_V_data_26_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_27_fu_1664_p2 = (($signed(data_V_data_27_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_28_fu_1680_p2 = (($signed(data_V_data_28_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_29_fu_1696_p2 = (($signed(data_V_data_29_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_1264_p2 = (($signed(data_V_data_2_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_30_fu_1712_p2 = (($signed(data_V_data_30_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_31_fu_1728_p2 = (($signed(data_V_data_31_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_1280_p2 = (($signed(data_V_data_3_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_1296_p2 = (($signed(data_V_data_4_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_1312_p2 = (($signed(data_V_data_5_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_1328_p2 = (($signed(data_V_data_6_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_1344_p2 = (($signed(data_V_data_7_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_1360_p2 = (($signed(data_V_data_8_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_1376_p2 = (($signed(data_V_data_9_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_1232_p2 = (($signed(data_V_data_0_V_dout) > $signed(53'd0)) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op199 = (res_V_data_9_V_full_n & res_V_data_8_V_full_n & res_V_data_7_V_full_n & res_V_data_6_V_full_n & res_V_data_5_V_full_n & res_V_data_4_V_full_n & res_V_data_3_V_full_n & res_V_data_31_V_full_n & res_V_data_30_V_full_n & res_V_data_2_V_full_n & res_V_data_29_V_full_n & res_V_data_28_V_full_n & res_V_data_27_V_full_n & res_V_data_26_V_full_n & res_V_data_25_V_full_n & res_V_data_24_V_full_n & res_V_data_23_V_full_n & res_V_data_22_V_full_n & res_V_data_21_V_full_n & res_V_data_20_V_full_n & res_V_data_1_V_full_n & res_V_data_19_V_full_n & res_V_data_18_V_full_n & res_V_data_17_V_full_n & res_V_data_16_V_full_n & res_V_data_15_V_full_n & res_V_data_14_V_full_n & res_V_data_13_V_full_n & res_V_data_12_V_full_n & res_V_data_11_V_full_n & res_V_data_10_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op3 = (data_V_data_9_V_empty_n & data_V_data_8_V_empty_n & data_V_data_7_V_empty_n & data_V_data_6_V_empty_n & data_V_data_5_V_empty_n & data_V_data_4_V_empty_n & data_V_data_3_V_empty_n & data_V_data_31_V_empty_n & data_V_data_30_V_empty_n & data_V_data_2_V_empty_n & data_V_data_29_V_empty_n & data_V_data_28_V_empty_n & data_V_data_27_V_empty_n & data_V_data_26_V_empty_n & data_V_data_25_V_empty_n & data_V_data_24_V_empty_n & data_V_data_23_V_empty_n & data_V_data_22_V_empty_n & data_V_data_21_V_empty_n & data_V_data_20_V_empty_n & data_V_data_1_V_empty_n & data_V_data_19_V_empty_n & data_V_data_18_V_empty_n & data_V_data_17_V_empty_n & data_V_data_16_V_empty_n & data_V_data_15_V_empty_n & data_V_data_14_V_empty_n & data_V_data_13_V_empty_n & data_V_data_12_V_empty_n & data_V_data_11_V_empty_n & data_V_data_10_V_empty_n & data_V_data_0_V_empty_n);

assign res_V_data_0_V_din = tmp_data_0_V_reg_2000;

assign res_V_data_10_V_din = tmp_data_10_V_reg_2050;

assign res_V_data_11_V_din = tmp_data_11_V_reg_2055;

assign res_V_data_12_V_din = tmp_data_12_V_reg_2060;

assign res_V_data_13_V_din = tmp_data_13_V_reg_2065;

assign res_V_data_14_V_din = tmp_data_14_V_reg_2070;

assign res_V_data_15_V_din = tmp_data_15_V_reg_2075;

assign res_V_data_16_V_din = tmp_data_16_V_reg_2080;

assign res_V_data_17_V_din = tmp_data_17_V_reg_2085;

assign res_V_data_18_V_din = tmp_data_18_V_reg_2090;

assign res_V_data_19_V_din = tmp_data_19_V_reg_2095;

assign res_V_data_1_V_din = tmp_data_1_V_reg_2005;

assign res_V_data_20_V_din = tmp_data_20_V_reg_2100;

assign res_V_data_21_V_din = tmp_data_21_V_reg_2105;

assign res_V_data_22_V_din = tmp_data_22_V_reg_2110;

assign res_V_data_23_V_din = tmp_data_23_V_reg_2115;

assign res_V_data_24_V_din = tmp_data_24_V_reg_2120;

assign res_V_data_25_V_din = tmp_data_25_V_reg_2125;

assign res_V_data_26_V_din = tmp_data_26_V_reg_2130;

assign res_V_data_27_V_din = tmp_data_27_V_reg_2135;

assign res_V_data_28_V_din = tmp_data_28_V_reg_2140;

assign res_V_data_29_V_din = tmp_data_29_V_reg_2145;

assign res_V_data_2_V_din = tmp_data_2_V_reg_2010;

assign res_V_data_30_V_din = tmp_data_30_V_reg_2150;

assign res_V_data_31_V_din = tmp_data_31_V_reg_2155;

assign res_V_data_3_V_din = tmp_data_3_V_reg_2015;

assign res_V_data_4_V_din = tmp_data_4_V_reg_2020;

assign res_V_data_5_V_din = tmp_data_5_V_reg_2025;

assign res_V_data_6_V_din = tmp_data_6_V_reg_2030;

assign res_V_data_7_V_din = tmp_data_7_V_reg_2035;

assign res_V_data_8_V_din = tmp_data_8_V_reg_2040;

assign res_V_data_9_V_din = tmp_data_9_V_reg_2045;

assign start_out = real_start;

assign tmp_data_0_V_fu_1744_p3 = ((icmp_ln1494_fu_1232_p2[0:0] === 1'b1) ? trunc_ln_fu_1238_p4 : 20'd0);

assign tmp_data_10_V_fu_1824_p3 = ((icmp_ln1494_10_fu_1392_p2[0:0] === 1'b1) ? trunc_ln708_s_fu_1398_p4 : 20'd0);

assign tmp_data_11_V_fu_1832_p3 = ((icmp_ln1494_11_fu_1408_p2[0:0] === 1'b1) ? trunc_ln708_10_fu_1414_p4 : 20'd0);

assign tmp_data_12_V_fu_1840_p3 = ((icmp_ln1494_12_fu_1424_p2[0:0] === 1'b1) ? trunc_ln708_11_fu_1430_p4 : 20'd0);

assign tmp_data_13_V_fu_1848_p3 = ((icmp_ln1494_13_fu_1440_p2[0:0] === 1'b1) ? trunc_ln708_12_fu_1446_p4 : 20'd0);

assign tmp_data_14_V_fu_1856_p3 = ((icmp_ln1494_14_fu_1456_p2[0:0] === 1'b1) ? trunc_ln708_13_fu_1462_p4 : 20'd0);

assign tmp_data_15_V_fu_1864_p3 = ((icmp_ln1494_15_fu_1472_p2[0:0] === 1'b1) ? trunc_ln708_14_fu_1478_p4 : 20'd0);

assign tmp_data_16_V_fu_1872_p3 = ((icmp_ln1494_16_fu_1488_p2[0:0] === 1'b1) ? trunc_ln708_15_fu_1494_p4 : 20'd0);

assign tmp_data_17_V_fu_1880_p3 = ((icmp_ln1494_17_fu_1504_p2[0:0] === 1'b1) ? trunc_ln708_16_fu_1510_p4 : 20'd0);

assign tmp_data_18_V_fu_1888_p3 = ((icmp_ln1494_18_fu_1520_p2[0:0] === 1'b1) ? trunc_ln708_17_fu_1526_p4 : 20'd0);

assign tmp_data_19_V_fu_1896_p3 = ((icmp_ln1494_19_fu_1536_p2[0:0] === 1'b1) ? trunc_ln708_18_fu_1542_p4 : 20'd0);

assign tmp_data_1_V_fu_1752_p3 = ((icmp_ln1494_1_fu_1248_p2[0:0] === 1'b1) ? trunc_ln708_1_fu_1254_p4 : 20'd0);

assign tmp_data_20_V_fu_1904_p3 = ((icmp_ln1494_20_fu_1552_p2[0:0] === 1'b1) ? trunc_ln708_19_fu_1558_p4 : 20'd0);

assign tmp_data_21_V_fu_1912_p3 = ((icmp_ln1494_21_fu_1568_p2[0:0] === 1'b1) ? trunc_ln708_20_fu_1574_p4 : 20'd0);

assign tmp_data_22_V_fu_1920_p3 = ((icmp_ln1494_22_fu_1584_p2[0:0] === 1'b1) ? trunc_ln708_21_fu_1590_p4 : 20'd0);

assign tmp_data_23_V_fu_1928_p3 = ((icmp_ln1494_23_fu_1600_p2[0:0] === 1'b1) ? trunc_ln708_22_fu_1606_p4 : 20'd0);

assign tmp_data_24_V_fu_1936_p3 = ((icmp_ln1494_24_fu_1616_p2[0:0] === 1'b1) ? trunc_ln708_23_fu_1622_p4 : 20'd0);

assign tmp_data_25_V_fu_1944_p3 = ((icmp_ln1494_25_fu_1632_p2[0:0] === 1'b1) ? trunc_ln708_24_fu_1638_p4 : 20'd0);

assign tmp_data_26_V_fu_1952_p3 = ((icmp_ln1494_26_fu_1648_p2[0:0] === 1'b1) ? trunc_ln708_25_fu_1654_p4 : 20'd0);

assign tmp_data_27_V_fu_1960_p3 = ((icmp_ln1494_27_fu_1664_p2[0:0] === 1'b1) ? trunc_ln708_26_fu_1670_p4 : 20'd0);

assign tmp_data_28_V_fu_1968_p3 = ((icmp_ln1494_28_fu_1680_p2[0:0] === 1'b1) ? trunc_ln708_27_fu_1686_p4 : 20'd0);

assign tmp_data_29_V_fu_1976_p3 = ((icmp_ln1494_29_fu_1696_p2[0:0] === 1'b1) ? trunc_ln708_28_fu_1702_p4 : 20'd0);

assign tmp_data_2_V_fu_1760_p3 = ((icmp_ln1494_2_fu_1264_p2[0:0] === 1'b1) ? trunc_ln708_2_fu_1270_p4 : 20'd0);

assign tmp_data_30_V_fu_1984_p3 = ((icmp_ln1494_30_fu_1712_p2[0:0] === 1'b1) ? trunc_ln708_29_fu_1718_p4 : 20'd0);

assign tmp_data_31_V_fu_1992_p3 = ((icmp_ln1494_31_fu_1728_p2[0:0] === 1'b1) ? trunc_ln708_30_fu_1734_p4 : 20'd0);

assign tmp_data_3_V_fu_1768_p3 = ((icmp_ln1494_3_fu_1280_p2[0:0] === 1'b1) ? trunc_ln708_3_fu_1286_p4 : 20'd0);

assign tmp_data_4_V_fu_1776_p3 = ((icmp_ln1494_4_fu_1296_p2[0:0] === 1'b1) ? trunc_ln708_4_fu_1302_p4 : 20'd0);

assign tmp_data_5_V_fu_1784_p3 = ((icmp_ln1494_5_fu_1312_p2[0:0] === 1'b1) ? trunc_ln708_5_fu_1318_p4 : 20'd0);

assign tmp_data_6_V_fu_1792_p3 = ((icmp_ln1494_6_fu_1328_p2[0:0] === 1'b1) ? trunc_ln708_6_fu_1334_p4 : 20'd0);

assign tmp_data_7_V_fu_1800_p3 = ((icmp_ln1494_7_fu_1344_p2[0:0] === 1'b1) ? trunc_ln708_7_fu_1350_p4 : 20'd0);

assign tmp_data_8_V_fu_1808_p3 = ((icmp_ln1494_8_fu_1360_p2[0:0] === 1'b1) ? trunc_ln708_8_fu_1366_p4 : 20'd0);

assign tmp_data_9_V_fu_1816_p3 = ((icmp_ln1494_9_fu_1376_p2[0:0] === 1'b1) ? trunc_ln708_9_fu_1382_p4 : 20'd0);

assign trunc_ln708_10_fu_1414_p4 = {{data_V_data_11_V_dout[29:10]}};

assign trunc_ln708_11_fu_1430_p4 = {{data_V_data_12_V_dout[29:10]}};

assign trunc_ln708_12_fu_1446_p4 = {{data_V_data_13_V_dout[29:10]}};

assign trunc_ln708_13_fu_1462_p4 = {{data_V_data_14_V_dout[29:10]}};

assign trunc_ln708_14_fu_1478_p4 = {{data_V_data_15_V_dout[29:10]}};

assign trunc_ln708_15_fu_1494_p4 = {{data_V_data_16_V_dout[29:10]}};

assign trunc_ln708_16_fu_1510_p4 = {{data_V_data_17_V_dout[29:10]}};

assign trunc_ln708_17_fu_1526_p4 = {{data_V_data_18_V_dout[29:10]}};

assign trunc_ln708_18_fu_1542_p4 = {{data_V_data_19_V_dout[29:10]}};

assign trunc_ln708_19_fu_1558_p4 = {{data_V_data_20_V_dout[29:10]}};

assign trunc_ln708_1_fu_1254_p4 = {{data_V_data_1_V_dout[29:10]}};

assign trunc_ln708_20_fu_1574_p4 = {{data_V_data_21_V_dout[29:10]}};

assign trunc_ln708_21_fu_1590_p4 = {{data_V_data_22_V_dout[29:10]}};

assign trunc_ln708_22_fu_1606_p4 = {{data_V_data_23_V_dout[29:10]}};

assign trunc_ln708_23_fu_1622_p4 = {{data_V_data_24_V_dout[29:10]}};

assign trunc_ln708_24_fu_1638_p4 = {{data_V_data_25_V_dout[29:10]}};

assign trunc_ln708_25_fu_1654_p4 = {{data_V_data_26_V_dout[29:10]}};

assign trunc_ln708_26_fu_1670_p4 = {{data_V_data_27_V_dout[29:10]}};

assign trunc_ln708_27_fu_1686_p4 = {{data_V_data_28_V_dout[29:10]}};

assign trunc_ln708_28_fu_1702_p4 = {{data_V_data_29_V_dout[29:10]}};

assign trunc_ln708_29_fu_1718_p4 = {{data_V_data_30_V_dout[29:10]}};

assign trunc_ln708_2_fu_1270_p4 = {{data_V_data_2_V_dout[29:10]}};

assign trunc_ln708_30_fu_1734_p4 = {{data_V_data_31_V_dout[29:10]}};

assign trunc_ln708_3_fu_1286_p4 = {{data_V_data_3_V_dout[29:10]}};

assign trunc_ln708_4_fu_1302_p4 = {{data_V_data_4_V_dout[29:10]}};

assign trunc_ln708_5_fu_1318_p4 = {{data_V_data_5_V_dout[29:10]}};

assign trunc_ln708_6_fu_1334_p4 = {{data_V_data_6_V_dout[29:10]}};

assign trunc_ln708_7_fu_1350_p4 = {{data_V_data_7_V_dout[29:10]}};

assign trunc_ln708_8_fu_1366_p4 = {{data_V_data_8_V_dout[29:10]}};

assign trunc_ln708_9_fu_1382_p4 = {{data_V_data_9_V_dout[29:10]}};

assign trunc_ln708_s_fu_1398_p4 = {{data_V_data_10_V_dout[29:10]}};

assign trunc_ln_fu_1238_p4 = {{data_V_data_0_V_dout[29:10]}};

endmodule //relu_array_ap_fixed_32u_array_ap_fixed_20_10_5_3_0_32u_relu_config6_s
