Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 30
    Strategy: Resource
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'hls/quickdraw_gru_hls4ml_prj/keras_model.h5'
OutputDir: hls/quickdraw_gru_hls4ml_prj
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: eF961c7e
Version: 1.0.0
