onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /LSTM_tb/dut/WIDTH
add wave -noupdate /LSTM_tb/dut/NINT
add wave -noupdate /LSTM_tb/dut/INPUT_SIZE
add wave -noupdate /LSTM_tb/dut/TIMESTEPS
add wave -noupdate /LSTM_tb/dut/OUTPUT_SIZE
add wave -noupdate /LSTM_tb/dut/OUTPUT_EACH_HT
add wave -noupdate /LSTM_tb/dut/PIPELINING
add wave -noupdate /LSTM_tb/dut/IMPLEMENTATION
add wave -noupdate /LSTM_tb/dut/PIPE_OUT
add wave -noupdate /LSTM_tb/dut/REMOVE_PIPELINES
add wave -noupdate /LSTM_tb/dut/NFRAC
add wave -noupdate /LSTM_tb/dut/SIGMOID_BRAM_FILE
add wave -noupdate /LSTM_tb/dut/TANH_BRAM_FILE
add wave -noupdate /LSTM_tb/dut/clk
add wave -noupdate /LSTM_tb/dut/reset
add wave -noupdate /LSTM_tb/dut/input_ready
add wave -noupdate /LSTM_tb/dut/output_ready
add wave -noupdate /LSTM_tb/dut/ready
add wave -noupdate /LSTM_tb/dut/next_layer_ready
add wave -noupdate /LSTM_tb/dut/input_v
add wave -noupdate /LSTM_tb/dut/ht
add wave -noupdate /LSTM_tb/dut/ready_for_output
add wave -noupdate /LSTM_tb/dut/processing
add wave -noupdate /LSTM_tb/dut/move_next
add wave -noupdate /LSTM_tb/dut/ct_1
add wave -noupdate /LSTM_tb/dut/ct
add wave -noupdate /LSTM_tb/dut/dense_inputx_ready
add wave -noupdate /LSTM_tb/dut/dense_outputx_ready
add wave -noupdate /LSTM_tb/dut/dense_inputx
add wave -noupdate /LSTM_tb/dut/dense_outputx
add wave -noupdate /LSTM_tb/dut/sig_output_ready1
add wave -noupdate /LSTM_tb/dut/sig_output_ready2
add wave -noupdate /LSTM_tb/dut/sig_output_ready3
add wave -noupdate /LSTM_tb/dut/sigmoid_ready
add wave -noupdate /LSTM_tb/dut/tanh_ready
add wave -noupdate /LSTM_tb/dut/tanh_output_ready
add wave -noupdate /LSTM_tb/dut/dense_inputh_ready
add wave -noupdate /LSTM_tb/dut/dense_outputh_ready
add wave -noupdate /LSTM_tb/dut/dense_inputh
add wave -noupdate /LSTM_tb/dut/dense_outputh
add wave -noupdate /LSTM_tb/dut/curr_step
add wave -noupdate /LSTM_tb/dut/xt
add wave -noupdate /LSTM_tb/dut/reset_cell
add wave -noupdate /LSTM_tb/dut/next_ready
add wave -noupdate /LSTM_tb/dut/which_tanh
add wave -noupdate /LSTM_tb/dut/edge_trig
add wave -noupdate /LSTM_tb/dut/lstm_reset
add wave -noupdate /LSTM_tb/dut/move_next_1
add wave -noupdate /LSTM_tb/dut/paused
add wave -noupdate /LSTM_tb/dut/state
add wave -noupdate /LSTM_tb/dut/next_state
add wave -noupdate /LSTM_tb/dut/ct_next
add wave -noupdate /LSTM_tb/dut/ct_tanh
add wave -noupdate /LSTM_tb/dut/ct_result_ready
add wave -noupdate /LSTM_tb/dut/next_output_ready
add wave -noupdate /LSTM_tb/dut/start_processing
add wave -noupdate /LSTM_tb/dut/future_reset_cell
add wave -noupdate /LSTM_tb/dut/densex_ready
add wave -noupdate /LSTM_tb/dut/denseh_ready
add wave -noupdate /LSTM_tb/dut/combined
add wave -noupdate /LSTM_tb/dut/ft_a
add wave -noupdate /LSTM_tb/dut/it_a
add wave -noupdate /LSTM_tb/dut/c_t_a
add wave -noupdate /LSTM_tb/dut/ot_a
add wave -noupdate /LSTM_tb/dut/tanh_input
add wave -noupdate /LSTM_tb/dut/tanh_output
add wave -noupdate /LSTM_tb/dut/ft
add wave -noupdate /LSTM_tb/dut/it
add wave -noupdate /LSTM_tb/dut/c_t
add wave -noupdate /LSTM_tb/dut/ot
add wave -noupdate /LSTM_tb/dut/tanh_input_ready
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1650059 ps} 0} {{Cursor 2} {38273 ps} 0}
quietly wave cursor active 2
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {65912 ps}
