// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module linear_array_array_ap_fixed_16_6_5_3_0_5u_linear_config22_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        data_V_data_4_V_dout,
        data_V_data_4_V_empty_n,
        data_V_data_4_V_read,
        res_V_data_0_V_TREADY,
        res_V_data_0_V_TDATA,
        res_V_data_0_V_TVALID,
        res_V_data_1_V_TDATA,
        res_V_data_1_V_TVALID,
        res_V_data_1_V_TREADY,
        res_V_data_2_V_TDATA,
        res_V_data_2_V_TVALID,
        res_V_data_2_V_TREADY,
        res_V_data_3_V_TDATA,
        res_V_data_3_V_TVALID,
        res_V_data_3_V_TREADY,
        res_V_data_4_V_TDATA,
        res_V_data_4_V_TVALID,
        res_V_data_4_V_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [7:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [7:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [7:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
input  [7:0] data_V_data_4_V_dout;
input   data_V_data_4_V_empty_n;
output   data_V_data_4_V_read;
input   res_V_data_0_V_TREADY;
output  [15:0] res_V_data_0_V_TDATA;
output   res_V_data_0_V_TVALID;
output  [15:0] res_V_data_1_V_TDATA;
output   res_V_data_1_V_TVALID;
input   res_V_data_1_V_TREADY;
output  [15:0] res_V_data_2_V_TDATA;
output   res_V_data_2_V_TVALID;
input   res_V_data_2_V_TREADY;
output  [15:0] res_V_data_3_V_TDATA;
output   res_V_data_3_V_TVALID;
input   res_V_data_3_V_TREADY;
output  [15:0] res_V_data_4_V_TDATA;
output   res_V_data_4_V_TVALID;
input   res_V_data_4_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;
reg data_V_data_4_V_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    io_acc_block_signal_op3;
reg    ap_block_state1_pp0_stage0_iter0;
wire    res_V_data_0_V_1_ack_in;
wire    res_V_data_0_V_1_ack_out;
reg   [1:0] res_V_data_0_V_1_state;
wire    res_V_data_1_V_1_ack_out;
reg   [1:0] res_V_data_1_V_1_state;
wire    res_V_data_2_V_1_ack_out;
reg   [1:0] res_V_data_2_V_1_state;
wire    res_V_data_3_V_1_ack_out;
reg   [1:0] res_V_data_3_V_1_state;
wire    res_V_data_4_V_1_ack_out;
reg   [1:0] res_V_data_4_V_1_state;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] res_V_data_0_V_1_data_out;
reg    res_V_data_0_V_1_vld_in;
wire    res_V_data_0_V_1_vld_out;
reg   [15:0] res_V_data_0_V_1_payload_A;
reg   [15:0] res_V_data_0_V_1_payload_B;
reg    res_V_data_0_V_1_sel_rd;
reg    res_V_data_0_V_1_sel_wr;
wire    res_V_data_0_V_1_sel;
wire    res_V_data_0_V_1_load_A;
wire    res_V_data_0_V_1_load_B;
wire    res_V_data_0_V_1_state_cmp_full;
reg   [15:0] res_V_data_1_V_1_data_out;
reg    res_V_data_1_V_1_vld_in;
wire    res_V_data_1_V_1_vld_out;
wire    res_V_data_1_V_1_ack_in;
reg   [15:0] res_V_data_1_V_1_payload_A;
reg   [15:0] res_V_data_1_V_1_payload_B;
reg    res_V_data_1_V_1_sel_rd;
reg    res_V_data_1_V_1_sel_wr;
wire    res_V_data_1_V_1_sel;
wire    res_V_data_1_V_1_load_A;
wire    res_V_data_1_V_1_load_B;
wire    res_V_data_1_V_1_state_cmp_full;
reg   [15:0] res_V_data_2_V_1_data_out;
reg    res_V_data_2_V_1_vld_in;
wire    res_V_data_2_V_1_vld_out;
wire    res_V_data_2_V_1_ack_in;
reg   [15:0] res_V_data_2_V_1_payload_A;
reg   [15:0] res_V_data_2_V_1_payload_B;
reg    res_V_data_2_V_1_sel_rd;
reg    res_V_data_2_V_1_sel_wr;
wire    res_V_data_2_V_1_sel;
wire    res_V_data_2_V_1_load_A;
wire    res_V_data_2_V_1_load_B;
wire    res_V_data_2_V_1_state_cmp_full;
reg   [15:0] res_V_data_3_V_1_data_out;
reg    res_V_data_3_V_1_vld_in;
wire    res_V_data_3_V_1_vld_out;
wire    res_V_data_3_V_1_ack_in;
reg   [15:0] res_V_data_3_V_1_payload_A;
reg   [15:0] res_V_data_3_V_1_payload_B;
reg    res_V_data_3_V_1_sel_rd;
reg    res_V_data_3_V_1_sel_wr;
wire    res_V_data_3_V_1_sel;
wire    res_V_data_3_V_1_load_A;
wire    res_V_data_3_V_1_load_B;
wire    res_V_data_3_V_1_state_cmp_full;
reg   [15:0] res_V_data_4_V_1_data_out;
reg    res_V_data_4_V_1_vld_in;
wire    res_V_data_4_V_1_vld_out;
wire    res_V_data_4_V_1_ack_in;
reg   [15:0] res_V_data_4_V_1_payload_A;
reg   [15:0] res_V_data_4_V_1_payload_B;
reg    res_V_data_4_V_1_sel_rd;
reg    res_V_data_4_V_1_sel_wr;
wire    res_V_data_4_V_1_sel;
wire    res_V_data_4_V_1_load_A;
wire    res_V_data_4_V_1_load_B;
wire    res_V_data_4_V_1_state_cmp_full;
reg    data_V_data_0_V_blk_n;
wire    ap_block_pp0_stage0;
reg    data_V_data_1_V_blk_n;
reg    data_V_data_2_V_blk_n;
reg    data_V_data_3_V_blk_n;
reg    data_V_data_4_V_blk_n;
reg    res_V_data_0_V_TDATA_blk_n;
reg    res_V_data_1_V_TDATA_blk_n;
reg    res_V_data_2_V_TDATA_blk_n;
reg    res_V_data_3_V_TDATA_blk_n;
reg    res_V_data_4_V_TDATA_blk_n;
wire  signed [15:0] tmp_data_0_V_3_fu_179_p1;
wire  signed [15:0] tmp_data_1_V_3_fu_192_p1;
wire  signed [15:0] tmp_data_2_V_3_fu_205_p1;
wire  signed [15:0] tmp_data_3_V_3_fu_218_p1;
wire  signed [15:0] tmp_data_4_V_3_fu_231_p1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
wire   [11:0] tmp_data_0_V_fu_171_p3;
wire   [11:0] tmp_data_1_V_fu_184_p3;
wire   [11:0] tmp_data_2_V_fu_197_p3;
wire   [11:0] tmp_data_3_V_fu_210_p3;
wire   [11:0] tmp_data_4_V_fu_223_p3;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 res_V_data_0_V_1_state = 2'd0;
#0 res_V_data_1_V_1_state = 2'd0;
#0 res_V_data_2_V_1_state = 2'd0;
#0 res_V_data_3_V_1_state = 2'd0;
#0 res_V_data_4_V_1_state = 2'd0;
#0 res_V_data_0_V_1_sel_rd = 1'b0;
#0 res_V_data_0_V_1_sel_wr = 1'b0;
#0 res_V_data_1_V_1_sel_rd = 1'b0;
#0 res_V_data_1_V_1_sel_wr = 1'b0;
#0 res_V_data_2_V_1_sel_rd = 1'b0;
#0 res_V_data_2_V_1_sel_wr = 1'b0;
#0 res_V_data_3_V_1_sel_rd = 1'b0;
#0 res_V_data_3_V_1_sel_wr = 1'b0;
#0 res_V_data_4_V_1_sel_rd = 1'b0;
#0 res_V_data_4_V_1_sel_wr = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_0_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_0_V_1_ack_out == 1'b1) & (res_V_data_0_V_1_vld_out == 1'b1))) begin
            res_V_data_0_V_1_sel_rd <= ~res_V_data_0_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_0_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_0_V_1_ack_in == 1'b1) & (res_V_data_0_V_1_vld_in == 1'b1))) begin
            res_V_data_0_V_1_sel_wr <= ~res_V_data_0_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_0_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_0_V_1_state == 2'd3) & (res_V_data_0_V_1_vld_in == 1'b0) & (res_V_data_0_V_1_ack_out == 1'b1)) | ((res_V_data_0_V_1_state == 2'd2) & (res_V_data_0_V_1_vld_in == 1'b0)))) begin
            res_V_data_0_V_1_state <= 2'd2;
        end else if ((((res_V_data_0_V_1_state == 2'd1) & (res_V_data_0_V_TREADY == 1'b0)) | ((res_V_data_0_V_1_state == 2'd3) & (res_V_data_0_V_TREADY == 1'b0) & (res_V_data_0_V_1_vld_in == 1'b1)))) begin
            res_V_data_0_V_1_state <= 2'd1;
        end else if ((((res_V_data_0_V_1_state == 2'd1) & (res_V_data_0_V_1_ack_out == 1'b1)) | (~((res_V_data_0_V_1_vld_in == 1'b0) & (res_V_data_0_V_1_ack_out == 1'b1)) & ~((res_V_data_0_V_TREADY == 1'b0) & (res_V_data_0_V_1_vld_in == 1'b1)) & (res_V_data_0_V_1_state == 2'd3)) | ((res_V_data_0_V_1_state == 2'd2) & (res_V_data_0_V_1_vld_in == 1'b1)))) begin
            res_V_data_0_V_1_state <= 2'd3;
        end else begin
            res_V_data_0_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_1_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_1_V_1_ack_out == 1'b1) & (res_V_data_1_V_1_vld_out == 1'b1))) begin
            res_V_data_1_V_1_sel_rd <= ~res_V_data_1_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_1_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_1_V_1_ack_in == 1'b1) & (res_V_data_1_V_1_vld_in == 1'b1))) begin
            res_V_data_1_V_1_sel_wr <= ~res_V_data_1_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_1_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_1_V_1_state == 2'd3) & (res_V_data_1_V_1_vld_in == 1'b0) & (res_V_data_1_V_1_ack_out == 1'b1)) | ((res_V_data_1_V_1_state == 2'd2) & (res_V_data_1_V_1_vld_in == 1'b0)))) begin
            res_V_data_1_V_1_state <= 2'd2;
        end else if ((((res_V_data_1_V_1_state == 2'd1) & (res_V_data_1_V_TREADY == 1'b0)) | ((res_V_data_1_V_1_state == 2'd3) & (res_V_data_1_V_TREADY == 1'b0) & (res_V_data_1_V_1_vld_in == 1'b1)))) begin
            res_V_data_1_V_1_state <= 2'd1;
        end else if ((((res_V_data_1_V_1_state == 2'd1) & (res_V_data_1_V_1_ack_out == 1'b1)) | (~((res_V_data_1_V_1_vld_in == 1'b0) & (res_V_data_1_V_1_ack_out == 1'b1)) & ~((res_V_data_1_V_TREADY == 1'b0) & (res_V_data_1_V_1_vld_in == 1'b1)) & (res_V_data_1_V_1_state == 2'd3)) | ((res_V_data_1_V_1_state == 2'd2) & (res_V_data_1_V_1_vld_in == 1'b1)))) begin
            res_V_data_1_V_1_state <= 2'd3;
        end else begin
            res_V_data_1_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_2_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_2_V_1_ack_out == 1'b1) & (res_V_data_2_V_1_vld_out == 1'b1))) begin
            res_V_data_2_V_1_sel_rd <= ~res_V_data_2_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_2_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_2_V_1_ack_in == 1'b1) & (res_V_data_2_V_1_vld_in == 1'b1))) begin
            res_V_data_2_V_1_sel_wr <= ~res_V_data_2_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_2_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_2_V_1_state == 2'd3) & (res_V_data_2_V_1_vld_in == 1'b0) & (res_V_data_2_V_1_ack_out == 1'b1)) | ((res_V_data_2_V_1_state == 2'd2) & (res_V_data_2_V_1_vld_in == 1'b0)))) begin
            res_V_data_2_V_1_state <= 2'd2;
        end else if ((((res_V_data_2_V_1_state == 2'd1) & (res_V_data_2_V_TREADY == 1'b0)) | ((res_V_data_2_V_1_state == 2'd3) & (res_V_data_2_V_TREADY == 1'b0) & (res_V_data_2_V_1_vld_in == 1'b1)))) begin
            res_V_data_2_V_1_state <= 2'd1;
        end else if ((((res_V_data_2_V_1_state == 2'd1) & (res_V_data_2_V_1_ack_out == 1'b1)) | (~((res_V_data_2_V_1_vld_in == 1'b0) & (res_V_data_2_V_1_ack_out == 1'b1)) & ~((res_V_data_2_V_TREADY == 1'b0) & (res_V_data_2_V_1_vld_in == 1'b1)) & (res_V_data_2_V_1_state == 2'd3)) | ((res_V_data_2_V_1_state == 2'd2) & (res_V_data_2_V_1_vld_in == 1'b1)))) begin
            res_V_data_2_V_1_state <= 2'd3;
        end else begin
            res_V_data_2_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_3_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_3_V_1_ack_out == 1'b1) & (res_V_data_3_V_1_vld_out == 1'b1))) begin
            res_V_data_3_V_1_sel_rd <= ~res_V_data_3_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_3_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_3_V_1_ack_in == 1'b1) & (res_V_data_3_V_1_vld_in == 1'b1))) begin
            res_V_data_3_V_1_sel_wr <= ~res_V_data_3_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_3_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_3_V_1_state == 2'd3) & (res_V_data_3_V_1_vld_in == 1'b0) & (res_V_data_3_V_1_ack_out == 1'b1)) | ((res_V_data_3_V_1_state == 2'd2) & (res_V_data_3_V_1_vld_in == 1'b0)))) begin
            res_V_data_3_V_1_state <= 2'd2;
        end else if ((((res_V_data_3_V_1_state == 2'd1) & (res_V_data_3_V_TREADY == 1'b0)) | ((res_V_data_3_V_1_state == 2'd3) & (res_V_data_3_V_TREADY == 1'b0) & (res_V_data_3_V_1_vld_in == 1'b1)))) begin
            res_V_data_3_V_1_state <= 2'd1;
        end else if ((((res_V_data_3_V_1_state == 2'd1) & (res_V_data_3_V_1_ack_out == 1'b1)) | (~((res_V_data_3_V_1_vld_in == 1'b0) & (res_V_data_3_V_1_ack_out == 1'b1)) & ~((res_V_data_3_V_TREADY == 1'b0) & (res_V_data_3_V_1_vld_in == 1'b1)) & (res_V_data_3_V_1_state == 2'd3)) | ((res_V_data_3_V_1_state == 2'd2) & (res_V_data_3_V_1_vld_in == 1'b1)))) begin
            res_V_data_3_V_1_state <= 2'd3;
        end else begin
            res_V_data_3_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_4_V_1_sel_rd <= 1'b0;
    end else begin
        if (((res_V_data_4_V_1_vld_out == 1'b1) & (res_V_data_4_V_1_ack_out == 1'b1))) begin
            res_V_data_4_V_1_sel_rd <= ~res_V_data_4_V_1_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_4_V_1_sel_wr <= 1'b0;
    end else begin
        if (((res_V_data_4_V_1_ack_in == 1'b1) & (res_V_data_4_V_1_vld_in == 1'b1))) begin
            res_V_data_4_V_1_sel_wr <= ~res_V_data_4_V_1_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        res_V_data_4_V_1_state <= 2'd0;
    end else begin
        if ((((res_V_data_4_V_1_state == 2'd3) & (res_V_data_4_V_1_vld_in == 1'b0) & (res_V_data_4_V_1_ack_out == 1'b1)) | ((res_V_data_4_V_1_state == 2'd2) & (res_V_data_4_V_1_vld_in == 1'b0)))) begin
            res_V_data_4_V_1_state <= 2'd2;
        end else if ((((res_V_data_4_V_1_state == 2'd1) & (res_V_data_4_V_TREADY == 1'b0)) | ((res_V_data_4_V_1_state == 2'd3) & (res_V_data_4_V_TREADY == 1'b0) & (res_V_data_4_V_1_vld_in == 1'b1)))) begin
            res_V_data_4_V_1_state <= 2'd1;
        end else if ((((res_V_data_4_V_1_state == 2'd1) & (res_V_data_4_V_1_ack_out == 1'b1)) | (~((res_V_data_4_V_1_vld_in == 1'b0) & (res_V_data_4_V_1_ack_out == 1'b1)) & ~((res_V_data_4_V_TREADY == 1'b0) & (res_V_data_4_V_1_vld_in == 1'b1)) & (res_V_data_4_V_1_state == 2'd3)) | ((res_V_data_4_V_1_state == 2'd2) & (res_V_data_4_V_1_vld_in == 1'b1)))) begin
            res_V_data_4_V_1_state <= 2'd3;
        end else begin
            res_V_data_4_V_1_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_0_V_1_load_A == 1'b1)) begin
        res_V_data_0_V_1_payload_A <= tmp_data_0_V_3_fu_179_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_0_V_1_load_B == 1'b1)) begin
        res_V_data_0_V_1_payload_B <= tmp_data_0_V_3_fu_179_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_1_V_1_load_A == 1'b1)) begin
        res_V_data_1_V_1_payload_A <= tmp_data_1_V_3_fu_192_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_1_V_1_load_B == 1'b1)) begin
        res_V_data_1_V_1_payload_B <= tmp_data_1_V_3_fu_192_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_2_V_1_load_A == 1'b1)) begin
        res_V_data_2_V_1_payload_A <= tmp_data_2_V_3_fu_205_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_2_V_1_load_B == 1'b1)) begin
        res_V_data_2_V_1_payload_B <= tmp_data_2_V_3_fu_205_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_3_V_1_load_A == 1'b1)) begin
        res_V_data_3_V_1_payload_A <= tmp_data_3_V_3_fu_218_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_3_V_1_load_B == 1'b1)) begin
        res_V_data_3_V_1_payload_B <= tmp_data_3_V_3_fu_218_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_4_V_1_load_A == 1'b1)) begin
        res_V_data_4_V_1_payload_A <= tmp_data_4_V_3_fu_231_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((res_V_data_4_V_1_load_B == 1'b1)) begin
        res_V_data_4_V_1_payload_B <= tmp_data_4_V_3_fu_231_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_0_V_read = 1'b1;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_1_V_read = 1'b1;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_2_V_read = 1'b1;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_3_V_read = 1'b1;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_4_V_blk_n = data_V_data_4_V_empty_n;
    end else begin
        data_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        data_V_data_4_V_read = 1'b1;
    end else begin
        data_V_data_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((res_V_data_0_V_1_sel == 1'b1)) begin
        res_V_data_0_V_1_data_out = res_V_data_0_V_1_payload_B;
    end else begin
        res_V_data_0_V_1_data_out = res_V_data_0_V_1_payload_A;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_V_data_0_V_1_vld_in = 1'b1;
    end else begin
        res_V_data_0_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        res_V_data_0_V_TDATA_blk_n = res_V_data_0_V_1_state[1'd1];
    end else begin
        res_V_data_0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((res_V_data_1_V_1_sel == 1'b1)) begin
        res_V_data_1_V_1_data_out = res_V_data_1_V_1_payload_B;
    end else begin
        res_V_data_1_V_1_data_out = res_V_data_1_V_1_payload_A;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_V_data_1_V_1_vld_in = 1'b1;
    end else begin
        res_V_data_1_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        res_V_data_1_V_TDATA_blk_n = res_V_data_1_V_1_state[1'd1];
    end else begin
        res_V_data_1_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((res_V_data_2_V_1_sel == 1'b1)) begin
        res_V_data_2_V_1_data_out = res_V_data_2_V_1_payload_B;
    end else begin
        res_V_data_2_V_1_data_out = res_V_data_2_V_1_payload_A;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_V_data_2_V_1_vld_in = 1'b1;
    end else begin
        res_V_data_2_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        res_V_data_2_V_TDATA_blk_n = res_V_data_2_V_1_state[1'd1];
    end else begin
        res_V_data_2_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((res_V_data_3_V_1_sel == 1'b1)) begin
        res_V_data_3_V_1_data_out = res_V_data_3_V_1_payload_B;
    end else begin
        res_V_data_3_V_1_data_out = res_V_data_3_V_1_payload_A;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_V_data_3_V_1_vld_in = 1'b1;
    end else begin
        res_V_data_3_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        res_V_data_3_V_TDATA_blk_n = res_V_data_3_V_1_state[1'd1];
    end else begin
        res_V_data_3_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((res_V_data_4_V_1_sel == 1'b1)) begin
        res_V_data_4_V_1_data_out = res_V_data_4_V_1_payload_B;
    end else begin
        res_V_data_4_V_1_data_out = res_V_data_4_V_1_payload_A;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        res_V_data_4_V_1_vld_in = 1'b1;
    end else begin
        res_V_data_4_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        res_V_data_4_V_TDATA_blk_n = res_V_data_4_V_1_state[1'd1];
    end else begin
        res_V_data_4_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((ap_start == 1'b0) | (io_acc_block_signal_op3 == 1'b0) | (ap_done_reg == 1'b1))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((res_V_data_2_V_1_state == 2'd1) | (res_V_data_1_V_1_state == 2'd1) | (res_V_data_4_V_1_state == 2'd1) | (res_V_data_3_V_1_state == 2'd1) | (res_V_data_0_V_1_state == 2'd1) | ((res_V_data_2_V_1_state == 2'd3) & (res_V_data_2_V_TREADY == 1'b0)) | ((res_V_data_1_V_1_state == 2'd3) & (res_V_data_1_V_TREADY == 1'b0)) | ((res_V_data_0_V_1_state == 2'd3) & (res_V_data_0_V_TREADY == 1'b0)) | ((res_V_data_4_V_1_state == 2'd3) & (res_V_data_4_V_TREADY == 1'b0)) | ((res_V_data_3_V_1_state == 2'd3) & (res_V_data_3_V_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((res_V_data_0_V_1_ack_in == 1'b0) | (ap_start == 1'b0) | (io_acc_block_signal_op3 == 1'b0) | (ap_done_reg == 1'b1))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((res_V_data_2_V_1_state == 2'd1) | (res_V_data_1_V_1_state == 2'd1) | (res_V_data_4_V_1_state == 2'd1) | (res_V_data_3_V_1_state == 2'd1) | (res_V_data_0_V_1_state == 2'd1) | (res_V_data_0_V_1_ack_in == 1'b0) | ((res_V_data_2_V_1_state == 2'd3) & (res_V_data_2_V_TREADY == 1'b0)) | ((res_V_data_1_V_1_state == 2'd3) & (res_V_data_1_V_TREADY == 1'b0)) | ((res_V_data_0_V_1_state == 2'd3) & (res_V_data_0_V_TREADY == 1'b0)) | ((res_V_data_4_V_1_state == 2'd3) & (res_V_data_4_V_TREADY == 1'b0)) | ((res_V_data_3_V_1_state == 2'd3) & (res_V_data_3_V_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_start == 1'b1) & ((res_V_data_0_V_1_ack_in == 1'b0) | (ap_start == 1'b0) | (io_acc_block_signal_op3 == 1'b0) | (ap_done_reg == 1'b1))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((res_V_data_2_V_1_state == 2'd1) | (res_V_data_1_V_1_state == 2'd1) | (res_V_data_4_V_1_state == 2'd1) | (res_V_data_3_V_1_state == 2'd1) | (res_V_data_0_V_1_state == 2'd1) | (res_V_data_0_V_1_ack_in == 1'b0) | ((res_V_data_2_V_1_state == 2'd3) & (res_V_data_2_V_TREADY == 1'b0)) | ((res_V_data_1_V_1_state == 2'd3) & (res_V_data_1_V_TREADY == 1'b0)) | ((res_V_data_0_V_1_state == 2'd3) & (res_V_data_0_V_TREADY == 1'b0)) | ((res_V_data_4_V_1_state == 2'd3) & (res_V_data_4_V_TREADY == 1'b0)) | ((res_V_data_3_V_1_state == 2'd3) & (res_V_data_3_V_TREADY == 1'b0)))));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start == 1'b0) | (io_acc_block_signal_op3 == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((res_V_data_2_V_1_state == 2'd1) | (res_V_data_1_V_1_state == 2'd1) | (res_V_data_4_V_1_state == 2'd1) | (res_V_data_3_V_1_state == 2'd1) | (res_V_data_0_V_1_state == 2'd1) | ((res_V_data_2_V_1_state == 2'd3) & (res_V_data_2_V_TREADY == 1'b0)) | ((res_V_data_1_V_1_state == 2'd3) & (res_V_data_1_V_TREADY == 1'b0)) | ((res_V_data_0_V_1_state == 2'd3) & (res_V_data_0_V_TREADY == 1'b0)) | ((res_V_data_4_V_1_state == 2'd3) & (res_V_data_4_V_TREADY == 1'b0)) | ((res_V_data_3_V_1_state == 2'd3) & (res_V_data_3_V_TREADY == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign io_acc_block_signal_op3 = (data_V_data_4_V_empty_n & data_V_data_3_V_empty_n & data_V_data_2_V_empty_n & data_V_data_1_V_empty_n & data_V_data_0_V_empty_n);

assign res_V_data_0_V_1_ack_in = res_V_data_0_V_1_state[1'd1];

assign res_V_data_0_V_1_ack_out = res_V_data_0_V_TREADY;

assign res_V_data_0_V_1_load_A = (res_V_data_0_V_1_state_cmp_full & ~res_V_data_0_V_1_sel_wr);

assign res_V_data_0_V_1_load_B = (res_V_data_0_V_1_state_cmp_full & res_V_data_0_V_1_sel_wr);

assign res_V_data_0_V_1_sel = res_V_data_0_V_1_sel_rd;

assign res_V_data_0_V_1_state_cmp_full = ((res_V_data_0_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_0_V_1_vld_out = res_V_data_0_V_1_state[1'd0];

assign res_V_data_0_V_TDATA = res_V_data_0_V_1_data_out;

assign res_V_data_0_V_TVALID = res_V_data_0_V_1_state[1'd0];

assign res_V_data_1_V_1_ack_in = res_V_data_1_V_1_state[1'd1];

assign res_V_data_1_V_1_ack_out = res_V_data_1_V_TREADY;

assign res_V_data_1_V_1_load_A = (res_V_data_1_V_1_state_cmp_full & ~res_V_data_1_V_1_sel_wr);

assign res_V_data_1_V_1_load_B = (res_V_data_1_V_1_state_cmp_full & res_V_data_1_V_1_sel_wr);

assign res_V_data_1_V_1_sel = res_V_data_1_V_1_sel_rd;

assign res_V_data_1_V_1_state_cmp_full = ((res_V_data_1_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_1_V_1_vld_out = res_V_data_1_V_1_state[1'd0];

assign res_V_data_1_V_TDATA = res_V_data_1_V_1_data_out;

assign res_V_data_1_V_TVALID = res_V_data_1_V_1_state[1'd0];

assign res_V_data_2_V_1_ack_in = res_V_data_2_V_1_state[1'd1];

assign res_V_data_2_V_1_ack_out = res_V_data_2_V_TREADY;

assign res_V_data_2_V_1_load_A = (res_V_data_2_V_1_state_cmp_full & ~res_V_data_2_V_1_sel_wr);

assign res_V_data_2_V_1_load_B = (res_V_data_2_V_1_state_cmp_full & res_V_data_2_V_1_sel_wr);

assign res_V_data_2_V_1_sel = res_V_data_2_V_1_sel_rd;

assign res_V_data_2_V_1_state_cmp_full = ((res_V_data_2_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_2_V_1_vld_out = res_V_data_2_V_1_state[1'd0];

assign res_V_data_2_V_TDATA = res_V_data_2_V_1_data_out;

assign res_V_data_2_V_TVALID = res_V_data_2_V_1_state[1'd0];

assign res_V_data_3_V_1_ack_in = res_V_data_3_V_1_state[1'd1];

assign res_V_data_3_V_1_ack_out = res_V_data_3_V_TREADY;

assign res_V_data_3_V_1_load_A = (res_V_data_3_V_1_state_cmp_full & ~res_V_data_3_V_1_sel_wr);

assign res_V_data_3_V_1_load_B = (res_V_data_3_V_1_state_cmp_full & res_V_data_3_V_1_sel_wr);

assign res_V_data_3_V_1_sel = res_V_data_3_V_1_sel_rd;

assign res_V_data_3_V_1_state_cmp_full = ((res_V_data_3_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_3_V_1_vld_out = res_V_data_3_V_1_state[1'd0];

assign res_V_data_3_V_TDATA = res_V_data_3_V_1_data_out;

assign res_V_data_3_V_TVALID = res_V_data_3_V_1_state[1'd0];

assign res_V_data_4_V_1_ack_in = res_V_data_4_V_1_state[1'd1];

assign res_V_data_4_V_1_ack_out = res_V_data_4_V_TREADY;

assign res_V_data_4_V_1_load_A = (res_V_data_4_V_1_state_cmp_full & ~res_V_data_4_V_1_sel_wr);

assign res_V_data_4_V_1_load_B = (res_V_data_4_V_1_state_cmp_full & res_V_data_4_V_1_sel_wr);

assign res_V_data_4_V_1_sel = res_V_data_4_V_1_sel_rd;

assign res_V_data_4_V_1_state_cmp_full = ((res_V_data_4_V_1_state != 2'd1) ? 1'b1 : 1'b0);

assign res_V_data_4_V_1_vld_out = res_V_data_4_V_1_state[1'd0];

assign res_V_data_4_V_TDATA = res_V_data_4_V_1_data_out;

assign res_V_data_4_V_TVALID = res_V_data_4_V_1_state[1'd0];

assign tmp_data_0_V_3_fu_179_p1 = $signed(tmp_data_0_V_fu_171_p3);

assign tmp_data_0_V_fu_171_p3 = {{data_V_data_0_V_dout}, {4'd0}};

assign tmp_data_1_V_3_fu_192_p1 = $signed(tmp_data_1_V_fu_184_p3);

assign tmp_data_1_V_fu_184_p3 = {{data_V_data_1_V_dout}, {4'd0}};

assign tmp_data_2_V_3_fu_205_p1 = $signed(tmp_data_2_V_fu_197_p3);

assign tmp_data_2_V_fu_197_p3 = {{data_V_data_2_V_dout}, {4'd0}};

assign tmp_data_3_V_3_fu_218_p1 = $signed(tmp_data_3_V_fu_210_p3);

assign tmp_data_3_V_fu_210_p3 = {{data_V_data_3_V_dout}, {4'd0}};

assign tmp_data_4_V_3_fu_231_p1 = $signed(tmp_data_4_V_fu_223_p3);

assign tmp_data_4_V_fu_223_p3 = {{data_V_data_4_V_dout}, {4'd0}};

endmodule //linear_array_array_ap_fixed_16_6_5_3_0_5u_linear_config22_s
