apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homevol
  namespace: uw-acme
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi