apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sharedvol
  namespace: uw-acme
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 128Gi