// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_0_V_dout,
        data_V_data_0_V_empty_n,
        data_V_data_0_V_read,
        data_V_data_1_V_dout,
        data_V_data_1_V_empty_n,
        data_V_data_1_V_read,
        data_V_data_2_V_dout,
        data_V_data_2_V_empty_n,
        data_V_data_2_V_read,
        data_V_data_3_V_dout,
        data_V_data_3_V_empty_n,
        data_V_data_3_V_read,
        data_V_data_4_V_dout,
        data_V_data_4_V_empty_n,
        data_V_data_4_V_read,
        data_V_data_5_V_dout,
        data_V_data_5_V_empty_n,
        data_V_data_5_V_read,
        data_V_data_6_V_dout,
        data_V_data_6_V_empty_n,
        data_V_data_6_V_read,
        data_V_data_7_V_dout,
        data_V_data_7_V_empty_n,
        data_V_data_7_V_read,
        data_V_data_8_V_dout,
        data_V_data_8_V_empty_n,
        data_V_data_8_V_read,
        data_V_data_9_V_dout,
        data_V_data_9_V_empty_n,
        data_V_data_9_V_read,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write,
        res_V_data_4_V_din,
        res_V_data_4_V_full_n,
        res_V_data_4_V_write,
        res_V_data_5_V_din,
        res_V_data_5_V_full_n,
        res_V_data_5_V_write,
        res_V_data_6_V_din,
        res_V_data_6_V_full_n,
        res_V_data_6_V_write,
        res_V_data_7_V_din,
        res_V_data_7_V_full_n,
        res_V_data_7_V_write,
        res_V_data_8_V_din,
        res_V_data_8_V_full_n,
        res_V_data_8_V_write,
        res_V_data_9_V_din,
        res_V_data_9_V_full_n,
        res_V_data_9_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state6 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [7:0] data_V_data_0_V_dout;
input   data_V_data_0_V_empty_n;
output   data_V_data_0_V_read;
input  [7:0] data_V_data_1_V_dout;
input   data_V_data_1_V_empty_n;
output   data_V_data_1_V_read;
input  [7:0] data_V_data_2_V_dout;
input   data_V_data_2_V_empty_n;
output   data_V_data_2_V_read;
input  [7:0] data_V_data_3_V_dout;
input   data_V_data_3_V_empty_n;
output   data_V_data_3_V_read;
input  [7:0] data_V_data_4_V_dout;
input   data_V_data_4_V_empty_n;
output   data_V_data_4_V_read;
input  [7:0] data_V_data_5_V_dout;
input   data_V_data_5_V_empty_n;
output   data_V_data_5_V_read;
input  [7:0] data_V_data_6_V_dout;
input   data_V_data_6_V_empty_n;
output   data_V_data_6_V_read;
input  [7:0] data_V_data_7_V_dout;
input   data_V_data_7_V_empty_n;
output   data_V_data_7_V_read;
input  [7:0] data_V_data_8_V_dout;
input   data_V_data_8_V_empty_n;
output   data_V_data_8_V_read;
input  [7:0] data_V_data_9_V_dout;
input   data_V_data_9_V_empty_n;
output   data_V_data_9_V_read;
output  [7:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [7:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [7:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [7:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;
output  [7:0] res_V_data_4_V_din;
input   res_V_data_4_V_full_n;
output   res_V_data_4_V_write;
output  [7:0] res_V_data_5_V_din;
input   res_V_data_5_V_full_n;
output   res_V_data_5_V_write;
output  [7:0] res_V_data_6_V_din;
input   res_V_data_6_V_full_n;
output   res_V_data_6_V_write;
output  [7:0] res_V_data_7_V_din;
input   res_V_data_7_V_full_n;
output   res_V_data_7_V_write;
output  [7:0] res_V_data_8_V_din;
input   res_V_data_8_V_full_n;
output   res_V_data_8_V_write;
output  [7:0] res_V_data_9_V_din;
input   res_V_data_9_V_full_n;
output   res_V_data_9_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_0_V_read;
reg data_V_data_1_V_read;
reg data_V_data_2_V_read;
reg data_V_data_3_V_read;
reg data_V_data_4_V_read;
reg data_V_data_5_V_read;
reg data_V_data_6_V_read;
reg data_V_data_7_V_read;
reg data_V_data_8_V_read;
reg data_V_data_9_V_read;
reg res_V_data_0_V_write;
reg res_V_data_1_V_write;
reg res_V_data_2_V_write;
reg res_V_data_3_V_write;
reg res_V_data_4_V_write;
reg res_V_data_5_V_write;
reg res_V_data_6_V_write;
reg res_V_data_7_V_write;
reg res_V_data_8_V_write;
reg res_V_data_9_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [31:0] pX_2;
reg   [31:0] sX_2;
reg   [31:0] pY_2;
reg   [31:0] sY_2;
reg   [7:0] kernel_data_V_3_10;
reg   [7:0] kernel_data_V_3_11;
reg   [7:0] kernel_data_V_3_12;
reg   [7:0] kernel_data_V_3_13;
reg   [7:0] kernel_data_V_3_14;
reg   [7:0] kernel_data_V_3_15;
reg   [7:0] kernel_data_V_3_16;
reg   [7:0] kernel_data_V_3_17;
reg   [7:0] kernel_data_V_3_18;
reg   [7:0] kernel_data_V_3_19;
reg   [7:0] kernel_data_V_3_30;
reg   [7:0] kernel_data_V_3_31;
reg   [7:0] kernel_data_V_3_32;
reg   [7:0] kernel_data_V_3_33;
reg   [7:0] kernel_data_V_3_34;
reg   [7:0] kernel_data_V_3_35;
reg   [7:0] kernel_data_V_3_36;
reg   [7:0] kernel_data_V_3_37;
reg   [7:0] kernel_data_V_3_38;
reg   [7:0] kernel_data_V_3_39;
reg    line_buffer_Array_V_3_0_0_ce0;
reg    line_buffer_Array_V_3_0_0_we0;
wire   [7:0] line_buffer_Array_V_3_0_0_q0;
reg    line_buffer_Array_V_3_0_1_ce0;
reg    line_buffer_Array_V_3_0_1_we0;
wire   [7:0] line_buffer_Array_V_3_0_1_q0;
reg    line_buffer_Array_V_3_0_2_ce0;
reg    line_buffer_Array_V_3_0_2_we0;
wire   [7:0] line_buffer_Array_V_3_0_2_q0;
reg    line_buffer_Array_V_3_0_3_ce0;
reg    line_buffer_Array_V_3_0_3_we0;
wire   [7:0] line_buffer_Array_V_3_0_3_q0;
reg    line_buffer_Array_V_3_0_4_ce0;
reg    line_buffer_Array_V_3_0_4_we0;
wire   [7:0] line_buffer_Array_V_3_0_4_q0;
reg    line_buffer_Array_V_3_0_5_ce0;
reg    line_buffer_Array_V_3_0_5_we0;
wire   [7:0] line_buffer_Array_V_3_0_5_q0;
reg    line_buffer_Array_V_3_0_6_ce0;
reg    line_buffer_Array_V_3_0_6_we0;
wire   [7:0] line_buffer_Array_V_3_0_6_q0;
reg    line_buffer_Array_V_3_0_7_ce0;
reg    line_buffer_Array_V_3_0_7_we0;
wire   [7:0] line_buffer_Array_V_3_0_7_q0;
reg    line_buffer_Array_V_3_0_8_ce0;
reg    line_buffer_Array_V_3_0_8_we0;
wire   [7:0] line_buffer_Array_V_3_0_8_q0;
reg    line_buffer_Array_V_3_0_9_ce0;
reg    line_buffer_Array_V_3_0_9_we0;
wire   [7:0] line_buffer_Array_V_3_0_9_q0;
reg    data_V_data_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln241_reg_2233;
reg    data_V_data_1_V_blk_n;
reg    data_V_data_2_V_blk_n;
reg    data_V_data_3_V_blk_n;
reg    data_V_data_4_V_blk_n;
reg    data_V_data_5_V_blk_n;
reg    data_V_data_6_V_blk_n;
reg    data_V_data_7_V_blk_n;
reg    data_V_data_8_V_blk_n;
reg    data_V_data_9_V_blk_n;
reg    res_V_data_0_V_blk_n;
reg    ap_enable_reg_pp0_iter3;
reg   [0:0] and_ln191_6_reg_2380;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
reg    res_V_data_4_V_blk_n;
reg    res_V_data_5_V_blk_n;
reg    res_V_data_6_V_blk_n;
reg    res_V_data_7_V_blk_n;
reg    res_V_data_8_V_blk_n;
reg    res_V_data_9_V_blk_n;
reg   [2:0] indvar_flatten_reg_488;
wire   [0:0] icmp_ln241_fu_510_p2;
wire    ap_block_state2_pp0_stage0_iter0;
wire    io_acc_block_signal_op33;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    io_acc_block_signal_op314;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln241_reg_2233_pp0_iter1_reg;
wire   [2:0] add_ln241_fu_516_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [7:0] shift_buffer_1_0_V_reg_2242;
reg   [7:0] shift_buffer_1_1_V_reg_2248;
reg   [7:0] shift_buffer_1_2_V_reg_2254;
reg   [7:0] shift_buffer_1_3_V_reg_2260;
reg   [7:0] shift_buffer_1_4_V_reg_2266;
reg   [7:0] shift_buffer_1_5_V_reg_2272;
reg   [7:0] shift_buffer_1_6_V_reg_2278;
reg   [7:0] shift_buffer_1_7_V_reg_2284;
reg   [7:0] shift_buffer_1_8_V_reg_2290;
reg   [7:0] shift_buffer_1_9_V_reg_2296;
reg   [7:0] DataOut_V_119_reg_2302;
reg   [7:0] DataOut_V_120_reg_2308;
reg   [7:0] DataOut_V_121_reg_2314;
reg   [7:0] DataOut_V_122_reg_2320;
reg   [7:0] DataOut_V_123_reg_2326;
reg   [7:0] DataOut_V_124_reg_2332;
reg   [7:0] DataOut_V_125_reg_2338;
reg   [7:0] DataOut_V_126_reg_2344;
reg   [7:0] DataOut_V_127_reg_2350;
reg   [7:0] DataOut_V_reg_2356;
wire   [0:0] icmp_ln191_8_fu_666_p2;
reg   [0:0] icmp_ln191_8_reg_2362;
wire   [0:0] icmp_ln191_9_fu_676_p2;
reg   [0:0] icmp_ln191_9_reg_2367;
wire   [0:0] icmp_ln212_fu_682_p2;
reg   [0:0] icmp_ln212_reg_2372;
wire   [0:0] icmp_ln216_fu_706_p2;
reg   [0:0] icmp_ln216_reg_2376;
wire   [0:0] and_ln191_6_fu_940_p2;
reg   [7:0] tmp_data_0_V_reg_2384;
reg   [7:0] tmp_data_1_V_reg_2389;
reg   [7:0] tmp_data_2_V_reg_2394;
reg   [7:0] tmp_data_3_V_reg_2399;
reg   [7:0] tmp_data_4_V_reg_2404;
reg   [7:0] tmp_data_5_V_reg_2409;
reg   [7:0] tmp_data_6_V_reg_2414;
reg   [7:0] tmp_data_7_V_reg_2419;
reg   [7:0] tmp_data_8_V_reg_2424;
reg   [7:0] tmp_data_9_V_reg_2429;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg   [31:0] ap_phi_mux_storemerge_i_i_phi_fu_503_p4;
wire   [31:0] select_ln222_fu_2218_p3;
reg   [31:0] ap_phi_reg_pp0_iter2_storemerge_i_i_reg_499;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_i_reg_499;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_i_i_reg_499;
wire   [31:0] add_ln225_fu_688_p2;
wire   [31:0] select_ln227_fu_2192_p3;
wire   [31:0] add_ln220_fu_712_p2;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln191_fu_914_p2;
wire   [0:0] icmp_ln191_7_fu_924_p2;
wire   [0:0] and_ln191_5_fu_936_p2;
wire   [0:0] and_ln191_fu_930_p2;
wire   [11:0] pool_window_0_V_fu_946_p3;
wire   [11:0] pool_window_1_V_fu_958_p3;
wire   [11:0] pool_window_2_V_fu_969_p3;
wire   [11:0] pool_window_3_V_fu_981_p3;
wire   [0:0] icmp_ln1496_fu_992_p2;
wire   [0:0] icmp_ln1496_111_fu_1006_p2;
wire   [11:0] select_ln66_fu_998_p3;
wire   [11:0] select_ln66_164_fu_1020_p3;
wire   [0:0] icmp_ln1496_112_fu_1028_p2;
wire   [1:0] select_ln66_163_fu_1012_p3;
wire   [1:0] zext_ln66_fu_1034_p1;
wire   [15:0] tmp_6_fu_1046_p1;
wire   [15:0] tmp_6_fu_1046_p2;
wire   [15:0] tmp_6_fu_1046_p3;
wire   [15:0] tmp_6_fu_1046_p4;
wire   [1:0] tmp_6_fu_1046_p5;
wire   [15:0] tmp_6_fu_1046_p6;
wire   [11:0] pool_window_0_V_28_fu_1070_p3;
wire   [11:0] pool_window_1_V_28_fu_1082_p3;
wire   [11:0] pool_window_2_V_28_fu_1093_p3;
wire   [11:0] pool_window_3_V_28_fu_1105_p3;
wire   [0:0] icmp_ln1496_1_fu_1116_p2;
wire   [0:0] icmp_ln1496_113_fu_1130_p2;
wire   [11:0] select_ln66_166_fu_1122_p3;
wire   [11:0] select_ln66_168_fu_1144_p3;
wire   [0:0] icmp_ln1496_114_fu_1152_p2;
wire   [1:0] select_ln66_167_fu_1136_p3;
wire   [1:0] zext_ln66_25_fu_1158_p1;
wire   [15:0] tmp_7_fu_1170_p1;
wire   [15:0] tmp_7_fu_1170_p2;
wire   [15:0] tmp_7_fu_1170_p3;
wire   [15:0] tmp_7_fu_1170_p4;
wire   [1:0] tmp_7_fu_1170_p5;
wire   [15:0] tmp_7_fu_1170_p6;
wire   [11:0] pool_window_0_V_30_fu_1194_p3;
wire   [11:0] pool_window_1_V_30_fu_1206_p3;
wire   [11:0] pool_window_2_V_30_fu_1217_p3;
wire   [11:0] pool_window_3_V_30_fu_1229_p3;
wire   [0:0] icmp_ln1496_2_fu_1240_p2;
wire   [0:0] icmp_ln1496_115_fu_1254_p2;
wire   [11:0] select_ln66_170_fu_1246_p3;
wire   [11:0] select_ln66_172_fu_1268_p3;
wire   [0:0] icmp_ln1496_116_fu_1276_p2;
wire   [1:0] select_ln66_171_fu_1260_p3;
wire   [1:0] zext_ln66_26_fu_1282_p1;
wire   [15:0] tmp_8_fu_1294_p1;
wire   [15:0] tmp_8_fu_1294_p2;
wire   [15:0] tmp_8_fu_1294_p3;
wire   [15:0] tmp_8_fu_1294_p4;
wire   [1:0] tmp_8_fu_1294_p5;
wire   [15:0] tmp_8_fu_1294_p6;
wire   [11:0] pool_window_0_V_32_fu_1318_p3;
wire   [11:0] pool_window_1_V_32_fu_1330_p3;
wire   [11:0] pool_window_2_V_32_fu_1341_p3;
wire   [11:0] pool_window_3_V_32_fu_1353_p3;
wire   [0:0] icmp_ln1496_3_fu_1364_p2;
wire   [0:0] icmp_ln1496_117_fu_1378_p2;
wire   [11:0] select_ln66_174_fu_1370_p3;
wire   [11:0] select_ln66_176_fu_1392_p3;
wire   [0:0] icmp_ln1496_118_fu_1400_p2;
wire   [1:0] select_ln66_175_fu_1384_p3;
wire   [1:0] zext_ln66_27_fu_1406_p1;
wire   [15:0] tmp_9_fu_1418_p1;
wire   [15:0] tmp_9_fu_1418_p2;
wire   [15:0] tmp_9_fu_1418_p3;
wire   [15:0] tmp_9_fu_1418_p4;
wire   [1:0] tmp_9_fu_1418_p5;
wire   [15:0] tmp_9_fu_1418_p6;
wire   [11:0] pool_window_0_V_34_fu_1442_p3;
wire   [11:0] pool_window_1_V_34_fu_1454_p3;
wire   [11:0] pool_window_2_V_34_fu_1465_p3;
wire   [11:0] pool_window_3_V_34_fu_1477_p3;
wire   [0:0] icmp_ln1496_4_fu_1488_p2;
wire   [0:0] icmp_ln1496_119_fu_1502_p2;
wire   [11:0] select_ln66_178_fu_1494_p3;
wire   [11:0] select_ln66_180_fu_1516_p3;
wire   [0:0] icmp_ln1496_120_fu_1524_p2;
wire   [1:0] select_ln66_179_fu_1508_p3;
wire   [1:0] zext_ln66_28_fu_1530_p1;
wire   [15:0] tmp_1_fu_1542_p1;
wire   [15:0] tmp_1_fu_1542_p2;
wire   [15:0] tmp_1_fu_1542_p3;
wire   [15:0] tmp_1_fu_1542_p4;
wire   [1:0] tmp_1_fu_1542_p5;
wire   [15:0] tmp_1_fu_1542_p6;
wire   [11:0] pool_window_0_V_36_fu_1566_p3;
wire   [11:0] pool_window_1_V_36_fu_1578_p3;
wire   [11:0] pool_window_2_V_36_fu_1589_p3;
wire   [11:0] pool_window_3_V_36_fu_1601_p3;
wire   [0:0] icmp_ln1496_5_fu_1612_p2;
wire   [0:0] icmp_ln1496_121_fu_1626_p2;
wire   [11:0] select_ln66_182_fu_1618_p3;
wire   [11:0] select_ln66_184_fu_1640_p3;
wire   [0:0] icmp_ln1496_122_fu_1648_p2;
wire   [1:0] select_ln66_183_fu_1632_p3;
wire   [1:0] zext_ln66_29_fu_1654_p1;
wire   [15:0] tmp_2_fu_1666_p1;
wire   [15:0] tmp_2_fu_1666_p2;
wire   [15:0] tmp_2_fu_1666_p3;
wire   [15:0] tmp_2_fu_1666_p4;
wire   [1:0] tmp_2_fu_1666_p5;
wire   [15:0] tmp_2_fu_1666_p6;
wire   [11:0] pool_window_0_V_38_fu_1690_p3;
wire   [11:0] pool_window_1_V_38_fu_1702_p3;
wire   [11:0] pool_window_2_V_38_fu_1713_p3;
wire   [11:0] pool_window_3_V_38_fu_1725_p3;
wire   [0:0] icmp_ln1496_6_fu_1736_p2;
wire   [0:0] icmp_ln1496_123_fu_1750_p2;
wire   [11:0] select_ln66_186_fu_1742_p3;
wire   [11:0] select_ln66_188_fu_1764_p3;
wire   [0:0] icmp_ln1496_124_fu_1772_p2;
wire   [1:0] select_ln66_187_fu_1756_p3;
wire   [1:0] zext_ln66_30_fu_1778_p1;
wire   [15:0] tmp_3_fu_1790_p1;
wire   [15:0] tmp_3_fu_1790_p2;
wire   [15:0] tmp_3_fu_1790_p3;
wire   [15:0] tmp_3_fu_1790_p4;
wire   [1:0] tmp_3_fu_1790_p5;
wire   [15:0] tmp_3_fu_1790_p6;
wire   [11:0] pool_window_0_V_40_fu_1814_p3;
wire   [11:0] pool_window_1_V_40_fu_1826_p3;
wire   [11:0] pool_window_2_V_40_fu_1837_p3;
wire   [11:0] pool_window_3_V_40_fu_1849_p3;
wire   [0:0] icmp_ln1496_7_fu_1860_p2;
wire   [0:0] icmp_ln1496_125_fu_1874_p2;
wire   [11:0] select_ln66_190_fu_1866_p3;
wire   [11:0] select_ln66_192_fu_1888_p3;
wire   [0:0] icmp_ln1496_126_fu_1896_p2;
wire   [1:0] select_ln66_191_fu_1880_p3;
wire   [1:0] zext_ln66_31_fu_1902_p1;
wire   [15:0] tmp_4_fu_1914_p1;
wire   [15:0] tmp_4_fu_1914_p2;
wire   [15:0] tmp_4_fu_1914_p3;
wire   [15:0] tmp_4_fu_1914_p4;
wire   [1:0] tmp_4_fu_1914_p5;
wire   [15:0] tmp_4_fu_1914_p6;
wire   [11:0] pool_window_0_V_42_fu_1938_p3;
wire   [11:0] pool_window_1_V_42_fu_1950_p3;
wire   [11:0] pool_window_2_V_42_fu_1961_p3;
wire   [11:0] pool_window_3_V_42_fu_1973_p3;
wire   [0:0] icmp_ln1496_8_fu_1984_p2;
wire   [0:0] icmp_ln1496_127_fu_1998_p2;
wire   [11:0] select_ln66_194_fu_1990_p3;
wire   [11:0] select_ln66_196_fu_2012_p3;
wire   [0:0] icmp_ln1496_128_fu_2020_p2;
wire   [1:0] select_ln66_195_fu_2004_p3;
wire   [1:0] zext_ln66_32_fu_2026_p1;
wire   [15:0] tmp_5_fu_2038_p1;
wire   [15:0] tmp_5_fu_2038_p2;
wire   [15:0] tmp_5_fu_2038_p3;
wire   [15:0] tmp_5_fu_2038_p4;
wire   [1:0] tmp_5_fu_2038_p5;
wire   [15:0] tmp_5_fu_2038_p6;
wire   [11:0] pool_window_0_V_44_fu_2062_p3;
wire   [11:0] pool_window_1_V_44_fu_2074_p3;
wire   [11:0] pool_window_2_V_44_fu_2085_p3;
wire   [11:0] pool_window_3_V_44_fu_2097_p3;
wire   [0:0] icmp_ln1496_9_fu_2108_p2;
wire   [0:0] icmp_ln1496_129_fu_2122_p2;
wire   [11:0] select_ln66_198_fu_2114_p3;
wire   [11:0] select_ln66_200_fu_2136_p3;
wire   [0:0] icmp_ln1496_130_fu_2144_p2;
wire   [1:0] select_ln66_199_fu_2128_p3;
wire   [1:0] zext_ln66_33_fu_2150_p1;
wire   [15:0] tmp_10_fu_2162_p1;
wire   [15:0] tmp_10_fu_2162_p2;
wire   [15:0] tmp_10_fu_2162_p3;
wire   [15:0] tmp_10_fu_2162_p4;
wire   [1:0] tmp_10_fu_2162_p5;
wire   [15:0] tmp_10_fu_2162_p6;
wire   [31:0] add_ln227_fu_2186_p2;
wire   [31:0] add_ln222_fu_2212_p2;
wire    ap_CS_fsm_state6;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_419;
reg    ap_condition_416;
reg    ap_condition_1493;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 pX_2 = 32'd0;
#0 sX_2 = 32'd0;
#0 pY_2 = 32'd0;
#0 sY_2 = 32'd0;
#0 kernel_data_V_3_10 = 8'd0;
#0 kernel_data_V_3_11 = 8'd0;
#0 kernel_data_V_3_12 = 8'd0;
#0 kernel_data_V_3_13 = 8'd0;
#0 kernel_data_V_3_14 = 8'd0;
#0 kernel_data_V_3_15 = 8'd0;
#0 kernel_data_V_3_16 = 8'd0;
#0 kernel_data_V_3_17 = 8'd0;
#0 kernel_data_V_3_18 = 8'd0;
#0 kernel_data_V_3_19 = 8'd0;
#0 kernel_data_V_3_30 = 8'd0;
#0 kernel_data_V_3_31 = 8'd0;
#0 kernel_data_V_3_32 = 8'd0;
#0 kernel_data_V_3_33 = 8'd0;
#0 kernel_data_V_3_34 = 8'd0;
#0 kernel_data_V_3_35 = 8'd0;
#0 kernel_data_V_3_36 = 8'd0;
#0 kernel_data_V_3_37 = 8'd0;
#0 kernel_data_V_3_38 = 8'd0;
#0 kernel_data_V_3_39 = 8'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_0_ce0),
    .we0(line_buffer_Array_V_3_0_0_we0),
    .d0(data_V_data_0_V_dout),
    .q0(line_buffer_Array_V_3_0_0_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_1_ce0),
    .we0(line_buffer_Array_V_3_0_1_we0),
    .d0(data_V_data_1_V_dout),
    .q0(line_buffer_Array_V_3_0_1_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_2_ce0),
    .we0(line_buffer_Array_V_3_0_2_we0),
    .d0(data_V_data_2_V_dout),
    .q0(line_buffer_Array_V_3_0_2_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_3_ce0),
    .we0(line_buffer_Array_V_3_0_3_we0),
    .d0(data_V_data_3_V_dout),
    .q0(line_buffer_Array_V_3_0_3_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_4_ce0),
    .we0(line_buffer_Array_V_3_0_4_we0),
    .d0(data_V_data_4_V_dout),
    .q0(line_buffer_Array_V_3_0_4_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_5_ce0),
    .we0(line_buffer_Array_V_3_0_5_we0),
    .d0(data_V_data_5_V_dout),
    .q0(line_buffer_Array_V_3_0_5_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_6_ce0),
    .we0(line_buffer_Array_V_3_0_6_we0),
    .d0(data_V_data_6_V_dout),
    .q0(line_buffer_Array_V_3_0_6_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_7_ce0),
    .we0(line_buffer_Array_V_3_0_7_we0),
    .d0(data_V_data_7_V_dout),
    .q0(line_buffer_Array_V_3_0_7_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_8_ce0),
    .we0(line_buffer_Array_V_3_0_8_we0),
    .d0(data_V_data_8_V_dout),
    .q0(line_buffer_Array_V_3_0_8_q0)
);

pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s_line_buffer_Array6jw #(
    .DataWidth( 8 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
line_buffer_Array_V_3_0_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(1'd1),
    .ce0(line_buffer_Array_V_3_0_9_ce0),
    .we0(line_buffer_Array_V_3_0_9_we0),
    .d0(data_V_data_9_V_dout),
    .q0(line_buffer_Array_V_3_0_9_q0)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U646(
    .din0(tmp_6_fu_1046_p1),
    .din1(tmp_6_fu_1046_p2),
    .din2(tmp_6_fu_1046_p3),
    .din3(tmp_6_fu_1046_p4),
    .din4(tmp_6_fu_1046_p5),
    .dout(tmp_6_fu_1046_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U647(
    .din0(tmp_7_fu_1170_p1),
    .din1(tmp_7_fu_1170_p2),
    .din2(tmp_7_fu_1170_p3),
    .din3(tmp_7_fu_1170_p4),
    .din4(tmp_7_fu_1170_p5),
    .dout(tmp_7_fu_1170_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U648(
    .din0(tmp_8_fu_1294_p1),
    .din1(tmp_8_fu_1294_p2),
    .din2(tmp_8_fu_1294_p3),
    .din3(tmp_8_fu_1294_p4),
    .din4(tmp_8_fu_1294_p5),
    .dout(tmp_8_fu_1294_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U649(
    .din0(tmp_9_fu_1418_p1),
    .din1(tmp_9_fu_1418_p2),
    .din2(tmp_9_fu_1418_p3),
    .din3(tmp_9_fu_1418_p4),
    .din4(tmp_9_fu_1418_p5),
    .dout(tmp_9_fu_1418_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U650(
    .din0(tmp_1_fu_1542_p1),
    .din1(tmp_1_fu_1542_p2),
    .din2(tmp_1_fu_1542_p3),
    .din3(tmp_1_fu_1542_p4),
    .din4(tmp_1_fu_1542_p5),
    .dout(tmp_1_fu_1542_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U651(
    .din0(tmp_2_fu_1666_p1),
    .din1(tmp_2_fu_1666_p2),
    .din2(tmp_2_fu_1666_p3),
    .din3(tmp_2_fu_1666_p4),
    .din4(tmp_2_fu_1666_p5),
    .dout(tmp_2_fu_1666_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U652(
    .din0(tmp_3_fu_1790_p1),
    .din1(tmp_3_fu_1790_p2),
    .din2(tmp_3_fu_1790_p3),
    .din3(tmp_3_fu_1790_p4),
    .din4(tmp_3_fu_1790_p5),
    .dout(tmp_3_fu_1790_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U653(
    .din0(tmp_4_fu_1914_p1),
    .din1(tmp_4_fu_1914_p2),
    .din2(tmp_4_fu_1914_p3),
    .din3(tmp_4_fu_1914_p4),
    .din4(tmp_4_fu_1914_p5),
    .dout(tmp_4_fu_1914_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U654(
    .din0(tmp_5_fu_2038_p1),
    .din1(tmp_5_fu_2038_p2),
    .din2(tmp_5_fu_2038_p3),
    .din3(tmp_5_fu_2038_p4),
    .din4(tmp_5_fu_2038_p5),
    .dout(tmp_5_fu_2038_p6)
);

myproject_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_mux_42_16_1_1_U655(
    .din0(tmp_10_fu_2162_p1),
    .din1(tmp_10_fu_2162_p2),
    .din2(tmp_10_fu_2162_p3),
    .din3(tmp_10_fu_2162_p4),
    .din4(tmp_10_fu_2162_p5),
    .dout(tmp_10_fu_2162_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_416)) begin
        if ((1'b1 == ap_condition_419)) begin
            ap_phi_reg_pp0_iter2_storemerge_i_i_reg_499 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_storemerge_i_i_reg_499 <= ap_phi_reg_pp0_iter1_storemerge_i_i_reg_499;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_fu_510_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_488 <= add_ln241_fu_516_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_488 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_416)) begin
        if ((icmp_ln212_fu_682_p2 == 1'd1)) begin
            pX_2 <= 32'd0;
        end else if ((icmp_ln212_fu_682_p2 == 1'd0)) begin
            pX_2 <= add_ln225_fu_688_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_1493)) begin
        if ((icmp_ln216_fu_706_p2 == 1'd1)) begin
            pY_2 <= 32'd0;
        end else if ((icmp_ln216_fu_706_p2 == 1'd0)) begin
            pY_2 <= add_ln220_fu_712_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln212_reg_2372 == 1'd1)) begin
            sX_2 <= 32'd0;
        end else if ((icmp_ln212_reg_2372 == 1'd0)) begin
            sX_2 <= select_ln227_fu_2192_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        DataOut_V_119_reg_2302 <= line_buffer_Array_V_3_0_0_q0;
        DataOut_V_120_reg_2308 <= line_buffer_Array_V_3_0_1_q0;
        DataOut_V_121_reg_2314 <= line_buffer_Array_V_3_0_2_q0;
        DataOut_V_122_reg_2320 <= line_buffer_Array_V_3_0_3_q0;
        DataOut_V_123_reg_2326 <= line_buffer_Array_V_3_0_4_q0;
        DataOut_V_124_reg_2332 <= line_buffer_Array_V_3_0_5_q0;
        DataOut_V_125_reg_2338 <= line_buffer_Array_V_3_0_6_q0;
        DataOut_V_126_reg_2344 <= line_buffer_Array_V_3_0_7_q0;
        DataOut_V_127_reg_2350 <= line_buffer_Array_V_3_0_8_q0;
        DataOut_V_reg_2356 <= line_buffer_Array_V_3_0_9_q0;
        icmp_ln191_8_reg_2362 <= icmp_ln191_8_fu_666_p2;
        icmp_ln191_9_reg_2367 <= icmp_ln191_9_fu_676_p2;
        shift_buffer_1_0_V_reg_2242 <= data_V_data_0_V_dout;
        shift_buffer_1_1_V_reg_2248 <= data_V_data_1_V_dout;
        shift_buffer_1_2_V_reg_2254 <= data_V_data_2_V_dout;
        shift_buffer_1_3_V_reg_2260 <= data_V_data_3_V_dout;
        shift_buffer_1_4_V_reg_2266 <= data_V_data_4_V_dout;
        shift_buffer_1_5_V_reg_2272 <= data_V_data_5_V_dout;
        shift_buffer_1_6_V_reg_2278 <= data_V_data_6_V_dout;
        shift_buffer_1_7_V_reg_2284 <= data_V_data_7_V_dout;
        shift_buffer_1_8_V_reg_2290 <= data_V_data_8_V_dout;
        shift_buffer_1_9_V_reg_2296 <= data_V_data_9_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233_pp0_iter1_reg == 1'd0))) begin
        and_ln191_6_reg_2380 <= and_ln191_6_fu_940_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_storemerge_i_i_reg_499 <= ap_phi_reg_pp0_iter0_storemerge_i_i_reg_499;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln212_reg_2372 <= icmp_ln212_fu_682_p2;
        icmp_ln241_reg_2233 <= icmp_ln241_fu_510_p2;
        icmp_ln241_reg_2233_pp0_iter1_reg <= icmp_ln241_reg_2233;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln212_fu_682_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln216_reg_2376 <= icmp_ln216_fu_706_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        kernel_data_V_3_10 <= DataOut_V_119_reg_2302;
        kernel_data_V_3_11 <= DataOut_V_120_reg_2308;
        kernel_data_V_3_12 <= DataOut_V_121_reg_2314;
        kernel_data_V_3_13 <= DataOut_V_122_reg_2320;
        kernel_data_V_3_14 <= DataOut_V_123_reg_2326;
        kernel_data_V_3_15 <= DataOut_V_124_reg_2332;
        kernel_data_V_3_16 <= DataOut_V_125_reg_2338;
        kernel_data_V_3_17 <= DataOut_V_126_reg_2344;
        kernel_data_V_3_18 <= DataOut_V_127_reg_2350;
        kernel_data_V_3_19 <= DataOut_V_reg_2356;
        kernel_data_V_3_30 <= shift_buffer_1_0_V_reg_2242;
        kernel_data_V_3_31 <= shift_buffer_1_1_V_reg_2248;
        kernel_data_V_3_32 <= shift_buffer_1_2_V_reg_2254;
        kernel_data_V_3_33 <= shift_buffer_1_3_V_reg_2260;
        kernel_data_V_3_34 <= shift_buffer_1_4_V_reg_2266;
        kernel_data_V_3_35 <= shift_buffer_1_5_V_reg_2272;
        kernel_data_V_3_36 <= shift_buffer_1_6_V_reg_2278;
        kernel_data_V_3_37 <= shift_buffer_1_7_V_reg_2284;
        kernel_data_V_3_38 <= shift_buffer_1_8_V_reg_2290;
        kernel_data_V_3_39 <= shift_buffer_1_9_V_reg_2296;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln212_reg_2372 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        sY_2 <= ap_phi_mux_storemerge_i_i_phi_fu_503_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_fu_940_p2))) begin
        tmp_data_0_V_reg_2384 <= {{tmp_6_fu_1046_p6[11:4]}};
        tmp_data_1_V_reg_2389 <= {{tmp_7_fu_1170_p6[11:4]}};
        tmp_data_2_V_reg_2394 <= {{tmp_8_fu_1294_p6[11:4]}};
        tmp_data_3_V_reg_2399 <= {{tmp_9_fu_1418_p6[11:4]}};
        tmp_data_4_V_reg_2404 <= {{tmp_1_fu_1542_p6[11:4]}};
        tmp_data_5_V_reg_2409 <= {{tmp_2_fu_1666_p6[11:4]}};
        tmp_data_6_V_reg_2414 <= {{tmp_3_fu_1790_p6[11:4]}};
        tmp_data_7_V_reg_2419 <= {{tmp_4_fu_1914_p6[11:4]}};
        tmp_data_8_V_reg_2424 <= {{tmp_5_fu_2038_p6[11:4]}};
        tmp_data_9_V_reg_2429 <= {{tmp_10_fu_2162_p6[11:4]}};
    end
end

always @ (*) begin
    if ((icmp_ln241_fu_510_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln212_reg_2372 == 1'd1) & (icmp_ln216_reg_2376 == 1'd0) & (icmp_ln241_reg_2233_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_storemerge_i_i_phi_fu_503_p4 = select_ln222_fu_2218_p3;
    end else begin
        ap_phi_mux_storemerge_i_i_phi_fu_503_p4 = ap_phi_reg_pp0_iter2_storemerge_i_i_reg_499;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_0_V_blk_n = data_V_data_0_V_empty_n;
    end else begin
        data_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_0_V_read = 1'b1;
    end else begin
        data_V_data_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_1_V_blk_n = data_V_data_1_V_empty_n;
    end else begin
        data_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_1_V_read = 1'b1;
    end else begin
        data_V_data_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_2_V_blk_n = data_V_data_2_V_empty_n;
    end else begin
        data_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_2_V_read = 1'b1;
    end else begin
        data_V_data_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_3_V_blk_n = data_V_data_3_V_empty_n;
    end else begin
        data_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_3_V_read = 1'b1;
    end else begin
        data_V_data_3_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_4_V_blk_n = data_V_data_4_V_empty_n;
    end else begin
        data_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_4_V_read = 1'b1;
    end else begin
        data_V_data_4_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_5_V_blk_n = data_V_data_5_V_empty_n;
    end else begin
        data_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_5_V_read = 1'b1;
    end else begin
        data_V_data_5_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_6_V_blk_n = data_V_data_6_V_empty_n;
    end else begin
        data_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_6_V_read = 1'b1;
    end else begin
        data_V_data_6_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_7_V_blk_n = data_V_data_7_V_empty_n;
    end else begin
        data_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_7_V_read = 1'b1;
    end else begin
        data_V_data_7_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_8_V_blk_n = data_V_data_8_V_empty_n;
    end else begin
        data_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_8_V_read = 1'b1;
    end else begin
        data_V_data_8_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln241_reg_2233 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_9_V_blk_n = data_V_data_9_V_empty_n;
    end else begin
        data_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_V_data_9_V_read = 1'b1;
    end else begin
        data_V_data_9_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_0_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_0_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_1_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_1_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_2_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_2_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_3_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_3_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_4_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_4_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_5_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_5_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_6_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_6_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_7_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_7_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_8_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_8_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_9_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buffer_Array_V_3_0_9_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_3_0_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n;
    end else begin
        res_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_4_V_write = 1'b1;
    end else begin
        res_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n;
    end else begin
        res_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_5_V_write = 1'b1;
    end else begin
        res_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n;
    end else begin
        res_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_6_V_write = 1'b1;
    end else begin
        res_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n;
    end else begin
        res_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_7_V_write = 1'b1;
    end else begin
        res_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_8_V_blk_n = res_V_data_8_V_full_n;
    end else begin
        res_V_data_8_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_8_V_write = 1'b1;
    end else begin
        res_V_data_8_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln191_6_reg_2380) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_9_V_blk_n = res_V_data_9_V_full_n;
    end else begin
        res_V_data_9_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_V_data_9_V_write = 1'b1;
    end else begin
        res_V_data_9_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln241_fu_510_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln241_fu_510_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln220_fu_712_p2 = (pY_2 + 32'd1);

assign add_ln222_fu_2212_p2 = (sY_2 + 32'd1);

assign add_ln225_fu_688_p2 = (pX_2 + 32'd1);

assign add_ln227_fu_2186_p2 = (sX_2 + 32'd1);

assign add_ln241_fu_516_p2 = (indvar_flatten_reg_488 + 3'd1);

assign and_ln191_5_fu_936_p2 = (icmp_ln191_9_reg_2367 & icmp_ln191_8_reg_2362);

assign and_ln191_6_fu_940_p2 = (and_ln191_fu_930_p2 & and_ln191_5_fu_936_p2);

assign and_ln191_fu_930_p2 = (icmp_ln191_fu_914_p2 & icmp_ln191_7_fu_924_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((io_acc_block_signal_op314 == 1'b0) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((io_acc_block_signal_op33 == 1'b0) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((io_acc_block_signal_op314 == 1'b0) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((io_acc_block_signal_op33 == 1'b0) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((io_acc_block_signal_op314 == 1'b0) & (1'd1 == and_ln191_6_reg_2380) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((io_acc_block_signal_op33 == 1'b0) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((io_acc_block_signal_op33 == 1'b0) & (icmp_ln241_reg_2233 == 1'd0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = ((io_acc_block_signal_op314 == 1'b0) & (1'd1 == and_ln191_6_reg_2380));
end

always @ (*) begin
    ap_condition_1493 = ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln212_fu_682_p2 == 1'd1) & (icmp_ln241_reg_2233 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_416 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_419 = ((icmp_ln216_fu_706_p2 == 1'd1) & (icmp_ln212_fu_682_p2 == 1'd1) & (icmp_ln241_reg_2233 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_i_i_reg_499 = 'bx;

assign ap_ready = internal_ap_ready;

assign icmp_ln1496_111_fu_1006_p2 = ((pool_window_2_V_fu_969_p3 < pool_window_3_V_fu_981_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_112_fu_1028_p2 = ((select_ln66_fu_998_p3 < select_ln66_164_fu_1020_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_113_fu_1130_p2 = ((pool_window_2_V_28_fu_1093_p3 < pool_window_3_V_28_fu_1105_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_114_fu_1152_p2 = ((select_ln66_166_fu_1122_p3 < select_ln66_168_fu_1144_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_115_fu_1254_p2 = ((pool_window_2_V_30_fu_1217_p3 < pool_window_3_V_30_fu_1229_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_116_fu_1276_p2 = ((select_ln66_170_fu_1246_p3 < select_ln66_172_fu_1268_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_117_fu_1378_p2 = ((pool_window_2_V_32_fu_1341_p3 < pool_window_3_V_32_fu_1353_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_118_fu_1400_p2 = ((select_ln66_174_fu_1370_p3 < select_ln66_176_fu_1392_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_119_fu_1502_p2 = ((pool_window_2_V_34_fu_1465_p3 < pool_window_3_V_34_fu_1477_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_120_fu_1524_p2 = ((select_ln66_178_fu_1494_p3 < select_ln66_180_fu_1516_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_121_fu_1626_p2 = ((pool_window_2_V_36_fu_1589_p3 < pool_window_3_V_36_fu_1601_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_122_fu_1648_p2 = ((select_ln66_182_fu_1618_p3 < select_ln66_184_fu_1640_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_123_fu_1750_p2 = ((pool_window_2_V_38_fu_1713_p3 < pool_window_3_V_38_fu_1725_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_124_fu_1772_p2 = ((select_ln66_186_fu_1742_p3 < select_ln66_188_fu_1764_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_125_fu_1874_p2 = ((pool_window_2_V_40_fu_1837_p3 < pool_window_3_V_40_fu_1849_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_126_fu_1896_p2 = ((select_ln66_190_fu_1866_p3 < select_ln66_192_fu_1888_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_127_fu_1998_p2 = ((pool_window_2_V_42_fu_1961_p3 < pool_window_3_V_42_fu_1973_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_128_fu_2020_p2 = ((select_ln66_194_fu_1990_p3 < select_ln66_196_fu_2012_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_129_fu_2122_p2 = ((pool_window_2_V_44_fu_2085_p3 < pool_window_3_V_44_fu_2097_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_130_fu_2144_p2 = ((select_ln66_198_fu_2114_p3 < select_ln66_200_fu_2136_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_1_fu_1116_p2 = ((pool_window_0_V_28_fu_1070_p3 < pool_window_1_V_28_fu_1082_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_2_fu_1240_p2 = ((pool_window_0_V_30_fu_1194_p3 < pool_window_1_V_30_fu_1206_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_3_fu_1364_p2 = ((pool_window_0_V_32_fu_1318_p3 < pool_window_1_V_32_fu_1330_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_4_fu_1488_p2 = ((pool_window_0_V_34_fu_1442_p3 < pool_window_1_V_34_fu_1454_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_5_fu_1612_p2 = ((pool_window_0_V_36_fu_1566_p3 < pool_window_1_V_36_fu_1578_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_6_fu_1736_p2 = ((pool_window_0_V_38_fu_1690_p3 < pool_window_1_V_38_fu_1702_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_7_fu_1860_p2 = ((pool_window_0_V_40_fu_1814_p3 < pool_window_1_V_40_fu_1826_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_8_fu_1984_p2 = ((pool_window_0_V_42_fu_1938_p3 < pool_window_1_V_42_fu_1950_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_9_fu_2108_p2 = ((pool_window_0_V_44_fu_2062_p3 < pool_window_1_V_44_fu_2074_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_992_p2 = ((pool_window_0_V_fu_946_p3 < pool_window_1_V_fu_958_p3) ? 1'b1 : 1'b0);

assign icmp_ln191_7_fu_924_p2 = ((sY_2 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln191_8_fu_666_p2 = (($signed(pY_2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln191_9_fu_676_p2 = (($signed(pX_2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln191_fu_914_p2 = ((sX_2 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln212_fu_682_p2 = ((pX_2 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln216_fu_706_p2 = ((pY_2 == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln241_fu_510_p2 = ((indvar_flatten_reg_488 == 3'd4) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op314 = (res_V_data_9_V_full_n & res_V_data_8_V_full_n & res_V_data_7_V_full_n & res_V_data_6_V_full_n & res_V_data_5_V_full_n & res_V_data_4_V_full_n & res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign io_acc_block_signal_op33 = (data_V_data_9_V_empty_n & data_V_data_8_V_empty_n & data_V_data_7_V_empty_n & data_V_data_6_V_empty_n & data_V_data_5_V_empty_n & data_V_data_4_V_empty_n & data_V_data_3_V_empty_n & data_V_data_2_V_empty_n & data_V_data_1_V_empty_n & data_V_data_0_V_empty_n);

assign pool_window_0_V_28_fu_1070_p3 = {{kernel_data_V_3_11}, {4'd0}};

assign pool_window_0_V_30_fu_1194_p3 = {{kernel_data_V_3_12}, {4'd0}};

assign pool_window_0_V_32_fu_1318_p3 = {{kernel_data_V_3_13}, {4'd0}};

assign pool_window_0_V_34_fu_1442_p3 = {{kernel_data_V_3_14}, {4'd0}};

assign pool_window_0_V_36_fu_1566_p3 = {{kernel_data_V_3_15}, {4'd0}};

assign pool_window_0_V_38_fu_1690_p3 = {{kernel_data_V_3_16}, {4'd0}};

assign pool_window_0_V_40_fu_1814_p3 = {{kernel_data_V_3_17}, {4'd0}};

assign pool_window_0_V_42_fu_1938_p3 = {{kernel_data_V_3_18}, {4'd0}};

assign pool_window_0_V_44_fu_2062_p3 = {{kernel_data_V_3_19}, {4'd0}};

assign pool_window_0_V_fu_946_p3 = {{kernel_data_V_3_10}, {4'd0}};

assign pool_window_1_V_28_fu_1082_p3 = {{DataOut_V_120_reg_2308}, {4'd0}};

assign pool_window_1_V_30_fu_1206_p3 = {{DataOut_V_121_reg_2314}, {4'd0}};

assign pool_window_1_V_32_fu_1330_p3 = {{DataOut_V_122_reg_2320}, {4'd0}};

assign pool_window_1_V_34_fu_1454_p3 = {{DataOut_V_123_reg_2326}, {4'd0}};

assign pool_window_1_V_36_fu_1578_p3 = {{DataOut_V_124_reg_2332}, {4'd0}};

assign pool_window_1_V_38_fu_1702_p3 = {{DataOut_V_125_reg_2338}, {4'd0}};

assign pool_window_1_V_40_fu_1826_p3 = {{DataOut_V_126_reg_2344}, {4'd0}};

assign pool_window_1_V_42_fu_1950_p3 = {{DataOut_V_127_reg_2350}, {4'd0}};

assign pool_window_1_V_44_fu_2074_p3 = {{DataOut_V_reg_2356}, {4'd0}};

assign pool_window_1_V_fu_958_p3 = {{DataOut_V_119_reg_2302}, {4'd0}};

assign pool_window_2_V_28_fu_1093_p3 = {{kernel_data_V_3_31}, {4'd0}};

assign pool_window_2_V_30_fu_1217_p3 = {{kernel_data_V_3_32}, {4'd0}};

assign pool_window_2_V_32_fu_1341_p3 = {{kernel_data_V_3_33}, {4'd0}};

assign pool_window_2_V_34_fu_1465_p3 = {{kernel_data_V_3_34}, {4'd0}};

assign pool_window_2_V_36_fu_1589_p3 = {{kernel_data_V_3_35}, {4'd0}};

assign pool_window_2_V_38_fu_1713_p3 = {{kernel_data_V_3_36}, {4'd0}};

assign pool_window_2_V_40_fu_1837_p3 = {{kernel_data_V_3_37}, {4'd0}};

assign pool_window_2_V_42_fu_1961_p3 = {{kernel_data_V_3_38}, {4'd0}};

assign pool_window_2_V_44_fu_2085_p3 = {{kernel_data_V_3_39}, {4'd0}};

assign pool_window_2_V_fu_969_p3 = {{kernel_data_V_3_30}, {4'd0}};

assign pool_window_3_V_28_fu_1105_p3 = {{shift_buffer_1_1_V_reg_2248}, {4'd0}};

assign pool_window_3_V_30_fu_1229_p3 = {{shift_buffer_1_2_V_reg_2254}, {4'd0}};

assign pool_window_3_V_32_fu_1353_p3 = {{shift_buffer_1_3_V_reg_2260}, {4'd0}};

assign pool_window_3_V_34_fu_1477_p3 = {{shift_buffer_1_4_V_reg_2266}, {4'd0}};

assign pool_window_3_V_36_fu_1601_p3 = {{shift_buffer_1_5_V_reg_2272}, {4'd0}};

assign pool_window_3_V_38_fu_1725_p3 = {{shift_buffer_1_6_V_reg_2278}, {4'd0}};

assign pool_window_3_V_40_fu_1849_p3 = {{shift_buffer_1_7_V_reg_2284}, {4'd0}};

assign pool_window_3_V_42_fu_1973_p3 = {{shift_buffer_1_8_V_reg_2290}, {4'd0}};

assign pool_window_3_V_44_fu_2097_p3 = {{shift_buffer_1_9_V_reg_2296}, {4'd0}};

assign pool_window_3_V_fu_981_p3 = {{shift_buffer_1_0_V_reg_2242}, {4'd0}};

assign res_V_data_0_V_din = tmp_data_0_V_reg_2384;

assign res_V_data_1_V_din = tmp_data_1_V_reg_2389;

assign res_V_data_2_V_din = tmp_data_2_V_reg_2394;

assign res_V_data_3_V_din = tmp_data_3_V_reg_2399;

assign res_V_data_4_V_din = tmp_data_4_V_reg_2404;

assign res_V_data_5_V_din = tmp_data_5_V_reg_2409;

assign res_V_data_6_V_din = tmp_data_6_V_reg_2414;

assign res_V_data_7_V_din = tmp_data_7_V_reg_2419;

assign res_V_data_8_V_din = tmp_data_8_V_reg_2424;

assign res_V_data_9_V_din = tmp_data_9_V_reg_2429;

assign select_ln222_fu_2218_p3 = ((icmp_ln191_7_fu_924_p2[0:0] === 1'b1) ? 32'd0 : add_ln222_fu_2212_p2);

assign select_ln227_fu_2192_p3 = ((icmp_ln191_fu_914_p2[0:0] === 1'b1) ? 32'd0 : add_ln227_fu_2186_p2);

assign select_ln66_163_fu_1012_p3 = ((icmp_ln1496_111_fu_1006_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_164_fu_1020_p3 = ((icmp_ln1496_111_fu_1006_p2[0:0] === 1'b1) ? pool_window_3_V_fu_981_p3 : pool_window_2_V_fu_969_p3);

assign select_ln66_166_fu_1122_p3 = ((icmp_ln1496_1_fu_1116_p2[0:0] === 1'b1) ? pool_window_1_V_28_fu_1082_p3 : pool_window_0_V_28_fu_1070_p3);

assign select_ln66_167_fu_1136_p3 = ((icmp_ln1496_113_fu_1130_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_168_fu_1144_p3 = ((icmp_ln1496_113_fu_1130_p2[0:0] === 1'b1) ? pool_window_3_V_28_fu_1105_p3 : pool_window_2_V_28_fu_1093_p3);

assign select_ln66_170_fu_1246_p3 = ((icmp_ln1496_2_fu_1240_p2[0:0] === 1'b1) ? pool_window_1_V_30_fu_1206_p3 : pool_window_0_V_30_fu_1194_p3);

assign select_ln66_171_fu_1260_p3 = ((icmp_ln1496_115_fu_1254_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_172_fu_1268_p3 = ((icmp_ln1496_115_fu_1254_p2[0:0] === 1'b1) ? pool_window_3_V_30_fu_1229_p3 : pool_window_2_V_30_fu_1217_p3);

assign select_ln66_174_fu_1370_p3 = ((icmp_ln1496_3_fu_1364_p2[0:0] === 1'b1) ? pool_window_1_V_32_fu_1330_p3 : pool_window_0_V_32_fu_1318_p3);

assign select_ln66_175_fu_1384_p3 = ((icmp_ln1496_117_fu_1378_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_176_fu_1392_p3 = ((icmp_ln1496_117_fu_1378_p2[0:0] === 1'b1) ? pool_window_3_V_32_fu_1353_p3 : pool_window_2_V_32_fu_1341_p3);

assign select_ln66_178_fu_1494_p3 = ((icmp_ln1496_4_fu_1488_p2[0:0] === 1'b1) ? pool_window_1_V_34_fu_1454_p3 : pool_window_0_V_34_fu_1442_p3);

assign select_ln66_179_fu_1508_p3 = ((icmp_ln1496_119_fu_1502_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_180_fu_1516_p3 = ((icmp_ln1496_119_fu_1502_p2[0:0] === 1'b1) ? pool_window_3_V_34_fu_1477_p3 : pool_window_2_V_34_fu_1465_p3);

assign select_ln66_182_fu_1618_p3 = ((icmp_ln1496_5_fu_1612_p2[0:0] === 1'b1) ? pool_window_1_V_36_fu_1578_p3 : pool_window_0_V_36_fu_1566_p3);

assign select_ln66_183_fu_1632_p3 = ((icmp_ln1496_121_fu_1626_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_184_fu_1640_p3 = ((icmp_ln1496_121_fu_1626_p2[0:0] === 1'b1) ? pool_window_3_V_36_fu_1601_p3 : pool_window_2_V_36_fu_1589_p3);

assign select_ln66_186_fu_1742_p3 = ((icmp_ln1496_6_fu_1736_p2[0:0] === 1'b1) ? pool_window_1_V_38_fu_1702_p3 : pool_window_0_V_38_fu_1690_p3);

assign select_ln66_187_fu_1756_p3 = ((icmp_ln1496_123_fu_1750_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_188_fu_1764_p3 = ((icmp_ln1496_123_fu_1750_p2[0:0] === 1'b1) ? pool_window_3_V_38_fu_1725_p3 : pool_window_2_V_38_fu_1713_p3);

assign select_ln66_190_fu_1866_p3 = ((icmp_ln1496_7_fu_1860_p2[0:0] === 1'b1) ? pool_window_1_V_40_fu_1826_p3 : pool_window_0_V_40_fu_1814_p3);

assign select_ln66_191_fu_1880_p3 = ((icmp_ln1496_125_fu_1874_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_192_fu_1888_p3 = ((icmp_ln1496_125_fu_1874_p2[0:0] === 1'b1) ? pool_window_3_V_40_fu_1849_p3 : pool_window_2_V_40_fu_1837_p3);

assign select_ln66_194_fu_1990_p3 = ((icmp_ln1496_8_fu_1984_p2[0:0] === 1'b1) ? pool_window_1_V_42_fu_1950_p3 : pool_window_0_V_42_fu_1938_p3);

assign select_ln66_195_fu_2004_p3 = ((icmp_ln1496_127_fu_1998_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_196_fu_2012_p3 = ((icmp_ln1496_127_fu_1998_p2[0:0] === 1'b1) ? pool_window_3_V_42_fu_1973_p3 : pool_window_2_V_42_fu_1961_p3);

assign select_ln66_198_fu_2114_p3 = ((icmp_ln1496_9_fu_2108_p2[0:0] === 1'b1) ? pool_window_1_V_44_fu_2074_p3 : pool_window_0_V_44_fu_2062_p3);

assign select_ln66_199_fu_2128_p3 = ((icmp_ln1496_129_fu_2122_p2[0:0] === 1'b1) ? 2'd3 : 2'd2);

assign select_ln66_200_fu_2136_p3 = ((icmp_ln1496_129_fu_2122_p2[0:0] === 1'b1) ? pool_window_3_V_44_fu_2097_p3 : pool_window_2_V_44_fu_2085_p3);

assign select_ln66_fu_998_p3 = ((icmp_ln1496_fu_992_p2[0:0] === 1'b1) ? pool_window_1_V_fu_958_p3 : pool_window_0_V_fu_946_p3);

assign start_out = real_start;

assign tmp_10_fu_2162_p1 = pool_window_0_V_44_fu_2062_p3;

assign tmp_10_fu_2162_p2 = pool_window_1_V_44_fu_2074_p3;

assign tmp_10_fu_2162_p3 = pool_window_2_V_44_fu_2085_p3;

assign tmp_10_fu_2162_p4 = pool_window_3_V_44_fu_2097_p3;

assign tmp_10_fu_2162_p5 = ((icmp_ln1496_130_fu_2144_p2[0:0] === 1'b1) ? select_ln66_199_fu_2128_p3 : zext_ln66_33_fu_2150_p1);

assign tmp_1_fu_1542_p1 = pool_window_0_V_34_fu_1442_p3;

assign tmp_1_fu_1542_p2 = pool_window_1_V_34_fu_1454_p3;

assign tmp_1_fu_1542_p3 = pool_window_2_V_34_fu_1465_p3;

assign tmp_1_fu_1542_p4 = pool_window_3_V_34_fu_1477_p3;

assign tmp_1_fu_1542_p5 = ((icmp_ln1496_120_fu_1524_p2[0:0] === 1'b1) ? select_ln66_179_fu_1508_p3 : zext_ln66_28_fu_1530_p1);

assign tmp_2_fu_1666_p1 = pool_window_0_V_36_fu_1566_p3;

assign tmp_2_fu_1666_p2 = pool_window_1_V_36_fu_1578_p3;

assign tmp_2_fu_1666_p3 = pool_window_2_V_36_fu_1589_p3;

assign tmp_2_fu_1666_p4 = pool_window_3_V_36_fu_1601_p3;

assign tmp_2_fu_1666_p5 = ((icmp_ln1496_122_fu_1648_p2[0:0] === 1'b1) ? select_ln66_183_fu_1632_p3 : zext_ln66_29_fu_1654_p1);

assign tmp_3_fu_1790_p1 = pool_window_0_V_38_fu_1690_p3;

assign tmp_3_fu_1790_p2 = pool_window_1_V_38_fu_1702_p3;

assign tmp_3_fu_1790_p3 = pool_window_2_V_38_fu_1713_p3;

assign tmp_3_fu_1790_p4 = pool_window_3_V_38_fu_1725_p3;

assign tmp_3_fu_1790_p5 = ((icmp_ln1496_124_fu_1772_p2[0:0] === 1'b1) ? select_ln66_187_fu_1756_p3 : zext_ln66_30_fu_1778_p1);

assign tmp_4_fu_1914_p1 = pool_window_0_V_40_fu_1814_p3;

assign tmp_4_fu_1914_p2 = pool_window_1_V_40_fu_1826_p3;

assign tmp_4_fu_1914_p3 = pool_window_2_V_40_fu_1837_p3;

assign tmp_4_fu_1914_p4 = pool_window_3_V_40_fu_1849_p3;

assign tmp_4_fu_1914_p5 = ((icmp_ln1496_126_fu_1896_p2[0:0] === 1'b1) ? select_ln66_191_fu_1880_p3 : zext_ln66_31_fu_1902_p1);

assign tmp_5_fu_2038_p1 = pool_window_0_V_42_fu_1938_p3;

assign tmp_5_fu_2038_p2 = pool_window_1_V_42_fu_1950_p3;

assign tmp_5_fu_2038_p3 = pool_window_2_V_42_fu_1961_p3;

assign tmp_5_fu_2038_p4 = pool_window_3_V_42_fu_1973_p3;

assign tmp_5_fu_2038_p5 = ((icmp_ln1496_128_fu_2020_p2[0:0] === 1'b1) ? select_ln66_195_fu_2004_p3 : zext_ln66_32_fu_2026_p1);

assign tmp_6_fu_1046_p1 = pool_window_0_V_fu_946_p3;

assign tmp_6_fu_1046_p2 = pool_window_1_V_fu_958_p3;

assign tmp_6_fu_1046_p3 = pool_window_2_V_fu_969_p3;

assign tmp_6_fu_1046_p4 = pool_window_3_V_fu_981_p3;

assign tmp_6_fu_1046_p5 = ((icmp_ln1496_112_fu_1028_p2[0:0] === 1'b1) ? select_ln66_163_fu_1012_p3 : zext_ln66_fu_1034_p1);

assign tmp_7_fu_1170_p1 = pool_window_0_V_28_fu_1070_p3;

assign tmp_7_fu_1170_p2 = pool_window_1_V_28_fu_1082_p3;

assign tmp_7_fu_1170_p3 = pool_window_2_V_28_fu_1093_p3;

assign tmp_7_fu_1170_p4 = pool_window_3_V_28_fu_1105_p3;

assign tmp_7_fu_1170_p5 = ((icmp_ln1496_114_fu_1152_p2[0:0] === 1'b1) ? select_ln66_167_fu_1136_p3 : zext_ln66_25_fu_1158_p1);

assign tmp_8_fu_1294_p1 = pool_window_0_V_30_fu_1194_p3;

assign tmp_8_fu_1294_p2 = pool_window_1_V_30_fu_1206_p3;

assign tmp_8_fu_1294_p3 = pool_window_2_V_30_fu_1217_p3;

assign tmp_8_fu_1294_p4 = pool_window_3_V_30_fu_1229_p3;

assign tmp_8_fu_1294_p5 = ((icmp_ln1496_116_fu_1276_p2[0:0] === 1'b1) ? select_ln66_171_fu_1260_p3 : zext_ln66_26_fu_1282_p1);

assign tmp_9_fu_1418_p1 = pool_window_0_V_32_fu_1318_p3;

assign tmp_9_fu_1418_p2 = pool_window_1_V_32_fu_1330_p3;

assign tmp_9_fu_1418_p3 = pool_window_2_V_32_fu_1341_p3;

assign tmp_9_fu_1418_p4 = pool_window_3_V_32_fu_1353_p3;

assign tmp_9_fu_1418_p5 = ((icmp_ln1496_118_fu_1400_p2[0:0] === 1'b1) ? select_ln66_175_fu_1384_p3 : zext_ln66_27_fu_1406_p1);

assign zext_ln66_25_fu_1158_p1 = icmp_ln1496_1_fu_1116_p2;

assign zext_ln66_26_fu_1282_p1 = icmp_ln1496_2_fu_1240_p2;

assign zext_ln66_27_fu_1406_p1 = icmp_ln1496_3_fu_1364_p2;

assign zext_ln66_28_fu_1530_p1 = icmp_ln1496_4_fu_1488_p2;

assign zext_ln66_29_fu_1654_p1 = icmp_ln1496_5_fu_1612_p2;

assign zext_ln66_30_fu_1778_p1 = icmp_ln1496_6_fu_1736_p2;

assign zext_ln66_31_fu_1902_p1 = icmp_ln1496_7_fu_1860_p2;

assign zext_ln66_32_fu_2026_p1 = icmp_ln1496_8_fu_1984_p2;

assign zext_ln66_33_fu_2150_p1 = icmp_ln1496_9_fu_2108_p2;

assign zext_ln66_fu_1034_p1 = icmp_ln1496_fu_992_p2;

endmodule //pooling2d_cl_array_array_ap_ufixed_8_2_5_3_0_10u_config13_s
