// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_wrapper_ap_ufixed_8_2_5_3_0_ap_fixed_8_2_5_3_0_config21_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] data_0_V_read;
input  [7:0] data_1_V_read;
input  [7:0] data_2_V_read;
input  [7:0] data_3_V_read;
input  [7:0] data_4_V_read;
input  [7:0] data_5_V_read;
input  [7:0] data_6_V_read;
input  [7:0] data_7_V_read;
input  [7:0] data_8_V_read;
input  [7:0] data_9_V_read;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;
reg[7:0] ap_return_3;
reg[7:0] ap_return_4;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln46_fu_559_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [3:0] w21_V_address0;
reg    w21_V_ce0;
wire   [37:0] w21_V_q0;
reg   [0:0] do_init_reg_187;
reg   [3:0] w_index15_reg_203;
reg   [7:0] data_0_V_read16_rewind_reg_218;
reg   [7:0] data_1_V_read17_rewind_reg_232;
reg   [7:0] data_2_V_read18_rewind_reg_246;
reg   [7:0] data_3_V_read19_rewind_reg_260;
reg   [7:0] data_4_V_read20_rewind_reg_274;
reg   [7:0] data_5_V_read21_rewind_reg_288;
reg   [7:0] data_6_V_read22_rewind_reg_302;
reg   [7:0] data_7_V_read23_rewind_reg_316;
reg   [7:0] data_8_V_read24_rewind_reg_330;
reg   [7:0] data_9_V_read25_rewind_reg_344;
reg   [7:0] data_0_V_read16_phi_reg_358;
reg   [7:0] data_1_V_read17_phi_reg_370;
reg   [7:0] data_2_V_read18_phi_reg_382;
reg   [7:0] data_3_V_read19_phi_reg_394;
reg   [7:0] data_4_V_read20_phi_reg_406;
reg   [7:0] data_5_V_read21_phi_reg_418;
reg   [7:0] data_6_V_read22_phi_reg_430;
reg   [7:0] data_7_V_read23_phi_reg_442;
reg   [7:0] data_8_V_read24_phi_reg_454;
reg   [7:0] data_9_V_read25_phi_reg_466;
reg   [15:0] acc_V_4_09_reg_478;
reg   [15:0] acc_V_3_08_reg_492;
reg   [15:0] acc_V_2_07_reg_506;
reg   [15:0] acc_V_1_06_reg_520;
reg   [15:0] acc_V_0_05_reg_534;
reg   [0:0] ap_phi_mux_do_init_phi_fu_191_p6;
wire   [3:0] w_index_fu_553_p2;
reg   [3:0] w_index_reg_1025;
reg   [0:0] icmp_ln46_reg_1030;
reg   [0:0] icmp_ln46_reg_1030_pp0_iter1_reg;
wire   [7:0] tmp_11_fu_565_p12;
reg   [7:0] tmp_11_reg_1034;
wire   [7:0] trunc_ln59_fu_591_p1;
reg   [7:0] trunc_ln59_reg_1040;
reg   [7:0] tmp_2_reg_1045;
reg   [7:0] tmp_3_reg_1050;
reg   [7:0] tmp_4_reg_1055;
reg   [5:0] tmp_12_reg_1060;
wire   [15:0] acc_0_V_fu_675_p2;
reg    ap_enable_reg_pp0_iter2;
wire   [15:0] acc_1_V_fu_724_p2;
wire   [15:0] acc_2_V_fu_773_p2;
wire   [15:0] acc_3_V_fu_822_p2;
wire   [15:0] acc_4_V_fu_874_p2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage0;
reg   [3:0] ap_phi_mux_w_index15_phi_fu_207_p6;
reg   [7:0] ap_phi_mux_data_0_V_read16_rewind_phi_fu_222_p6;
reg   [7:0] ap_phi_mux_data_1_V_read17_rewind_phi_fu_236_p6;
reg   [7:0] ap_phi_mux_data_2_V_read18_rewind_phi_fu_250_p6;
reg   [7:0] ap_phi_mux_data_3_V_read19_rewind_phi_fu_264_p6;
reg   [7:0] ap_phi_mux_data_4_V_read20_rewind_phi_fu_278_p6;
reg   [7:0] ap_phi_mux_data_5_V_read21_rewind_phi_fu_292_p6;
reg   [7:0] ap_phi_mux_data_6_V_read22_rewind_phi_fu_306_p6;
reg   [7:0] ap_phi_mux_data_7_V_read23_rewind_phi_fu_320_p6;
reg   [7:0] ap_phi_mux_data_8_V_read24_rewind_phi_fu_334_p6;
reg   [7:0] ap_phi_mux_data_9_V_read25_rewind_phi_fu_348_p6;
reg   [7:0] ap_phi_mux_data_0_V_read16_phi_phi_fu_362_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_0_V_read16_phi_reg_358;
reg   [7:0] ap_phi_reg_pp0_iter1_data_0_V_read16_phi_reg_358;
reg   [7:0] ap_phi_mux_data_1_V_read17_phi_phi_fu_374_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_1_V_read17_phi_reg_370;
reg   [7:0] ap_phi_reg_pp0_iter1_data_1_V_read17_phi_reg_370;
reg   [7:0] ap_phi_mux_data_2_V_read18_phi_phi_fu_386_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_2_V_read18_phi_reg_382;
reg   [7:0] ap_phi_reg_pp0_iter1_data_2_V_read18_phi_reg_382;
reg   [7:0] ap_phi_mux_data_3_V_read19_phi_phi_fu_398_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_3_V_read19_phi_reg_394;
reg   [7:0] ap_phi_reg_pp0_iter1_data_3_V_read19_phi_reg_394;
reg   [7:0] ap_phi_mux_data_4_V_read20_phi_phi_fu_410_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_4_V_read20_phi_reg_406;
reg   [7:0] ap_phi_reg_pp0_iter1_data_4_V_read20_phi_reg_406;
reg   [7:0] ap_phi_mux_data_5_V_read21_phi_phi_fu_422_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_5_V_read21_phi_reg_418;
reg   [7:0] ap_phi_reg_pp0_iter1_data_5_V_read21_phi_reg_418;
reg   [7:0] ap_phi_mux_data_6_V_read22_phi_phi_fu_434_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_6_V_read22_phi_reg_430;
reg   [7:0] ap_phi_reg_pp0_iter1_data_6_V_read22_phi_reg_430;
reg   [7:0] ap_phi_mux_data_7_V_read23_phi_phi_fu_446_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_7_V_read23_phi_reg_442;
reg   [7:0] ap_phi_reg_pp0_iter1_data_7_V_read23_phi_reg_442;
reg   [7:0] ap_phi_mux_data_8_V_read24_phi_phi_fu_458_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_8_V_read24_phi_reg_454;
reg   [7:0] ap_phi_reg_pp0_iter1_data_8_V_read24_phi_reg_454;
reg   [7:0] ap_phi_mux_data_9_V_read25_phi_phi_fu_470_p4;
wire   [7:0] ap_phi_reg_pp0_iter0_data_9_V_read25_phi_reg_466;
reg   [7:0] ap_phi_reg_pp0_iter1_data_9_V_read25_phi_reg_466;
wire   [63:0] zext_ln59_fu_548_p1;
wire   [7:0] mul_ln1118_fu_641_p0;
wire   [15:0] zext_ln1116_fu_635_p1;
wire  signed [7:0] mul_ln1118_fu_641_p1;
wire   [15:0] mul_ln1118_fu_641_p2;
wire   [14:0] trunc_ln_fu_647_p4;
wire  signed [15:0] sext_ln708_fu_657_p1;
wire   [11:0] trunc_ln703_fu_671_p1;
wire   [11:0] trunc_ln703_5_fu_661_p4;
wire   [7:0] mul_ln1118_1_fu_690_p0;
wire  signed [7:0] mul_ln1118_1_fu_690_p1;
wire   [15:0] mul_ln1118_1_fu_690_p2;
wire   [14:0] trunc_ln708_s_fu_696_p4;
wire  signed [15:0] sext_ln708_1_fu_706_p1;
wire   [11:0] trunc_ln703_1_fu_720_p1;
wire   [11:0] trunc_ln1_fu_710_p4;
wire   [7:0] mul_ln1118_2_fu_739_p0;
wire  signed [7:0] mul_ln1118_2_fu_739_p1;
wire   [15:0] mul_ln1118_2_fu_739_p2;
wire   [14:0] trunc_ln708_14_fu_745_p4;
wire  signed [15:0] sext_ln708_2_fu_755_p1;
wire   [11:0] trunc_ln703_3_fu_769_p1;
wire   [11:0] trunc_ln703_8_fu_759_p4;
wire   [7:0] mul_ln1118_3_fu_788_p0;
wire  signed [7:0] mul_ln1118_3_fu_788_p1;
wire   [15:0] mul_ln1118_3_fu_788_p2;
wire   [14:0] trunc_ln708_15_fu_794_p4;
wire  signed [15:0] sext_ln708_3_fu_804_p1;
wire   [11:0] trunc_ln703_4_fu_818_p1;
wire   [11:0] trunc_ln703_s_fu_808_p4;
wire  signed [5:0] mul_ln1118_4_fu_840_p0;
wire   [7:0] mul_ln1118_4_fu_840_p1;
wire   [13:0] mul_ln1118_4_fu_840_p2;
wire   [12:0] trunc_ln708_16_fu_846_p4;
wire  signed [15:0] sext_ln708_4_fu_856_p1;
wire   [11:0] trunc_ln703_6_fu_870_p1;
wire   [11:0] trunc_ln703_2_fu_860_p4;
wire   [11:0] add_ln703_1_fu_681_p2;
wire   [11:0] add_ln703_2_fu_730_p2;
wire   [11:0] add_ln703_3_fu_779_p2;
wire   [11:0] add_ln703_4_fu_828_p2;
wire   [11:0] add_ln703_5_fu_880_p2;
reg   [7:0] ap_return_0_preg;
reg   [7:0] ap_return_1_preg;
reg   [7:0] ap_return_2_preg;
reg   [7:0] ap_return_3_preg;
reg   [7:0] ap_return_4_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [13:0] mul_ln1118_4_fu_840_p10;
reg    ap_condition_192;
reg    ap_condition_40;
reg    ap_condition_186;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_return_0_preg = 8'd0;
#0 ap_return_1_preg = 8'd0;
#0 ap_return_2_preg = 8'd0;
#0 ap_return_3_preg = 8'd0;
#0 ap_return_4_preg = 8'd0;
end

dense_wrapper_ap_ufixed_8_2_5_3_0_ap_fixed_8_2_5_3_0_config21_s_w21_V #(
    .DataWidth( 38 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
w21_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w21_V_address0),
    .ce0(w21_V_ce0),
    .q0(w21_V_q0)
);

myproject_mux_104_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 8 ),
    .din6_WIDTH( 8 ),
    .din7_WIDTH( 8 ),
    .din8_WIDTH( 8 ),
    .din9_WIDTH( 8 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 8 ))
myproject_mux_104_8_1_1_U858(
    .din0(ap_phi_mux_data_0_V_read16_phi_phi_fu_362_p4),
    .din1(ap_phi_mux_data_1_V_read17_phi_phi_fu_374_p4),
    .din2(ap_phi_mux_data_2_V_read18_phi_phi_fu_386_p4),
    .din3(ap_phi_mux_data_3_V_read19_phi_phi_fu_398_p4),
    .din4(ap_phi_mux_data_4_V_read20_phi_phi_fu_410_p4),
    .din5(ap_phi_mux_data_5_V_read21_phi_phi_fu_422_p4),
    .din6(ap_phi_mux_data_6_V_read22_phi_phi_fu_434_p4),
    .din7(ap_phi_mux_data_7_V_read23_phi_phi_fu_446_p4),
    .din8(ap_phi_mux_data_8_V_read24_phi_phi_fu_458_p4),
    .din9(ap_phi_mux_data_9_V_read25_phi_phi_fu_470_p4),
    .din10(w_index15_reg_203),
    .dout(tmp_11_fu_565_p12)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_0_preg <= {{add_ln703_1_fu_681_p2[11:4]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_1_preg <= {{add_ln703_2_fu_730_p2[11:4]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_2_preg <= {{add_ln703_3_fu_779_p2[11:4]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_3_preg <= {{add_ln703_4_fu_828_p2[11:4]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 8'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_4_preg <= {{add_ln703_5_fu_880_p2[11:4]}};
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        acc_V_0_05_reg_534 <= acc_0_V_fu_675_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_0_05_reg_534 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        acc_V_1_06_reg_520 <= acc_1_V_fu_724_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_1_06_reg_520 <= 16'd32;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        acc_V_2_07_reg_506 <= acc_2_V_fu_773_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_2_07_reg_506 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        acc_V_3_08_reg_492 <= acc_3_V_fu_822_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_3_08_reg_492 <= 16'd32;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        acc_V_4_09_reg_478 <= acc_4_V_fu_874_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        acc_V_4_09_reg_478 <= 16'd448;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_0_V_read16_phi_reg_358 <= data_0_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_0_V_read16_phi_reg_358 <= ap_phi_reg_pp0_iter0_data_0_V_read16_phi_reg_358;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_1_V_read17_phi_reg_370 <= data_1_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_1_V_read17_phi_reg_370 <= ap_phi_reg_pp0_iter0_data_1_V_read17_phi_reg_370;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_2_V_read18_phi_reg_382 <= data_2_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_2_V_read18_phi_reg_382 <= ap_phi_reg_pp0_iter0_data_2_V_read18_phi_reg_382;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_3_V_read19_phi_reg_394 <= data_3_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_3_V_read19_phi_reg_394 <= ap_phi_reg_pp0_iter0_data_3_V_read19_phi_reg_394;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_4_V_read20_phi_reg_406 <= data_4_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_4_V_read20_phi_reg_406 <= ap_phi_reg_pp0_iter0_data_4_V_read20_phi_reg_406;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_5_V_read21_phi_reg_418 <= data_5_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_5_V_read21_phi_reg_418 <= ap_phi_reg_pp0_iter0_data_5_V_read21_phi_reg_418;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_6_V_read22_phi_reg_430 <= data_6_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_6_V_read22_phi_reg_430 <= ap_phi_reg_pp0_iter0_data_6_V_read22_phi_reg_430;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_7_V_read23_phi_reg_442 <= data_7_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_7_V_read23_phi_reg_442 <= ap_phi_reg_pp0_iter0_data_7_V_read23_phi_reg_442;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_8_V_read24_phi_reg_454 <= data_8_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_8_V_read24_phi_reg_454 <= ap_phi_reg_pp0_iter0_data_8_V_read24_phi_reg_454;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_191_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_9_V_read25_phi_reg_466 <= data_9_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_9_V_read25_phi_reg_466 <= ap_phi_reg_pp0_iter0_data_9_V_read25_phi_reg_466;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_0_V_read16_phi_reg_358 <= ap_phi_mux_data_0_V_read16_rewind_phi_fu_222_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_0_V_read16_phi_reg_358 <= ap_phi_reg_pp0_iter1_data_0_V_read16_phi_reg_358;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_1_V_read17_phi_reg_370 <= ap_phi_mux_data_1_V_read17_rewind_phi_fu_236_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_1_V_read17_phi_reg_370 <= ap_phi_reg_pp0_iter1_data_1_V_read17_phi_reg_370;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_2_V_read18_phi_reg_382 <= ap_phi_mux_data_2_V_read18_rewind_phi_fu_250_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_2_V_read18_phi_reg_382 <= ap_phi_reg_pp0_iter1_data_2_V_read18_phi_reg_382;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_3_V_read19_phi_reg_394 <= ap_phi_mux_data_3_V_read19_rewind_phi_fu_264_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_3_V_read19_phi_reg_394 <= ap_phi_reg_pp0_iter1_data_3_V_read19_phi_reg_394;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_4_V_read20_phi_reg_406 <= ap_phi_mux_data_4_V_read20_rewind_phi_fu_278_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_4_V_read20_phi_reg_406 <= ap_phi_reg_pp0_iter1_data_4_V_read20_phi_reg_406;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_5_V_read21_phi_reg_418 <= ap_phi_mux_data_5_V_read21_rewind_phi_fu_292_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_5_V_read21_phi_reg_418 <= ap_phi_reg_pp0_iter1_data_5_V_read21_phi_reg_418;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_6_V_read22_phi_reg_430 <= ap_phi_mux_data_6_V_read22_rewind_phi_fu_306_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_6_V_read22_phi_reg_430 <= ap_phi_reg_pp0_iter1_data_6_V_read22_phi_reg_430;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_7_V_read23_phi_reg_442 <= ap_phi_mux_data_7_V_read23_rewind_phi_fu_320_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_7_V_read23_phi_reg_442 <= ap_phi_reg_pp0_iter1_data_7_V_read23_phi_reg_442;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_8_V_read24_phi_reg_454 <= ap_phi_mux_data_8_V_read24_rewind_phi_fu_334_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_8_V_read24_phi_reg_454 <= ap_phi_reg_pp0_iter1_data_8_V_read24_phi_reg_454;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_186)) begin
        if ((do_init_reg_187 == 1'd0)) begin
            data_9_V_read25_phi_reg_466 <= ap_phi_mux_data_9_V_read25_rewind_phi_fu_348_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_9_V_read25_phi_reg_466 <= ap_phi_reg_pp0_iter1_data_9_V_read25_phi_reg_466;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_1030 == 1'd0))) begin
        do_init_reg_187 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_187 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln46_reg_1030 == 1'd0))) begin
        w_index15_reg_203 <= w_index_reg_1025;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index15_reg_203 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        data_0_V_read16_rewind_reg_218 <= data_0_V_read16_phi_reg_358;
        data_1_V_read17_rewind_reg_232 <= data_1_V_read17_phi_reg_370;
        data_2_V_read18_rewind_reg_246 <= data_2_V_read18_phi_reg_382;
        data_3_V_read19_rewind_reg_260 <= data_3_V_read19_phi_reg_394;
        data_4_V_read20_rewind_reg_274 <= data_4_V_read20_phi_reg_406;
        data_5_V_read21_rewind_reg_288 <= data_5_V_read21_phi_reg_418;
        data_6_V_read22_rewind_reg_302 <= data_6_V_read22_phi_reg_430;
        data_7_V_read23_rewind_reg_316 <= data_7_V_read23_phi_reg_442;
        data_8_V_read24_rewind_reg_330 <= data_8_V_read24_phi_reg_454;
        data_9_V_read25_rewind_reg_344 <= data_9_V_read25_phi_reg_466;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln46_reg_1030 <= icmp_ln46_fu_559_p2;
        icmp_ln46_reg_1030_pp0_iter1_reg <= icmp_ln46_reg_1030;
        tmp_11_reg_1034 <= tmp_11_fu_565_p12;
        tmp_12_reg_1060 <= {{w21_V_q0[37:32]}};
        tmp_2_reg_1045 <= {{w21_V_q0[15:8]}};
        tmp_3_reg_1050 <= {{w21_V_q0[23:16]}};
        tmp_4_reg_1055 <= {{w21_V_q0[31:24]}};
        trunc_ln59_reg_1040 <= trunc_ln59_fu_591_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1025 <= w_index_fu_553_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_0_V_read16_phi_phi_fu_362_p4 = ap_phi_mux_data_0_V_read16_rewind_phi_fu_222_p6;
    end else begin
        ap_phi_mux_data_0_V_read16_phi_phi_fu_362_p4 = ap_phi_reg_pp0_iter1_data_0_V_read16_phi_reg_358;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_0_V_read16_rewind_phi_fu_222_p6 = data_0_V_read16_phi_reg_358;
    end else begin
        ap_phi_mux_data_0_V_read16_rewind_phi_fu_222_p6 = data_0_V_read16_rewind_reg_218;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_1_V_read17_phi_phi_fu_374_p4 = ap_phi_mux_data_1_V_read17_rewind_phi_fu_236_p6;
    end else begin
        ap_phi_mux_data_1_V_read17_phi_phi_fu_374_p4 = ap_phi_reg_pp0_iter1_data_1_V_read17_phi_reg_370;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_1_V_read17_rewind_phi_fu_236_p6 = data_1_V_read17_phi_reg_370;
    end else begin
        ap_phi_mux_data_1_V_read17_rewind_phi_fu_236_p6 = data_1_V_read17_rewind_reg_232;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_2_V_read18_phi_phi_fu_386_p4 = ap_phi_mux_data_2_V_read18_rewind_phi_fu_250_p6;
    end else begin
        ap_phi_mux_data_2_V_read18_phi_phi_fu_386_p4 = ap_phi_reg_pp0_iter1_data_2_V_read18_phi_reg_382;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_2_V_read18_rewind_phi_fu_250_p6 = data_2_V_read18_phi_reg_382;
    end else begin
        ap_phi_mux_data_2_V_read18_rewind_phi_fu_250_p6 = data_2_V_read18_rewind_reg_246;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_3_V_read19_phi_phi_fu_398_p4 = ap_phi_mux_data_3_V_read19_rewind_phi_fu_264_p6;
    end else begin
        ap_phi_mux_data_3_V_read19_phi_phi_fu_398_p4 = ap_phi_reg_pp0_iter1_data_3_V_read19_phi_reg_394;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_3_V_read19_rewind_phi_fu_264_p6 = data_3_V_read19_phi_reg_394;
    end else begin
        ap_phi_mux_data_3_V_read19_rewind_phi_fu_264_p6 = data_3_V_read19_rewind_reg_260;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_4_V_read20_phi_phi_fu_410_p4 = ap_phi_mux_data_4_V_read20_rewind_phi_fu_278_p6;
    end else begin
        ap_phi_mux_data_4_V_read20_phi_phi_fu_410_p4 = ap_phi_reg_pp0_iter1_data_4_V_read20_phi_reg_406;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_4_V_read20_rewind_phi_fu_278_p6 = data_4_V_read20_phi_reg_406;
    end else begin
        ap_phi_mux_data_4_V_read20_rewind_phi_fu_278_p6 = data_4_V_read20_rewind_reg_274;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_5_V_read21_phi_phi_fu_422_p4 = ap_phi_mux_data_5_V_read21_rewind_phi_fu_292_p6;
    end else begin
        ap_phi_mux_data_5_V_read21_phi_phi_fu_422_p4 = ap_phi_reg_pp0_iter1_data_5_V_read21_phi_reg_418;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_5_V_read21_rewind_phi_fu_292_p6 = data_5_V_read21_phi_reg_418;
    end else begin
        ap_phi_mux_data_5_V_read21_rewind_phi_fu_292_p6 = data_5_V_read21_rewind_reg_288;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_6_V_read22_phi_phi_fu_434_p4 = ap_phi_mux_data_6_V_read22_rewind_phi_fu_306_p6;
    end else begin
        ap_phi_mux_data_6_V_read22_phi_phi_fu_434_p4 = ap_phi_reg_pp0_iter1_data_6_V_read22_phi_reg_430;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_6_V_read22_rewind_phi_fu_306_p6 = data_6_V_read22_phi_reg_430;
    end else begin
        ap_phi_mux_data_6_V_read22_rewind_phi_fu_306_p6 = data_6_V_read22_rewind_reg_302;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_7_V_read23_phi_phi_fu_446_p4 = ap_phi_mux_data_7_V_read23_rewind_phi_fu_320_p6;
    end else begin
        ap_phi_mux_data_7_V_read23_phi_phi_fu_446_p4 = ap_phi_reg_pp0_iter1_data_7_V_read23_phi_reg_442;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_7_V_read23_rewind_phi_fu_320_p6 = data_7_V_read23_phi_reg_442;
    end else begin
        ap_phi_mux_data_7_V_read23_rewind_phi_fu_320_p6 = data_7_V_read23_rewind_reg_316;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_8_V_read24_phi_phi_fu_458_p4 = ap_phi_mux_data_8_V_read24_rewind_phi_fu_334_p6;
    end else begin
        ap_phi_mux_data_8_V_read24_phi_phi_fu_458_p4 = ap_phi_reg_pp0_iter1_data_8_V_read24_phi_reg_454;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_8_V_read24_rewind_phi_fu_334_p6 = data_8_V_read24_phi_reg_454;
    end else begin
        ap_phi_mux_data_8_V_read24_rewind_phi_fu_334_p6 = data_8_V_read24_rewind_reg_330;
    end
end

always @ (*) begin
    if (((do_init_reg_187 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_data_9_V_read25_phi_phi_fu_470_p4 = ap_phi_mux_data_9_V_read25_rewind_phi_fu_348_p6;
    end else begin
        ap_phi_mux_data_9_V_read25_phi_phi_fu_470_p4 = ap_phi_reg_pp0_iter1_data_9_V_read25_phi_reg_466;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_data_9_V_read25_rewind_phi_fu_348_p6 = data_9_V_read25_phi_reg_466;
    end else begin
        ap_phi_mux_data_9_V_read25_rewind_phi_fu_348_p6 = data_9_V_read25_rewind_reg_344;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_192)) begin
        if ((icmp_ln46_reg_1030 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_191_p6 = 1'd1;
        end else if ((icmp_ln46_reg_1030 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_191_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_191_p6 = do_init_reg_187;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_191_p6 = do_init_reg_187;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_192)) begin
        if ((icmp_ln46_reg_1030 == 1'd1)) begin
            ap_phi_mux_w_index15_phi_fu_207_p6 = 4'd0;
        end else if ((icmp_ln46_reg_1030 == 1'd0)) begin
            ap_phi_mux_w_index15_phi_fu_207_p6 = w_index_reg_1025;
        end else begin
            ap_phi_mux_w_index15_phi_fu_207_p6 = w_index15_reg_203;
        end
    end else begin
        ap_phi_mux_w_index15_phi_fu_207_p6 = w_index15_reg_203;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_fu_559_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_0 = {{add_ln703_1_fu_681_p2[11:4]}};
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_1 = {{add_ln703_2_fu_730_p2[11:4]}};
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_2 = {{add_ln703_3_fu_779_p2[11:4]}};
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_3 = {{add_ln703_4_fu_828_p2[11:4]}};
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln46_reg_1030_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_4 = {{add_ln703_5_fu_880_p2[11:4]}};
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w21_V_ce0 = 1'b1;
    end else begin
        w21_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((ap_reset_idle_pp0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_675_p2 = ($signed(acc_V_0_05_reg_534) + $signed(sext_ln708_fu_657_p1));

assign acc_1_V_fu_724_p2 = ($signed(acc_V_1_06_reg_520) + $signed(sext_ln708_1_fu_706_p1));

assign acc_2_V_fu_773_p2 = ($signed(acc_V_2_07_reg_506) + $signed(sext_ln708_2_fu_755_p1));

assign acc_3_V_fu_822_p2 = ($signed(acc_V_3_08_reg_492) + $signed(sext_ln708_3_fu_804_p1));

assign acc_4_V_fu_874_p2 = ($signed(acc_V_4_09_reg_478) + $signed(sext_ln708_4_fu_856_p1));

assign add_ln703_1_fu_681_p2 = (trunc_ln703_fu_671_p1 + trunc_ln703_5_fu_661_p4);

assign add_ln703_2_fu_730_p2 = (trunc_ln703_1_fu_720_p1 + trunc_ln1_fu_710_p4);

assign add_ln703_3_fu_779_p2 = (trunc_ln703_3_fu_769_p1 + trunc_ln703_8_fu_759_p4);

assign add_ln703_4_fu_828_p2 = (trunc_ln703_4_fu_818_p1 + trunc_ln703_s_fu_808_p4);

assign add_ln703_5_fu_880_p2 = (trunc_ln703_6_fu_870_p1 + trunc_ln703_2_fu_860_p4);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_186 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_192 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_40 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_data_0_V_read16_phi_reg_358 = 'bx;

assign ap_phi_reg_pp0_iter0_data_1_V_read17_phi_reg_370 = 'bx;

assign ap_phi_reg_pp0_iter0_data_2_V_read18_phi_reg_382 = 'bx;

assign ap_phi_reg_pp0_iter0_data_3_V_read19_phi_reg_394 = 'bx;

assign ap_phi_reg_pp0_iter0_data_4_V_read20_phi_reg_406 = 'bx;

assign ap_phi_reg_pp0_iter0_data_5_V_read21_phi_reg_418 = 'bx;

assign ap_phi_reg_pp0_iter0_data_6_V_read22_phi_reg_430 = 'bx;

assign ap_phi_reg_pp0_iter0_data_7_V_read23_phi_reg_442 = 'bx;

assign ap_phi_reg_pp0_iter0_data_8_V_read24_phi_reg_454 = 'bx;

assign ap_phi_reg_pp0_iter0_data_9_V_read25_phi_reg_466 = 'bx;

assign icmp_ln46_fu_559_p2 = ((ap_phi_mux_w_index15_phi_fu_207_p6 == 4'd9) ? 1'b1 : 1'b0);

assign mul_ln1118_1_fu_690_p0 = zext_ln1116_fu_635_p1;

assign mul_ln1118_1_fu_690_p1 = tmp_2_reg_1045;

assign mul_ln1118_1_fu_690_p2 = ($signed({{1'b0}, {mul_ln1118_1_fu_690_p0}}) * $signed(mul_ln1118_1_fu_690_p1));

assign mul_ln1118_2_fu_739_p0 = zext_ln1116_fu_635_p1;

assign mul_ln1118_2_fu_739_p1 = tmp_3_reg_1050;

assign mul_ln1118_2_fu_739_p2 = ($signed({{1'b0}, {mul_ln1118_2_fu_739_p0}}) * $signed(mul_ln1118_2_fu_739_p1));

assign mul_ln1118_3_fu_788_p0 = zext_ln1116_fu_635_p1;

assign mul_ln1118_3_fu_788_p1 = tmp_4_reg_1055;

assign mul_ln1118_3_fu_788_p2 = ($signed({{1'b0}, {mul_ln1118_3_fu_788_p0}}) * $signed(mul_ln1118_3_fu_788_p1));

assign mul_ln1118_4_fu_840_p0 = tmp_12_reg_1060;

assign mul_ln1118_4_fu_840_p1 = mul_ln1118_4_fu_840_p10;

assign mul_ln1118_4_fu_840_p10 = tmp_11_reg_1034;

assign mul_ln1118_4_fu_840_p2 = ($signed(mul_ln1118_4_fu_840_p0) * $signed({{1'b0}, {mul_ln1118_4_fu_840_p1}}));

assign mul_ln1118_fu_641_p0 = zext_ln1116_fu_635_p1;

assign mul_ln1118_fu_641_p1 = trunc_ln59_reg_1040;

assign mul_ln1118_fu_641_p2 = ($signed({{1'b0}, {mul_ln1118_fu_641_p0}}) * $signed(mul_ln1118_fu_641_p1));

assign sext_ln708_1_fu_706_p1 = $signed(trunc_ln708_s_fu_696_p4);

assign sext_ln708_2_fu_755_p1 = $signed(trunc_ln708_14_fu_745_p4);

assign sext_ln708_3_fu_804_p1 = $signed(trunc_ln708_15_fu_794_p4);

assign sext_ln708_4_fu_856_p1 = $signed(trunc_ln708_16_fu_846_p4);

assign sext_ln708_fu_657_p1 = $signed(trunc_ln_fu_647_p4);

assign trunc_ln1_fu_710_p4 = {{mul_ln1118_1_fu_690_p2[12:1]}};

assign trunc_ln59_fu_591_p1 = w21_V_q0[7:0];

assign trunc_ln703_1_fu_720_p1 = acc_V_1_06_reg_520[11:0];

assign trunc_ln703_2_fu_860_p4 = {{mul_ln1118_4_fu_840_p2[12:1]}};

assign trunc_ln703_3_fu_769_p1 = acc_V_2_07_reg_506[11:0];

assign trunc_ln703_4_fu_818_p1 = acc_V_3_08_reg_492[11:0];

assign trunc_ln703_5_fu_661_p4 = {{mul_ln1118_fu_641_p2[12:1]}};

assign trunc_ln703_6_fu_870_p1 = acc_V_4_09_reg_478[11:0];

assign trunc_ln703_8_fu_759_p4 = {{mul_ln1118_2_fu_739_p2[12:1]}};

assign trunc_ln703_fu_671_p1 = acc_V_0_05_reg_534[11:0];

assign trunc_ln703_s_fu_808_p4 = {{mul_ln1118_3_fu_788_p2[12:1]}};

assign trunc_ln708_14_fu_745_p4 = {{mul_ln1118_2_fu_739_p2[15:1]}};

assign trunc_ln708_15_fu_794_p4 = {{mul_ln1118_3_fu_788_p2[15:1]}};

assign trunc_ln708_16_fu_846_p4 = {{mul_ln1118_4_fu_840_p2[13:1]}};

assign trunc_ln708_s_fu_696_p4 = {{mul_ln1118_1_fu_690_p2[15:1]}};

assign trunc_ln_fu_647_p4 = {{mul_ln1118_fu_641_p2[15:1]}};

assign w21_V_address0 = zext_ln59_fu_548_p1;

assign w_index_fu_553_p2 = (4'd1 + ap_phi_mux_w_index15_phi_fu_207_p6);

assign zext_ln1116_fu_635_p1 = tmp_11_reg_1034;

assign zext_ln59_fu_548_p1 = ap_phi_mux_w_index15_phi_fu_207_p6;

endmodule //dense_wrapper_ap_ufixed_8_2_5_3_0_ap_fixed_8_2_5_3_0_config21_s
