// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_6u_config2_s_HH_
#define _compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_6u_config2_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0.h"
#include "shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s.h"

namespace ap_rtl {

struct compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_6u_config2_s : public sc_module {
    // Port declarations 25
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > p_read;
    sc_out< sc_lv<8> > res_stream_V_data_0_V_din;
    sc_in< sc_logic > res_stream_V_data_0_V_full_n;
    sc_out< sc_logic > res_stream_V_data_0_V_write;
    sc_out< sc_lv<8> > res_stream_V_data_1_V_din;
    sc_in< sc_logic > res_stream_V_data_1_V_full_n;
    sc_out< sc_logic > res_stream_V_data_1_V_write;
    sc_out< sc_lv<8> > res_stream_V_data_2_V_din;
    sc_in< sc_logic > res_stream_V_data_2_V_full_n;
    sc_out< sc_logic > res_stream_V_data_2_V_write;
    sc_out< sc_lv<8> > res_stream_V_data_3_V_din;
    sc_in< sc_logic > res_stream_V_data_3_V_full_n;
    sc_out< sc_logic > res_stream_V_data_3_V_write;
    sc_out< sc_lv<8> > res_stream_V_data_4_V_din;
    sc_in< sc_logic > res_stream_V_data_4_V_full_n;
    sc_out< sc_logic > res_stream_V_data_4_V_write;
    sc_out< sc_lv<8> > res_stream_V_data_5_V_din;
    sc_in< sc_logic > res_stream_V_data_5_V_full_n;
    sc_out< sc_logic > res_stream_V_data_5_V_write;


    // Module declarations
    compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_6u_config2_s(sc_module_name name);
    SC_HAS_PROCESS(compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_6u_config2_s);

    ~compute_output_buffer_2d_array_array_ap_fixed_8_2_5_3_0_6u_config2_s();

    sc_trace_file* mVcdFile;

    dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0* grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184;
    shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s* call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<8> > kernel_data_V_1411;
    sc_signal< sc_lv<8> > kernel_data_V_2412;
    sc_signal< sc_lv<8> > kernel_data_V_4414;
    sc_signal< sc_lv<8> > kernel_data_V_5415;
    sc_signal< sc_lv<8> > kernel_data_V_7;
    sc_signal< sc_lv<8> > kernel_data_V_8;
    sc_signal< sc_lv<8> > kernel_data_V_0;
    sc_signal< sc_lv<8> > kernel_data_V_3413;
    sc_signal< sc_lv<8> > kernel_data_V_6;
    sc_signal< sc_lv<32> > sX_5;
    sc_signal< sc_lv<32> > sY_5;
    sc_signal< sc_lv<32> > pY_5;
    sc_signal< sc_lv<32> > pX_5;
    sc_signal< sc_logic > res_stream_V_data_0_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > and_ln284_4_reg_565;
    sc_signal< sc_logic > res_stream_V_data_1_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_2_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_3_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_4_V_blk_n;
    sc_signal< sc_logic > res_stream_V_data_5_V_blk_n;
    sc_signal< sc_lv<32> > sX_5_load_reg_533;
    sc_signal< sc_lv<1> > icmp_ln284_fu_348_p2;
    sc_signal< sc_lv<1> > icmp_ln284_reg_538;
    sc_signal< sc_lv<32> > sY_5_load_reg_543;
    sc_signal< sc_lv<1> > icmp_ln284_4_fu_358_p2;
    sc_signal< sc_lv<1> > icmp_ln284_4_reg_548;
    sc_signal< sc_lv<32> > pY_5_load_reg_553;
    sc_signal< sc_lv<32> > pX_5_load_reg_559;
    sc_signal< sc_lv<1> > and_ln284_4_fu_416_p2;
    sc_signal< sc_lv<8> > tmp_data_0_V_reg_569;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_ready;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_done;
    sc_signal< sc_lv<8> > tmp_data_1_V_reg_574;
    sc_signal< sc_lv<8> > tmp_data_2_V_reg_579;
    sc_signal< sc_lv<8> > tmp_data_3_V_reg_584;
    sc_signal< sc_lv<8> > tmp_data_4_V_reg_589;
    sc_signal< sc_lv<8> > tmp_data_5_V_reg_594;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_start;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_idle;
    sc_signal< sc_lv<8> > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_return_0;
    sc_signal< sc_lv<8> > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_return_1;
    sc_signal< sc_lv<8> > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_return_2;
    sc_signal< sc_lv<8> > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_return_3;
    sc_signal< sc_lv<8> > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_return_4;
    sc_signal< sc_lv<8> > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_return_5;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_start;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_done;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_idle;
    sc_signal< sc_logic > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_ready;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_0;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_1;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_2;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_3;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_4;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_5;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_6;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_7;
    sc_signal< sc_lv<8> > call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_return_8;
    sc_signal< sc_lv<32> > select_ln313_fu_513_p3;
    sc_signal< sc_lv<32> > ap_phi_mux_storemerge_phi_fu_177_p4;
    sc_signal< sc_logic > io_acc_block_signal_op58;
    sc_signal< bool > ap_block_state3;
    sc_signal< sc_lv<1> > icmp_ln303_fu_446_p2;
    sc_signal< sc_lv<1> > icmp_ln307_fu_492_p2;
    sc_signal< sc_logic > grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_start_reg;
    sc_signal< sc_lv<32> > select_ln318_fu_467_p3;
    sc_signal< sc_lv<32> > add_ln311_fu_497_p2;
    sc_signal< sc_lv<32> > add_ln316_fu_451_p2;
    sc_signal< sc_lv<31> > tmp_2_fu_368_p4;
    sc_signal< sc_lv<31> > tmp_3_fu_388_p4;
    sc_signal< sc_lv<1> > icmp_ln284_5_fu_378_p2;
    sc_signal< sc_lv<1> > icmp_ln284_6_fu_398_p2;
    sc_signal< sc_lv<1> > and_ln284_3_fu_410_p2;
    sc_signal< sc_lv<1> > and_ln284_fu_404_p2;
    sc_signal< sc_lv<32> > add_ln318_fu_462_p2;
    sc_signal< sc_lv<32> > add_ln313_fu_508_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< bool > ap_condition_164;
    sc_signal< bool > ap_condition_216;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<32> ap_const_lv32_2F;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln311_fu_497_p2();
    void thread_add_ln313_fu_508_p2();
    void thread_add_ln316_fu_451_p2();
    void thread_add_ln318_fu_462_p2();
    void thread_and_ln284_3_fu_410_p2();
    void thread_and_ln284_4_fu_416_p2();
    void thread_and_ln284_fu_404_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_state3();
    void thread_ap_condition_164();
    void thread_ap_condition_216();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_storemerge_phi_fu_177_p4();
    void thread_ap_ready();
    void thread_call_ret_shift_line_buffer_array_ap_ufixed_8_0_5_3_0_1u_config2_s_fu_208_ap_start();
    void thread_grp_dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_fu_184_ap_start();
    void thread_icmp_ln284_4_fu_358_p2();
    void thread_icmp_ln284_5_fu_378_p2();
    void thread_icmp_ln284_6_fu_398_p2();
    void thread_icmp_ln284_fu_348_p2();
    void thread_icmp_ln303_fu_446_p2();
    void thread_icmp_ln307_fu_492_p2();
    void thread_io_acc_block_signal_op58();
    void thread_res_stream_V_data_0_V_blk_n();
    void thread_res_stream_V_data_0_V_din();
    void thread_res_stream_V_data_0_V_write();
    void thread_res_stream_V_data_1_V_blk_n();
    void thread_res_stream_V_data_1_V_din();
    void thread_res_stream_V_data_1_V_write();
    void thread_res_stream_V_data_2_V_blk_n();
    void thread_res_stream_V_data_2_V_din();
    void thread_res_stream_V_data_2_V_write();
    void thread_res_stream_V_data_3_V_blk_n();
    void thread_res_stream_V_data_3_V_din();
    void thread_res_stream_V_data_3_V_write();
    void thread_res_stream_V_data_4_V_blk_n();
    void thread_res_stream_V_data_4_V_din();
    void thread_res_stream_V_data_4_V_write();
    void thread_res_stream_V_data_5_V_blk_n();
    void thread_res_stream_V_data_5_V_din();
    void thread_res_stream_V_data_5_V_write();
    void thread_select_ln313_fu_513_p3();
    void thread_select_ln318_fu_467_p3();
    void thread_tmp_2_fu_368_p4();
    void thread_tmp_3_fu_388_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
