// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_HH_
#define _dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_w2_V.h"

namespace ap_rtl {

struct dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0 : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<8> > kernel_data_V_8;
    sc_in< sc_lv<8> > kernel_data_V_0;
    sc_in< sc_lv<8> > kernel_data_V_1411;
    sc_in< sc_lv<8> > kernel_data_V_2412;
    sc_in< sc_lv<8> > kernel_data_V_3413;
    sc_in< sc_lv<8> > kernel_data_V_4414;
    sc_in< sc_lv<8> > kernel_data_V_5415;
    sc_in< sc_lv<8> > kernel_data_V_6;
    sc_in< sc_lv<8> > kernel_data_V_7;
    sc_out< sc_lv<8> > ap_return_0;
    sc_out< sc_lv<8> > ap_return_1;
    sc_out< sc_lv<8> > ap_return_2;
    sc_out< sc_lv<8> > ap_return_3;
    sc_out< sc_lv<8> > ap_return_4;
    sc_out< sc_lv<8> > ap_return_5;


    // Module declarations
    dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0(sc_module_name name);
    SC_HAS_PROCESS(dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0);

    ~dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0();

    sc_trace_file* mVcdFile;

    dense_resource_rf_leq_nin_ap_ufixed_ap_fixed_config2_mult_0_0_0_0_0_0_0_w2_V* w2_V_U;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<1> > icmp_ln46_fu_264_p2;
    sc_signal< sc_logic > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter2;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< sc_lv<4> > w2_V_address0;
    sc_signal< sc_logic > w2_V_ce0;
    sc_signal< sc_lv<47> > w2_V_q0;
    sc_signal< sc_lv<4> > w_index17_reg_139;
    sc_signal< sc_lv<14> > p_Val2_1216_reg_169;
    sc_signal< sc_lv<15> > p_Val2_1114_reg_183;
    sc_signal< sc_lv<15> > p_Val2_1012_reg_197;
    sc_signal< sc_lv<15> > p_Val2_910_reg_211;
    sc_signal< sc_lv<15> > p_Val2_88_reg_225;
    sc_signal< sc_lv<15> > p_Val2_6_reg_239;
    sc_signal< sc_lv<4> > w_index_fu_258_p2;
    sc_signal< sc_lv<4> > w_index_reg_799;
    sc_signal< sc_lv<1> > icmp_ln46_reg_804;
    sc_signal< sc_lv<1> > icmp_ln46_reg_804_pp0_iter1_reg;
    sc_signal< sc_lv<8> > select_ln19_7_fu_452_p3;
    sc_signal< sc_lv<8> > select_ln19_7_reg_808;
    sc_signal< sc_lv<8> > trunc_ln59_fu_460_p1;
    sc_signal< sc_lv<8> > trunc_ln59_reg_814;
    sc_signal< sc_lv<8> > tmp_382_i_reg_819;
    sc_signal< sc_lv<8> > tmp_384_i_reg_824;
    sc_signal< sc_lv<8> > tmp_386_i_reg_829;
    sc_signal< sc_lv<8> > tmp_388_i_reg_834;
    sc_signal< sc_lv<7> > tmp_reg_839;
    sc_signal< sc_lv<15> > acc_0_V_fu_540_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter2;
    sc_signal< sc_lv<15> > acc_1_V_fu_572_p2;
    sc_signal< sc_lv<15> > acc_2_V_fu_601_p2;
    sc_signal< sc_lv<15> > acc_3_V_fu_630_p2;
    sc_signal< sc_lv<15> > acc_4_V_fu_659_p2;
    sc_signal< sc_lv<14> > acc_5_V_fu_688_p2;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< bool > ap_block_pp0_stage0_subdone;
    sc_signal< sc_lv<4> > ap_phi_mux_w_index17_phi_fu_143_p6;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<64> > zext_ln59_fu_253_p1;
    sc_signal< sc_lv<1> > icmp_ln19_7_fu_348_p2;
    sc_signal< sc_lv<1> > icmp_ln19_6_fu_342_p2;
    sc_signal< sc_lv<1> > icmp_ln19_5_fu_336_p2;
    sc_signal< sc_lv<1> > icmp_ln19_4_fu_330_p2;
    sc_signal< sc_lv<1> > icmp_ln19_3_fu_324_p2;
    sc_signal< sc_lv<1> > icmp_ln19_2_fu_318_p2;
    sc_signal< sc_lv<1> > icmp_ln19_1_fu_312_p2;
    sc_signal< sc_lv<1> > icmp_ln19_fu_306_p2;
    sc_signal< sc_lv<1> > or_ln19_fu_362_p2;
    sc_signal< sc_lv<8> > select_ln19_fu_354_p3;
    sc_signal< sc_lv<8> > select_ln19_1_fu_368_p3;
    sc_signal< sc_lv<1> > or_ln19_1_fu_376_p2;
    sc_signal< sc_lv<1> > or_ln19_2_fu_390_p2;
    sc_signal< sc_lv<8> > select_ln19_2_fu_382_p3;
    sc_signal< sc_lv<8> > select_ln19_3_fu_396_p3;
    sc_signal< sc_lv<1> > or_ln19_3_fu_404_p2;
    sc_signal< sc_lv<1> > or_ln19_4_fu_418_p2;
    sc_signal< sc_lv<8> > select_ln19_4_fu_410_p3;
    sc_signal< sc_lv<8> > select_ln19_5_fu_424_p3;
    sc_signal< sc_lv<1> > or_ln19_5_fu_432_p2;
    sc_signal< sc_lv<1> > or_ln19_6_fu_446_p2;
    sc_signal< sc_lv<8> > select_ln19_6_fu_438_p3;
    sc_signal< sc_lv<8> > mul_ln1118_fu_520_p0;
    sc_signal< sc_lv<8> > mul_ln1118_fu_520_p1;
    sc_signal< sc_lv<16> > zext_ln1116_fu_514_p1;
    sc_signal< sc_lv<16> > mul_ln1118_fu_520_p2;
    sc_signal< sc_lv<11> > trunc_ln_fu_526_p4;
    sc_signal< sc_lv<15> > sext_ln703_fu_536_p1;
    sc_signal< sc_lv<8> > mul_ln1118_75_fu_552_p0;
    sc_signal< sc_lv<8> > mul_ln1118_75_fu_552_p1;
    sc_signal< sc_lv<16> > mul_ln1118_75_fu_552_p2;
    sc_signal< sc_lv<11> > trunc_ln708_s_fu_558_p4;
    sc_signal< sc_lv<15> > sext_ln703_1_fu_568_p1;
    sc_signal< sc_lv<8> > mul_ln1118_76_fu_581_p0;
    sc_signal< sc_lv<8> > mul_ln1118_76_fu_581_p1;
    sc_signal< sc_lv<16> > mul_ln1118_76_fu_581_p2;
    sc_signal< sc_lv<11> > trunc_ln708_84_fu_587_p4;
    sc_signal< sc_lv<15> > sext_ln703_2_fu_597_p1;
    sc_signal< sc_lv<8> > mul_ln1118_77_fu_610_p0;
    sc_signal< sc_lv<8> > mul_ln1118_77_fu_610_p1;
    sc_signal< sc_lv<16> > mul_ln1118_77_fu_610_p2;
    sc_signal< sc_lv<11> > trunc_ln708_85_fu_616_p4;
    sc_signal< sc_lv<15> > sext_ln703_3_fu_626_p1;
    sc_signal< sc_lv<8> > mul_ln1118_78_fu_639_p0;
    sc_signal< sc_lv<8> > mul_ln1118_78_fu_639_p1;
    sc_signal< sc_lv<16> > mul_ln1118_78_fu_639_p2;
    sc_signal< sc_lv<11> > trunc_ln708_86_fu_645_p4;
    sc_signal< sc_lv<15> > sext_ln703_4_fu_655_p1;
    sc_signal< sc_lv<8> > mul_ln1118_79_fu_668_p0;
    sc_signal< sc_lv<7> > mul_ln1118_79_fu_668_p1;
    sc_signal< sc_lv<15> > mul_ln1118_79_fu_668_p2;
    sc_signal< sc_lv<10> > tmp_1_fu_674_p4;
    sc_signal< sc_lv<14> > sext_ln703_5_fu_684_p1;
    sc_signal< sc_lv<8> > ap_return_0_preg;
    sc_signal< sc_lv<8> > ap_return_1_preg;
    sc_signal< sc_lv<8> > ap_return_2_preg;
    sc_signal< sc_lv<8> > ap_return_3_preg;
    sc_signal< sc_lv<8> > ap_return_4_preg;
    sc_signal< sc_lv<8> > ap_return_5_preg;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    sc_signal< sc_logic > ap_idle_pp0_0to1;
    sc_signal< sc_logic > ap_reset_idle_pp0;
    sc_signal< sc_logic > ap_idle_pp0;
    sc_signal< sc_logic > ap_enable_pp0;
    sc_signal< sc_lv<15> > mul_ln1118_79_fu_668_p00;
    sc_signal< bool > ap_condition_136;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_pp0_stage0;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const bool ap_const_boolean_0;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<14> ap_const_lv14_3C00;
    static const sc_lv<15> ap_const_lv15_7F80;
    static const sc_lv<15> ap_const_lv15_7FE0;
    static const sc_lv<15> ap_const_lv15_7FC8;
    static const sc_lv<15> ap_const_lv15_7FC0;
    static const sc_lv<15> ap_const_lv15_7F90;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_27;
    static const sc_lv<32> ap_const_lv32_28;
    static const sc_lv<32> ap_const_lv32_2E;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<8> ap_const_lv8_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_acc_0_V_fu_540_p2();
    void thread_acc_1_V_fu_572_p2();
    void thread_acc_2_V_fu_601_p2();
    void thread_acc_3_V_fu_630_p2();
    void thread_acc_4_V_fu_659_p2();
    void thread_acc_5_V_fu_688_p2();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_pp0_stage0_subdone();
    void thread_ap_block_state2_pp0_stage0_iter0();
    void thread_ap_block_state3_pp0_stage0_iter1();
    void thread_ap_block_state4_pp0_stage0_iter2();
    void thread_ap_condition_136();
    void thread_ap_done();
    void thread_ap_enable_pp0();
    void thread_ap_enable_reg_pp0_iter0();
    void thread_ap_idle();
    void thread_ap_idle_pp0();
    void thread_ap_idle_pp0_0to1();
    void thread_ap_phi_mux_w_index17_phi_fu_143_p6();
    void thread_ap_ready();
    void thread_ap_reset_idle_pp0();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_icmp_ln19_1_fu_312_p2();
    void thread_icmp_ln19_2_fu_318_p2();
    void thread_icmp_ln19_3_fu_324_p2();
    void thread_icmp_ln19_4_fu_330_p2();
    void thread_icmp_ln19_5_fu_336_p2();
    void thread_icmp_ln19_6_fu_342_p2();
    void thread_icmp_ln19_7_fu_348_p2();
    void thread_icmp_ln19_fu_306_p2();
    void thread_icmp_ln46_fu_264_p2();
    void thread_mul_ln1118_75_fu_552_p0();
    void thread_mul_ln1118_75_fu_552_p1();
    void thread_mul_ln1118_75_fu_552_p2();
    void thread_mul_ln1118_76_fu_581_p0();
    void thread_mul_ln1118_76_fu_581_p1();
    void thread_mul_ln1118_76_fu_581_p2();
    void thread_mul_ln1118_77_fu_610_p0();
    void thread_mul_ln1118_77_fu_610_p1();
    void thread_mul_ln1118_77_fu_610_p2();
    void thread_mul_ln1118_78_fu_639_p0();
    void thread_mul_ln1118_78_fu_639_p1();
    void thread_mul_ln1118_78_fu_639_p2();
    void thread_mul_ln1118_79_fu_668_p0();
    void thread_mul_ln1118_79_fu_668_p00();
    void thread_mul_ln1118_79_fu_668_p1();
    void thread_mul_ln1118_79_fu_668_p2();
    void thread_mul_ln1118_fu_520_p0();
    void thread_mul_ln1118_fu_520_p1();
    void thread_mul_ln1118_fu_520_p2();
    void thread_or_ln19_1_fu_376_p2();
    void thread_or_ln19_2_fu_390_p2();
    void thread_or_ln19_3_fu_404_p2();
    void thread_or_ln19_4_fu_418_p2();
    void thread_or_ln19_5_fu_432_p2();
    void thread_or_ln19_6_fu_446_p2();
    void thread_or_ln19_fu_362_p2();
    void thread_select_ln19_1_fu_368_p3();
    void thread_select_ln19_2_fu_382_p3();
    void thread_select_ln19_3_fu_396_p3();
    void thread_select_ln19_4_fu_410_p3();
    void thread_select_ln19_5_fu_424_p3();
    void thread_select_ln19_6_fu_438_p3();
    void thread_select_ln19_7_fu_452_p3();
    void thread_select_ln19_fu_354_p3();
    void thread_sext_ln703_1_fu_568_p1();
    void thread_sext_ln703_2_fu_597_p1();
    void thread_sext_ln703_3_fu_626_p1();
    void thread_sext_ln703_4_fu_655_p1();
    void thread_sext_ln703_5_fu_684_p1();
    void thread_sext_ln703_fu_536_p1();
    void thread_tmp_1_fu_674_p4();
    void thread_trunc_ln59_fu_460_p1();
    void thread_trunc_ln708_84_fu_587_p4();
    void thread_trunc_ln708_85_fu_616_p4();
    void thread_trunc_ln708_86_fu_645_p4();
    void thread_trunc_ln708_s_fu_558_p4();
    void thread_trunc_ln_fu_526_p4();
    void thread_w2_V_address0();
    void thread_w2_V_ce0();
    void thread_w_index_fu_258_p2();
    void thread_zext_ln1116_fu_514_p1();
    void thread_zext_ln59_fu_253_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
